package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

type Node struct {
	Name     string
	FullPath string
	IsLeaf   bool
	Params   []string
	Children map[string]*Node
}

var paramRegexp = regexp.MustCompile(`{{\s*\.(\w+)\s*}}`)

func main() {
	root, err := collectTree()
	if err != nil {
		panic(err)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("package i18n\n\n")
	out.WriteString("type MessageID string\n\n")

	out.WriteString("var (\n")
	for _, childName := range sortedKeys(root.Children) {
		child := root.Children[childName]
		writeStructDefinition(&out, child, 1)
	}
	out.WriteString(")\n\n")

	writeArgsFunctions(&out, root)

	if err := os.WriteFile("./keys.go", out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func writeStructDefinition(out *bytes.Buffer, node *Node, indent int) {
	tabs := strings.Repeat("\t", indent)
	goName := toGoName(node.Name)

	if node.IsLeaf {
		return
	}

	fmt.Fprintf(out, "%s%s = struct {\n", tabs, goName)

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		childGoName := toGoName(child.Name)
		if child.IsLeaf {
			fmt.Fprintf(out, "%s\t%s MessageID\n", tabs, childGoName)
		} else {
			writeStructFieldType(out, child, indent+1)
		}
	}

	fmt.Fprintf(out, "%s}{\n", tabs)
	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		childGoName := toGoName(child.Name)
		if child.IsLeaf {
			fmt.Fprintf(out, "%s\t%s: %q,\n", tabs, childGoName, child.FullPath)
		} else {
			writeStructFieldInit(out, child, indent+1)
		}
	}
	fmt.Fprintf(out, "%s}\n", tabs)
}

func writeStructFieldType(out *bytes.Buffer, node *Node, indent int) {
	tabs := strings.Repeat("\t", indent)
	fmt.Fprintf(out, "%s%s struct {\n", tabs, toGoName(node.Name))
	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		if child.IsLeaf {
			fmt.Fprintf(out, "%s\t%s MessageID\n", tabs, toGoName(child.Name))
		} else {
			writeStructFieldType(out, child, indent+1)
		}
	}
	fmt.Fprintf(out, "%s}\n", tabs)
}

func writeStructFieldInit(out *bytes.Buffer, node *Node, indent int) {
	tabs := strings.Repeat("\t", indent)
	fmt.Fprintf(out, "%s%s: struct {\n", tabs, toGoName(node.Name))

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		if child.IsLeaf {
			fmt.Fprintf(out, "%s\t%s MessageID\n", tabs, toGoName(child.Name))
		} else {
			writeStructFieldType(out, child, indent+1)
		}
	}

	fmt.Fprintf(out, "%s}{\n", tabs)
	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		if child.IsLeaf {
			fmt.Fprintf(out, "%s\t%s: %q,\n", tabs, toGoName(child.Name), child.FullPath)
		} else {
			writeStructFieldInit(out, child, indent+1)
		}
	}
	fmt.Fprintf(out, "%s},\n", tabs)
}

func writeArgsFunctions(out *bytes.Buffer, node *Node) {
	if node.IsLeaf && len(node.Params) > 0 {
		parts := strings.Split(node.FullPath, ".")
		for i := range parts {
			parts[i] = toGoName(parts[i])
		}
		funcName := strings.Join(parts, "") + "Args"

		fmt.Fprintf(out, "func %s(\n", funcName)
		for _, param := range node.Params {
			fmt.Fprintf(out, "\t%s any,\n", lowerFirst(param))
		}
		out.WriteString(") map[string]any {\n")
		out.WriteString("\treturn map[string]any{\n")
		for _, param := range node.Params {
			fmt.Fprintf(out, "\t\t%q: %s,\n", param, lowerFirst(param))
		}
		out.WriteString("\t}\n}\n\n")
	}

	for _, childName := range sortedKeys(node.Children) {
		writeArgsFunctions(out, node.Children[childName])
	}
}

func collectTree() (*Node, error) {
	root := &Node{Name: "root", Children: make(map[string]*Node)}
	entries, err := os.ReadDir("locales")
	if err != nil {
		return nil, err
	}

	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".toml" {
			continue
		}

		data, err := os.ReadFile(filepath.Join("locales", entry.Name()))
		if err != nil {
			return nil, err
		}

		var rawMap map[string]any
		if err := toml.Unmarshal(data, &rawMap); err != nil {
			return nil, err
		}

		buildTreeFromMap(root, rawMap, "")
	}

	return root, nil
}

func buildTreeFromMap(current *Node, raw map[string]any, prefix string) {
	for key, val := range raw {
		fullPath := key
		if prefix != "" {
			fullPath = prefix + "." + key
		}

		if subMap, ok := val.(map[string]any); ok {
			if otherVal, hasOther := subMap["other"].(string); hasOther {
				node, exists := current.Children[key]
				if !exists {
					node = &Node{Name: key, FullPath: fullPath, IsLeaf: true}
					current.Children[key] = node
				}
				node.Params = mergeParams(node.Params, extractParams(otherVal))
			} else {
				node, exists := current.Children[key]
				if !exists {
					node = &Node{Name: key, FullPath: fullPath, IsLeaf: false, Children: make(map[string]*Node)}
					current.Children[key] = node
				}
				buildTreeFromMap(node, subMap, fullPath)
			}
		}
	}
}

func extractParams(text string) []string {
	matches := paramRegexp.FindAllStringSubmatch(text, -1)
	seen := make(map[string]struct{})
	var params []string
	for _, match := range matches {
		name := match[1]
		if _, ok := seen[name]; !ok {
			seen[name] = struct{}{}
			params = append(params, name)
		}
	}
	sort.Strings(params)
	return params
}

func mergeParams(a, b []string) []string {
	seen := make(map[string]struct{})
	for _, v := range a {
		seen[v] = struct{}{}
	}
	for _, v := range b {
		seen[v] = struct{}{}
	}
	result := make([]string, 0, len(seen))
	for v := range seen {
		result = append(result, v)
	}
	sort.Strings(result)
	return result
}

func toGoName(key string) string {
	parts := strings.FieldsFunc(key, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	for i := range parts {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func sortedKeys(m map[string]*Node) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
