package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

type Node struct {
	Name     string
	FullPath string
	IsLeaf   bool
	Params   []string
	Children map[string]*Node
}

var paramRegexp = regexp.MustCompile(`{{\s*\.(\w+)\s*}}`)

func main() {
	root, err := collectTree()
	if err != nil {
		panic(err)
	}

	var out bytes.Buffer

	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("package i18n\n\n")
	out.WriteString("type MessageID string\n\n")

	out.WriteString("var (\n")

	for _, childName := range sortedKeys(root.Children) {
		child := root.Children[childName]
		writeStructDefinition(&out, child, 1)
	}

	out.WriteString(")\n\n")

	writeDataStructs(&out, root)

	// #nosec G306 -- generated Go source file is intended to be world-readable
	if err := os.WriteFile("./keys.go", out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func writeStructDefinition(out *bytes.Buffer, node *Node, indent int) {
	tabs := strings.Repeat("\t", indent)
	goName := toGoName(node.Name)

	if node.IsLeaf {
		return
	}

	_, _ = fmt.Fprintf(out, "%s%s = struct {\n", tabs, goName)

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		childGoName := toGoName(child.Name)

		if child.IsLeaf {
			_, _ = fmt.Fprintf(out, "%s\t%s MessageID\n", tabs, childGoName)
		} else {
			writeStructFieldType(out, child, indent+1)
		}
	}

	_, _ = fmt.Fprintf(out, "%s}{\n", tabs)

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		childGoName := toGoName(child.Name)

		if child.IsLeaf {
			_, _ = fmt.Fprintf(out, "%s\t%s: %q,\n", tabs, childGoName, child.FullPath)
		} else {
			writeStructFieldInit(out, child, indent+1)
		}
	}

	_, _ = fmt.Fprintf(out, "%s}\n", tabs)
}

func writeStructFieldType(out *bytes.Buffer, node *Node, indent int) {
	tabs := strings.Repeat("\t", indent)

	_, _ = fmt.Fprintf(out, "%s%s struct {\n", tabs, toGoName(node.Name))

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		if child.IsLeaf {
			_, _ = fmt.Fprintf(out, "%s\t%s MessageID\n", tabs, toGoName(child.Name))
		} else {
			writeStructFieldType(out, child, indent+1)
		}
	}

	_, _ = fmt.Fprintf(out, "%s}\n", tabs)
}

func writeStructFieldInit(out *bytes.Buffer, node *Node, indent int) {
	tabs := strings.Repeat("\t", indent)

	_, _ = fmt.Fprintf(out, "%s%s: struct {\n", tabs, toGoName(node.Name))

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		if child.IsLeaf {
			_, _ = fmt.Fprintf(out, "%s\t%s MessageID\n", tabs, toGoName(child.Name))
		} else {
			writeStructFieldType(out, child, indent+1)
		}
	}

	_, _ = fmt.Fprintf(out, "%s}{\n", tabs)

	for _, childName := range sortedKeys(node.Children) {
		child := node.Children[childName]
		if child.IsLeaf {
			_, _ = fmt.Fprintf(out, "%s\t%s: %q,\n", tabs, toGoName(child.Name), child.FullPath)
		} else {
			writeStructFieldInit(out, child, indent+1)
		}
	}

	_, _ = fmt.Fprintf(out, "%s},\n", tabs)
}

func writeDataStructs(out *bytes.Buffer, node *Node) {
	if node.IsLeaf && len(node.Params) > 0 {
		parts := strings.Split(node.FullPath, ".")
		for i := range parts {
			parts[i] = toGoName(parts[i])
		}

		typeName := strings.Join(parts, "") + "Data"

		_, _ = fmt.Fprintf(out, "type %s struct {\n", typeName)

		for _, param := range node.Params {
			_, _ = fmt.Fprintf(out, "\t%s any\n", toGoName(param))
		}

		out.WriteString("}\n\n")
	}

	for _, child := range node.Children {
		writeDataStructs(out, child)
	}
}

func collectTree() (*Node, error) {
	root := &Node{
		Name:     "root",
		Children: make(map[string]*Node),
	}

	err := filepath.Walk("locales", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() || filepath.Ext(path) != ".toml" {
			return nil
		}

		//nolint:gosec // G122,G304: trusted repository files
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		var raw map[string]any

		if err := toml.Unmarshal(data, &raw); err != nil {
			return err
		}

		buildTreeFromMap(root, raw, "")

		return nil
	})

	return root, err
}

func buildTreeFromMap(current *Node, raw map[string]any, prefix string) {
	for key, val := range raw {
		fullPath := key
		if prefix != "" {
			fullPath = prefix + "." + key
		}

		if subStr, ok := val.(string); ok {
			node, exists := current.Children[key]
			if !exists {
				node = &Node{Name: key, FullPath: fullPath, IsLeaf: true}
				current.Children[key] = node
			}
			node.Params = mergeParams(node.Params, extractParams(subStr))
		} else if subMap, ok := val.(map[string]any); ok {
			if isPluralMap(subMap) || isGenderMap(subMap) {
				node, exists := current.Children[key]
				if !exists {
					node = &Node{Name: key, FullPath: fullPath, IsLeaf: true}
					current.Children[key] = node
				}
				for _, subVal := range subMap {
					if str, ok := subVal.(string); ok {
						node.Params = mergeParams(node.Params, extractParams(str))
					} else if innerMap, ok := subVal.(map[string]any); ok {
						for _, innerVal := range innerMap {
							if str2, ok := innerVal.(string); ok {
								node.Params = mergeParams(node.Params, extractParams(str2))
							}
						}
					}
				}
			} else {
				node, exists := current.Children[key]
				if !exists {
					node = &Node{Name: key, FullPath: fullPath, IsLeaf: false, Children: make(map[string]*Node)}
					current.Children[key] = node
				}
				buildTreeFromMap(node, subMap, fullPath)
			}
		}
	}
}

func isPluralMap(m map[string]any) bool {
	return m["other"] != nil
}

func isGenderMap(m map[string]any) bool {
	return m["male"] != nil && m["female"] != nil
}

func extractParams(text string) []string {
	matches := paramRegexp.FindAllStringSubmatch(text, -1)

	seen := make(map[string]struct{})

	var params []string

	for _, match := range matches {
		name := match[1]
		if _, ok := seen[name]; ok {
			continue
		}

		seen[name] = struct{}{}
		params = append(params, name)
	}

	return params
}

func mergeParams(a, b []string) []string {
	seen := make(map[string]struct{})
	result := make([]string, 0, len(a)+len(b))

	for _, v := range a {
		if _, ok := seen[v]; !ok {
			seen[v] = struct{}{}
			result = append(result, v)
		}
	}

	for _, v := range b {
		if _, ok := seen[v]; !ok {
			seen[v] = struct{}{}
			result = append(result, v)
		}
	}

	return result
}

func toGoName(key string) string {
	parts := strings.FieldsFunc(key, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	for i := range parts {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}

	return strings.Join(parts, "")
}

func sortedKeys(m map[string]*Node) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	return keys
}
