package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

func main() {
	keys, err := collectKeys()
	if err != nil {
		panic(err)
	}

	sort.Strings(keys)

	var out bytes.Buffer

	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("package i18n\n\n")
	out.WriteString("type MessageID string\n\n")
	out.WriteString("const (\n")

	for _, key := range keys {
		_, _ = fmt.Fprintf(
			&out,
			"\t%s MessageID = %q\n",
			toGoName(key),
			key,
		)
	}

	out.WriteString(")\n")

	// #nosec G306 -- generated source file should be readable by others
	if err := os.WriteFile("./keys.go", out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func collectKeys() ([]string, error) {
	input := "locales"

	entries, err := os.ReadDir(input)
	if err != nil {
		return nil, err
	}

	set := make(map[string]struct{})

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		data, err := os.ReadFile(filepath.Join(input, entry.Name()))
		if err != nil {
			return nil, err
		}

		var messages map[string]any

		if err := toml.Unmarshal(data, &messages); err != nil {
			return nil, err
		}

		for key := range messages {
			set[key] = struct{}{}
		}
	}

	keys := make([]string, 0, len(set))

	for key := range set {
		keys = append(keys, key)
	}

	return keys, nil
}

func toGoName(key string) string {
	parts := strings.FieldsFunc(key, func(r rune) bool {
		return r == '_' || r == '-' || r == '.'
	})

	for i := range parts {
		if parts[i] == "" {
			continue
		}

		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}

	return strings.Join(parts, "")
}
