// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chatmember.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMember = `-- name: CreateChatMember :exec
INSERT INTO chat_members(chat_id, user_id, tag, status, rest_until, left_at, rest_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateChatMemberParams struct {
	ChatID     int64              `db:"chat_id" json:"chatId"`
	UserID     int64              `db:"user_id" json:"userId"`
	Tag        pgtype.Text        `db:"tag" json:"tag"`
	Status     int16              `db:"status" json:"status"`
	RestUntil  pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	LeftAt     pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	RestReason pgtype.Text        `db:"rest_reason" json:"restReason"`
}

func (q *Queries) CreateChatMember(ctx context.Context, arg CreateChatMemberParams) error {
	_, err := q.db.Exec(ctx, createChatMember,
		arg.ChatID,
		arg.UserID,
		arg.Tag,
		arg.Status,
		arg.RestUntil,
		arg.LeftAt,
		arg.RestReason,
	)
	return err
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_members.chat_id, chat_members.user_id, chat_members.joined_at, chat_members.rest_until, chat_members.tag, chat_members.left_at, chat_members.rest_reason, chat_members.emoji, chat_members.status, chat_members.emoji_json, chat_members.exclude_from_call, users.id, users.username, users.first_name, users.last_name, users.created_at, users.gender, users.emoji, users.custom_emoji_id, users.emoji_json, users.is_bot, chats.id, chats.norm_warn, chats.newbie_threshold_days, chats.ai_system_prompt, chats.max_ladder, chats.call_on_join, chats.welcome_call_message, chats.week_start_day, chats.max_warns, chats.norm_ban, chats.command_prefix, chats.allow_prefixless, chats.mentions_per_message, chats.mention_types, chats.title, chats.tags_enabled, chats.week_start_time, chats.broadcast_enabled, chats.removed_at, chats.emojis_enabled, chats.skip_call_confirmation
FROM chat_members
         JOIN users ON users.id = user_id
         JOIN chats ON chat_members.chat_id = chats.id AND chat_id = $1 AND user_id = $2
`

type GetChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type GetChatMemberRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
	Chat       Chat       `db:"chat" json:"chat"`
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (GetChatMemberRow, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChatID, arg.UserID)
	var i GetChatMemberRow
	err := row.Scan(
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.ChatMember.ExcludeFromCall,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
		&i.User.IsBot,
		&i.Chat.ID,
		&i.Chat.NormWarn,
		&i.Chat.NewbieThresholdDays,
		&i.Chat.AiSystemPrompt,
		&i.Chat.MaxLadder,
		&i.Chat.CallOnJoin,
		&i.Chat.WelcomeCallMessage,
		&i.Chat.WeekStartDay,
		&i.Chat.MaxWarns,
		&i.Chat.NormBan,
		&i.Chat.CommandPrefix,
		&i.Chat.AllowPrefixless,
		&i.Chat.MentionsPerMessage,
		&i.Chat.MentionTypes,
		&i.Chat.Title,
		&i.Chat.TagsEnabled,
		&i.Chat.WeekStartTime,
		&i.Chat.BroadcastEnabled,
		&i.Chat.RemovedAt,
		&i.Chat.EmojisEnabled,
		&i.Chat.SkipCallConfirmation,
	)
	return i, err
}

const markAllChatMembersLeftExcept = `-- name: MarkAllChatMembersLeftExcept :exec
UPDATE chat_members
SET left_at = $1
WHERE chat_id = $2
  AND left_at IS NULL
  AND user_id <> ALL ($3::BIGINT[])
`

type MarkAllChatMembersLeftExceptParams struct {
	LeftAt  pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	ChatID  int64              `db:"chat_id" json:"chatId"`
	UserIds []int64            `db:"user_ids" json:"userIds"`
}

func (q *Queries) MarkAllChatMembersLeftExcept(ctx context.Context, arg MarkAllChatMembersLeftExceptParams) error {
	_, err := q.db.Exec(ctx, markAllChatMembersLeftExcept, arg.LeftAt, arg.ChatID, arg.UserIds)
	return err
}

const markChatMemberLeft = `-- name: MarkChatMemberLeft :exec
UPDATE chat_members
SET left_at = $1
WHERE user_id = $2
  AND chat_id = $3
`

type MarkChatMemberLeftParams struct {
	LeftAt pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	UserID int64              `db:"user_id" json:"userId"`
	ChatID int64              `db:"chat_id" json:"chatId"`
}

func (q *Queries) MarkChatMemberLeft(ctx context.Context, arg MarkChatMemberLeftParams) error {
	_, err := q.db.Exec(ctx, markChatMemberLeft, arg.LeftAt, arg.UserID, arg.ChatID)
	return err
}

const setChatMemberTag = `-- name: SetChatMemberTag :exec
UPDATE chat_members
SET tag = $1
WHERE user_id = $2
  AND chat_id = $3
`

type SetChatMemberTagParams struct {
	Tag    pgtype.Text `db:"tag" json:"tag"`
	UserID int64       `db:"user_id" json:"userId"`
	ChatID int64       `db:"chat_id" json:"chatId"`
}

func (q *Queries) SetChatMemberTag(ctx context.Context, arg SetChatMemberTagParams) error {
	_, err := q.db.Exec(ctx, setChatMemberTag, arg.Tag, arg.UserID, arg.ChatID)
	return err
}

const upsertChatMembersAndUsers = `-- name: UpsertChatMembersAndUsers :exec
WITH upserted_users AS (
    INSERT INTO users (
                       id,
                       username,
                       first_name,
                       last_name,
                       is_bot
        )
        SELECT u.id,
               u.username,
               u.first_name,
               u.last_name,
               COALESCE(u.is_bot, false)
        FROM ROWS FROM (
                 UNNEST($2::BIGINT[]),
                 UNNEST($5::TEXT[]),
                 UNNEST($6::TEXT[]),
                 UNNEST($7::TEXT[]),
                 UNNEST($8::BOOLEAN[])
                 ) AS u(id, username, first_name, last_name, is_bot)
        ON CONFLICT (id) DO UPDATE SET
            username = EXCLUDED.username,
            first_name = EXCLUDED.first_name,
            last_name = EXCLUDED.last_name,
            is_bot = EXCLUDED.is_bot
        RETURNING id)
INSERT
INTO chat_members (chat_id, user_id, tag, status)
SELECT $1,
       m.user_id,
       m.tag,
       m.status
FROM ROWS FROM (
         UNNEST($2::BIGINT[]),
         UNNEST($3::TEXT[]),
         UNNEST($4::SMALLINT[])
         ) AS m(user_id, tag, status)
         JOIN upserted_users AS uu ON m.user_id = uu.id
ON CONFLICT (chat_id, user_id)
    DO UPDATE
    SET tag     = CASE
                      WHEN EXCLUDED.tag <> '' THEN EXCLUDED.tag
                      ELSE chat_members.tag
        END,
        status  = GREATEST(EXCLUDED.status, chat_members.status),
        left_at = CASE
                      WHEN chat_members.left_at IS NOT NULL THEN NULL
                      ELSE chat_members.left_at
            END
`

type UpsertChatMembersAndUsersParams struct {
	ChatID     int64    `db:"chat_id" json:"chatId"`
	UserIds    []int64  `db:"user_ids" json:"userIds"`
	Tags       []string `db:"tags" json:"tags"`
	Statuses   []int16  `db:"statuses" json:"statuses"`
	Usernames  []string `db:"usernames" json:"usernames"`
	FirstNames []string `db:"first_names" json:"firstNames"`
	LastNames  []string `db:"last_names" json:"lastNames"`
	IsBots     []bool   `db:"is_bots" json:"isBots"`
}

func (q *Queries) UpsertChatMembersAndUsers(ctx context.Context, arg UpsertChatMembersAndUsersParams) error {
	_, err := q.db.Exec(ctx, upsertChatMembersAndUsers,
		arg.ChatID,
		arg.UserIds,
		arg.Tags,
		arg.Statuses,
		arg.Usernames,
		arg.FirstNames,
		arg.LastNames,
		arg.IsBots,
	)
	return err
}
