// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chatmember.sql

package db

import (
	"context"

	"activity-bot/internal/emoji"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMember = `-- name: CreateChatMember :exec
INSERT INTO chat_members(chat_id, user_id, tag, status, rest_until, left_at, rest_reason, emoji_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateChatMemberParams struct {
	ChatID     int64              `db:"chat_id" json:"chatId"`
	UserID     int64              `db:"user_id" json:"userId"`
	Tag        pgtype.Text        `db:"tag" json:"tag"`
	Status     int16              `db:"status" json:"status"`
	RestUntil  pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	LeftAt     pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	RestReason pgtype.Text        `db:"rest_reason" json:"restReason"`
	EmojiJson  emoji.Emojis       `db:"emoji_json" json:"emojiJson"`
}

func (q *Queries) CreateChatMember(ctx context.Context, arg CreateChatMemberParams) error {
	_, err := q.db.Exec(ctx, createChatMember,
		arg.ChatID,
		arg.UserID,
		arg.Tag,
		arg.Status,
		arg.RestUntil,
		arg.LeftAt,
		arg.RestReason,
		arg.EmojiJson,
	)
	return err
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_members.chat_id, chat_members.user_id, chat_members.joined_at, chat_members.rest_until, chat_members.tag, chat_members.left_at, chat_members.rest_reason, chat_members.emoji, chat_members.status, chat_members.emoji_json, chat_members.exclude_from_call, users.id, users.username, users.first_name, users.last_name, users.created_at, users.gender, users.emoji, users.custom_emoji_id, users.emoji_json, users.is_bot, chats.id, chats.norm_warn, chats.newbie_threshold_days, chats.ai_system_prompt, chats.max_ladder, chats.call_on_join, chats.welcome_call_message, chats.week_start_day, chats.max_warns, chats.norm_ban, chats.command_prefix, chats.allow_prefixless, chats.mentions_per_message, chats.mention_types, chats.title, chats.tags_enabled, chats.week_start_time, chats.broadcast_enabled, chats.removed_at, chats.emojis_enabled, chats.skip_call_confirmation
FROM chat_members
         JOIN users ON users.id = user_id
         JOIN chats ON chat_members.chat_id = chats.id
    AND chat_id = $1
    AND user_id = $2
    AND users.is_bot = $3
`

type GetChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
	IsBot  bool  `db:"is_bot" json:"isBot"`
}

type GetChatMemberRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
	Chat       Chat       `db:"chat" json:"chat"`
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (GetChatMemberRow, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChatID, arg.UserID, arg.IsBot)
	var i GetChatMemberRow
	err := row.Scan(
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.ChatMember.ExcludeFromCall,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
		&i.User.IsBot,
		&i.Chat.ID,
		&i.Chat.NormWarn,
		&i.Chat.NewbieThresholdDays,
		&i.Chat.AiSystemPrompt,
		&i.Chat.MaxLadder,
		&i.Chat.CallOnJoin,
		&i.Chat.WelcomeCallMessage,
		&i.Chat.WeekStartDay,
		&i.Chat.MaxWarns,
		&i.Chat.NormBan,
		&i.Chat.CommandPrefix,
		&i.Chat.AllowPrefixless,
		&i.Chat.MentionsPerMessage,
		&i.Chat.MentionTypes,
		&i.Chat.Title,
		&i.Chat.TagsEnabled,
		&i.Chat.WeekStartTime,
		&i.Chat.BroadcastEnabled,
		&i.Chat.RemovedAt,
		&i.Chat.EmojisEnabled,
		&i.Chat.SkipCallConfirmation,
	)
	return i, err
}
