// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: norm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNorm = `-- name: DeleteNorm :exec
DELETE
FROM chat_norms
WHERE chat_id = $1
  AND name = $2
`

type DeleteNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) DeleteNorm(ctx context.Context, arg DeleteNormParams) error {
	_, err := q.db.Exec(ctx, deleteNorm, arg.ChatID, arg.Name)
	return err
}

const getNorm = `-- name: GetNorm :one
SELECT id, chat_id, name, value
FROM chat_norms
WHERE chat_id = $1
  AND name ILIKE '%' || $2::text || '%'
LIMIT 1
`

type GetNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) GetNorm(ctx context.Context, arg GetNormParams) (ChatNorm, error) {
	row := q.db.QueryRow(ctx, getNorm, arg.ChatID, arg.Name)
	var i ChatNorm
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Value,
	)
	return i, err
}

const listNorms = `-- name: ListNorms :many
SELECT id, chat_id, name, value
FROM chat_norms
WHERE chat_id = $1
`

func (q *Queries) ListNorms(ctx context.Context, chatID int64) ([]ChatNorm, error) {
	rows, err := q.db.Query(ctx, listNorms, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatNorm{}
	for rows.Next() {
		var i ChatNorm
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNormsWithMembers = `-- name: ListNormsWithMembers :many
SELECT n.id, n.chat_id, n.name, n.value,
       cmn.user_id
FROM chat_norms n
         LEFT JOIN chat_member_norms cmn
                   ON cmn.norm_id = n.id
WHERE n.chat_id = $1
ORDER BY n.id
`

type ListNormsWithMembersRow struct {
	ChatNorm ChatNorm    `db:"chat_norm" json:"chatNorm"`
	UserID   pgtype.Int8 `db:"user_id" json:"userId"`
}

func (q *Queries) ListNormsWithMembers(ctx context.Context, chatID int64) ([]ListNormsWithMembersRow, error) {
	rows, err := q.db.Query(ctx, listNormsWithMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNormsWithMembersRow{}
	for rows.Next() {
		var i ListNormsWithMembersRow
		if err := rows.Scan(
			&i.ChatNorm.ID,
			&i.ChatNorm.ChatID,
			&i.ChatNorm.Name,
			&i.ChatNorm.Value,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNorm = `-- name: SetNorm :exec
INSERT INTO chat_norms(chat_id, name, value)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id, name) DO UPDATE SET value = $3
`

type SetNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
	Value  int32  `db:"value" json:"value"`
}

func (q *Queries) SetNorm(ctx context.Context, arg SetNormParams) error {
	_, err := q.db.Exec(ctx, setNorm, arg.ChatID, arg.Name, arg.Value)
	return err
}
