// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chatStats = `-- name: ChatStats :many
SELECT
    cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, cm.exclude_from_call,
    u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json, u.is_bot,
    COUNT(m.chat_id) AS messages_count
FROM chat_members cm
         JOIN users u
              ON u.id = cm.user_id
         LEFT JOIN messages m
                   ON m.chat_id = cm.chat_id
                       AND m.user_id = cm.user_id
                       AND ($1::timestamptz IS NULL OR m.created_at >= $1::timestamptz)
                       AND ($2::timestamptz IS NULL OR m.created_at < $2::timestamptz)
WHERE cm.chat_id = $3
  AND cm.left_at IS NULL
  AND (cm.rest_until IS NULL OR cm.rest_until < now())
  AND NOT u.is_bot
GROUP BY cm.chat_id, cm.user_id, u.id
ORDER BY messages_count DESC
`

type ChatStatsParams struct {
	FromDate pgtype.Timestamptz `db:"from_date" json:"fromDate"`
	ToDate   pgtype.Timestamptz `db:"to_date" json:"toDate"`
	ChatID   int64              `db:"chat_id" json:"chatId"`
}

type ChatStatsRow struct {
	ChatMember    ChatMember `db:"chat_member" json:"chatMember"`
	User          User       `db:"user" json:"user"`
	MessagesCount int64      `db:"messages_count" json:"messagesCount"`
}

func (q *Queries) ChatStats(ctx context.Context, arg ChatStatsParams) ([]ChatStatsRow, error) {
	rows, err := q.db.Query(ctx, chatStats, arg.FromDate, arg.ToDate, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatStatsRow{}
	for rows.Next() {
		var i ChatStatsRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.User.IsBot,
			&i.MessagesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
