// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatAdmin = `-- name: AddChatAdmin :exec
UPDATE chat_members
SET status = 'administrator'
WHERE chat_id = $1
  AND user_id = $2
`

type AddChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) AddChatAdmin(ctx context.Context, arg AddChatAdminParams) error {
	_, err := q.db.Exec(ctx, addChatAdmin, arg.ChatID, arg.UserID)
	return err
}

const getChatAdmins = `-- name: GetChatAdmins :many
SELECT u.id, u.username, u.first_name, u.last_name, cm.joined_at as created_at
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.status IN ('administrator', 'creator')
ORDER BY cm.joined_at
`

type GetChatAdminsRow struct {
	ID        int64              `db:"id" json:"id"`
	Username  pgtype.Text        `db:"username" json:"username"`
	FirstName pgtype.Text        `db:"first_name" json:"firstName"`
	LastName  pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) GetChatAdmins(ctx context.Context, chatID int64) ([]GetChatAdminsRow, error) {
	rows, err := q.db.Query(ctx, getChatAdmins, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAdminsRow{}
	for rows.Next() {
		var i GetChatAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMemberStatus = `-- name: GetChatMemberStatus :one
SELECT status
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type GetChatMemberStatusParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetChatMemberStatus(ctx context.Context, arg GetChatMemberStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getChatMemberStatus, arg.ChatID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getChatsWhereUserIsAdmin = `-- name: GetChatsWhereUserIsAdmin :many
SELECT c.id, c.norm_warn, c.newbie_threshold_days, c.ai_system_prompt, c.max_ladder, c.call_on_join, c.welcome_call_message, c.week_start_day, c.max_warns, c.norm_ban, c.command_prefix, c.allow_prefixless, c.mentions_per_message, c.mention_types, c.title, c.tags_enabled
FROM chats c
JOIN chat_members cm ON c.id = cm.chat_id
WHERE c.id < 0 AND cm.user_id = $1 AND cm.status IN ('administrator', 'creator') AND title <> ''
`

func (q *Queries) GetChatsWhereUserIsAdmin(ctx context.Context, userID int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChatsWhereUserIsAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.NormWarn,
			&i.NewbieThresholdDays,
			&i.AiSystemPrompt,
			&i.MaxLadder,
			&i.CallOnJoin,
			&i.WelcomeCallMessage,
			&i.WeekStartDay,
			&i.MaxWarns,
			&i.NormBan,
			&i.CommandPrefix,
			&i.AllowPrefixless,
			&i.MentionsPerMessage,
			&i.MentionTypes,
			&i.Title,
			&i.TagsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersWithExpiredMute = `-- name: GetMembersWithExpiredMute :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.custom_title, cm.status, cm.left_at
FROM moderation_actions ma
         JOIN chat_members cm ON ma.chat_id = cm.chat_id AND ma.user_id = cm.user_id
WHERE ma.type = 'mute'
  AND ma.revoked_at IS NULL
  AND ma.expires_at <= NOW()
`

func (q *Queries) GetMembersWithExpiredMute(ctx context.Context) ([]ChatMember, error) {
	rows, err := q.db.Query(ctx, getMembersWithExpiredMute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMember{}
	for rows.Next() {
		var i ChatMember
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.JoinedAt,
			&i.RestUntil,
			&i.CustomTitle,
			&i.Status,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChatAdmin = `-- name: IsChatAdmin :one
SELECT EXISTS(SELECT 1
              FROM chat_members
              WHERE chat_id = $1
                AND user_id = $2
                AND status IN ('administrator', 'creator'))
`

type IsChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) IsChatAdmin(ctx context.Context, arg IsChatAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatAdmin, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isChatCreator = `-- name: IsChatCreator :one
SELECT EXISTS(SELECT 1
              FROM chat_members
              WHERE chat_id = $1
                AND user_id = $2
                AND status = 'creator')
`

type IsChatCreatorParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) IsChatCreator(ctx context.Context, arg IsChatCreatorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatCreator, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeChatAdmin = `-- name: RemoveChatAdmin :exec
UPDATE chat_members
SET status = 'member'
WHERE chat_id = $1
  AND user_id = $2
`

type RemoveChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) RemoveChatAdmin(ctx context.Context, arg RemoveChatAdminParams) error {
	_, err := q.db.Exec(ctx, removeChatAdmin, arg.ChatID, arg.UserID)
	return err
}
