// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
)

const addChatAdmin = `-- name: AddChatAdmin :exec
UPDATE chat_members
SET status = 'administrator'
WHERE chat_id = $1
  AND user_id = $2
`

type AddChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) AddChatAdmin(ctx context.Context, arg AddChatAdminParams) error {
	_, err := q.db.Exec(ctx, addChatAdmin, arg.ChatID, arg.UserID)
	return err
}

const getChatAdmins = `-- name: GetChatAdmins :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.custom_title, cm.status, cm.left_at, cm.rest_reason, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.status IN ('administrator', 'creator')
ORDER BY cm.joined_at
`

type GetChatAdminsRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatAdmins(ctx context.Context, chatID int64) ([]GetChatAdminsRow, error) {
	rows, err := q.db.Query(ctx, getChatAdmins, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAdminsRow{}
	for rows.Next() {
		var i GetChatAdminsRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.CustomTitle,
			&i.ChatMember.Status,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMemberStatus = `-- name: GetChatMemberStatus :one
SELECT status
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type GetChatMemberStatusParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetChatMemberStatus(ctx context.Context, arg GetChatMemberStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getChatMemberStatus, arg.ChatID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getMembersWithExpiredMute = `-- name: GetMembersWithExpiredMute :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.custom_title, cm.status, cm.left_at, cm.rest_reason
FROM moderation_actions ma
         JOIN chat_members cm ON ma.chat_id = cm.chat_id AND ma.user_id = cm.user_id
WHERE ma.type = 'mute'
  AND ma.revoked_at IS NULL
  AND ma.expires_at <= NOW()
`

type GetMembersWithExpiredMuteRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
}

func (q *Queries) GetMembersWithExpiredMute(ctx context.Context) ([]GetMembersWithExpiredMuteRow, error) {
	rows, err := q.db.Query(ctx, getMembersWithExpiredMute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMembersWithExpiredMuteRow{}
	for rows.Next() {
		var i GetMembersWithExpiredMuteRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.CustomTitle,
			&i.ChatMember.Status,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChatAdmin = `-- name: IsChatAdmin :one
SELECT EXISTS(SELECT 1
              FROM chat_members
              WHERE chat_id = $1
                AND user_id = $2
                AND status IN ('administrator', 'creator'))
`

type IsChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) IsChatAdmin(ctx context.Context, arg IsChatAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatAdmin, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isChatCreator = `-- name: IsChatCreator :one
SELECT EXISTS(SELECT 1
              FROM chat_members
              WHERE chat_id = $1
                AND user_id = $2
                AND status = 'creator')
`

type IsChatCreatorParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) IsChatCreator(ctx context.Context, arg IsChatCreatorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatCreator, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeChatAdmin = `-- name: RemoveChatAdmin :exec
UPDATE chat_members
SET status = 'member'
WHERE chat_id = $1
  AND user_id = $2
`

type RemoveChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) RemoveChatAdmin(ctx context.Context, arg RemoveChatAdminParams) error {
	_, err := q.db.Exec(ctx, removeChatAdmin, arg.ChatID, arg.UserID)
	return err
}
