// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
)

const getChatAdmins = `-- name: GetChatAdmins :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.status > 0
ORDER BY cm.joined_at
`

type GetChatAdminsRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatAdmins(ctx context.Context, chatID int64) ([]GetChatAdminsRow, error) {
	rows, err := q.db.Query(ctx, getChatAdmins, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAdminsRow{}
	for rows.Next() {
		var i GetChatAdminsRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersWithExpiredMute = `-- name: GetMembersWithExpiredMute :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status
FROM moderation_actions ma
         JOIN chat_members cm ON ma.chat_id = cm.chat_id AND ma.user_id = cm.user_id
WHERE ma.type = 'mute'
  AND ma.revoked_at IS NULL
  AND ma.expires_at <= NOW()
`

type GetMembersWithExpiredMuteRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
}

func (q *Queries) GetMembersWithExpiredMute(ctx context.Context) ([]GetMembersWithExpiredMuteRow, error) {
	rows, err := q.db.Query(ctx, getMembersWithExpiredMute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMembersWithExpiredMuteRow{}
	for rows.Next() {
		var i GetMembersWithExpiredMuteRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChatMemberStatus = `-- name: SetChatMemberStatus :exec
UPDATE chat_members
SET status = $1
WHERE chat_id = $2
  AND user_id = $3
`

type SetChatMemberStatusParams struct {
	Status int16 `db:"status" json:"status"`
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) SetChatMemberStatus(ctx context.Context, arg SetChatMemberStatusParams) error {
	_, err := q.db.Exec(ctx, setChatMemberStatus, arg.Status, arg.ChatID, arg.UserID)
	return err
}
