// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banned.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banChat = `-- name: BanChat :exec
INSERT INTO banned_chats (
    chat_id,
    reason,
    expires_at
)
VALUES ($1, $2, $3)
    ON CONFLICT (chat_id)
DO UPDATE SET
    reason = EXCLUDED.reason,
           created_at = now(),
           expires_at = EXCLUDED.expires_at
`

type BanChatParams struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	Reason    pgtype.Text        `db:"reason" json:"reason"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) BanChat(ctx context.Context, arg BanChatParams) error {
	_, err := q.db.Exec(ctx, banChat, arg.ChatID, arg.Reason, arg.ExpiresAt)
	return err
}

const banUser = `-- name: BanUser :exec
INSERT INTO banned_users (
    user_id,
    reason,
    expires_at
)
VALUES ($1, $2, $3)
    ON CONFLICT (user_id)
DO UPDATE SET
    reason = EXCLUDED.reason,
           created_at = now(),
           expires_at = EXCLUDED.expires_at
`

type BanUserParams struct {
	UserID    int64              `db:"user_id" json:"userId"`
	Reason    pgtype.Text        `db:"reason" json:"reason"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.UserID, arg.Reason, arg.ExpiresAt)
	return err
}

const getBannedChats = `-- name: GetBannedChats :many
SELECT
    chat_id,
    reason,
    created_at,
    expires_at
FROM banned_chats
ORDER BY created_at DESC
`

func (q *Queries) GetBannedChats(ctx context.Context) ([]BannedChat, error) {
	rows, err := q.db.Query(ctx, getBannedChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BannedChat{}
	for rows.Next() {
		var i BannedChat
		if err := rows.Scan(
			&i.ChatID,
			&i.Reason,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBannedUsers = `-- name: GetBannedUsers :many
SELECT
    user_id,
    reason,
    created_at,
    expires_at
FROM banned_users
ORDER BY created_at DESC
`

func (q *Queries) GetBannedUsers(ctx context.Context) ([]BannedUser, error) {
	rows, err := q.db.Query(ctx, getBannedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BannedUser{}
	for rows.Next() {
		var i BannedUser
		if err := rows.Scan(
			&i.UserID,
			&i.Reason,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatBan = `-- name: GetChatBan :one
SELECT
    chat_id,
    reason,
    created_at,
    expires_at
FROM banned_chats
WHERE chat_id = $1
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetChatBan(ctx context.Context, chatID int64) (BannedChat, error) {
	row := q.db.QueryRow(ctx, getChatBan, chatID)
	var i BannedChat
	err := row.Scan(
		&i.ChatID,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserBan = `-- name: GetUserBan :one
SELECT
    user_id,
    reason,
    created_at,
    expires_at
FROM banned_users
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetUserBan(ctx context.Context, userID int64) (BannedUser, error) {
	row := q.db.QueryRow(ctx, getUserBan, userID)
	var i BannedUser
	err := row.Scan(
		&i.UserID,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isChatBanned = `-- name: IsChatBanned :one
SELECT EXISTS (
    SELECT 1
    FROM banned_chats
    WHERE chat_id = $1
      AND (expires_at IS NULL OR expires_at > now())
) AS banned
`

func (q *Queries) IsChatBanned(ctx context.Context, chatID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isChatBanned, chatID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const isUserBanned = `-- name: IsUserBanned :one
SELECT EXISTS (
    SELECT 1
    FROM banned_users
    WHERE user_id = $1
      AND (expires_at IS NULL OR expires_at > now())
) AS banned
`

func (q *Queries) IsUserBanned(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBanned, userID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const unbanChat = `-- name: UnbanChat :exec
DELETE FROM banned_chats
WHERE chat_id = $1
`

func (q *Queries) UnbanChat(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, unbanChat, chatID)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
DELETE FROM banned_users
WHERE user_id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, unbanUser, userID)
	return err
}
