// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatAdmin = `-- name: AddChatAdmin :exec
INSERT INTO chat_admins(chat_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) AddChatAdmin(ctx context.Context, arg AddChatAdminParams) error {
	_, err := q.db.Exec(ctx, addChatAdmin, arg.ChatID, arg.UserID)
	return err
}

const chatExemptUsers = `-- name: ChatExemptUsers :many
SELECT cm.user_id,
       u.username,
       u.first_name,
       u.last_name,
       cm.exempt_until
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.exempt_until IS NOT NULL
  AND cm.exempt_until >= now()
ORDER BY cm.exempt_until ASC
`

type ChatExemptUsersRow struct {
	UserID      int64              `db:"user_id" json:"userId"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
}

func (q *Queries) ChatExemptUsers(ctx context.Context, chatID int64) ([]ChatExemptUsersRow, error) {
	rows, err := q.db.Query(ctx, chatExemptUsers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatExemptUsersRow{}
	for rows.Next() {
		var i ChatExemptUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.ExemptUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChatMember = `-- name: DeleteChatMember :exec
DELETE FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type DeleteChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteChatMember(ctx context.Context, arg DeleteChatMemberParams) error {
	_, err := q.db.Exec(ctx, deleteChatMember, arg.ChatID, arg.UserID)
	return err
}

const ensureChatExists = `-- name: EnsureChatExists :exec
INSERT INTO chats(id, weekly_norm)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type EnsureChatExistsParams struct {
	ID         int64 `db:"id" json:"id"`
	WeeklyNorm int32 `db:"weekly_norm" json:"weeklyNorm"`
}

func (q *Queries) EnsureChatExists(ctx context.Context, arg EnsureChatExistsParams) error {
	_, err := q.db.Exec(ctx, ensureChatExists, arg.ID, arg.WeeklyNorm)
	return err
}

const ensureChatMemberExists = `-- name: EnsureChatMemberExists :exec
INSERT INTO chat_members(chat_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type EnsureChatMemberExistsParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) EnsureChatMemberExists(ctx context.Context, arg EnsureChatMemberExistsParams) error {
	_, err := q.db.Exec(ctx, ensureChatMemberExists, arg.ChatID, arg.UserID)
	return err
}

const exemptChatMember = `-- name: ExemptChatMember :exec
UPDATE chat_members
SET exempt_until = $1
WHERE chat_id = $2
  AND user_id = $3
`

type ExemptChatMemberParams struct {
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
}

func (q *Queries) ExemptChatMember(ctx context.Context, arg ExemptChatMemberParams) error {
	_, err := q.db.Exec(ctx, exemptChatMember, arg.ExemptUntil, arg.ChatID, arg.UserID)
	return err
}

const getChatAdmins = `-- name: GetChatAdmins :many
SELECT u.id, u.username, u.first_name, u.last_name, ca.created_at
FROM chat_admins ca
         JOIN users u ON u.id = ca.user_id
WHERE ca.chat_id = $1
ORDER BY ca.created_at
`

type GetChatAdminsRow struct {
	ID        int64              `db:"id" json:"id"`
	Username  pgtype.Text        `db:"username" json:"username"`
	FirstName pgtype.Text        `db:"first_name" json:"firstName"`
	LastName  pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) GetChatAdmins(ctx context.Context, chatID int64) ([]GetChatAdminsRow, error) {
	rows, err := q.db.Query(ctx, getChatAdmins, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAdminsRow{}
	for rows.Next() {
		var i GetChatAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_id, user_id, joined_at, exempt_until, custom_title
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type GetChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChatID, arg.UserID)
	var i ChatMember
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.ExemptUntil,
		&i.CustomTitle,
	)
	return i, err
}

const getChatMembersWithTitles = `-- name: GetChatMembersWithTitles :many
SELECT cm.user_id, cm.custom_title, u.first_name, u.last_name, u.username
FROM chat_members cm
JOIN users u ON cm.user_id = u.id
WHERE cm.chat_id = $1
  AND cm.custom_title IS NOT NULL
  AND cm.custom_title <> ''
`

type GetChatMembersWithTitlesRow struct {
	UserID      int64       `db:"user_id" json:"userId"`
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	FirstName   pgtype.Text `db:"first_name" json:"firstName"`
	LastName    pgtype.Text `db:"last_name" json:"lastName"`
	Username    pgtype.Text `db:"username" json:"username"`
}

func (q *Queries) GetChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetChatMembersWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, getChatMembersWithTitles, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersWithTitlesRow{}
	for rows.Next() {
		var i GetChatMembersWithTitlesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CustomTitle,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateChat = `-- name: GetOrCreateChat :one
INSERT INTO chats(id, weekly_norm)
VALUES ($1, $2)
ON CONFLICT(id) DO UPDATE SET weekly_norm = chats.weekly_norm
RETURNING id, weekly_norm
`

type GetOrCreateChatParams struct {
	ID         int64 `db:"id" json:"id"`
	WeeklyNorm int32 `db:"weekly_norm" json:"weeklyNorm"`
}

func (q *Queries) GetOrCreateChat(ctx context.Context, arg GetOrCreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, getOrCreateChat, arg.ID, arg.WeeklyNorm)
	var i Chat
	err := row.Scan(&i.ID, &i.WeeklyNorm)
	return i, err
}

const isChatAdmin = `-- name: IsChatAdmin :one
SELECT EXISTS(
    SELECT 1
    FROM chat_admins
    WHERE chat_id = $1
      AND user_id = $2
)
`

type IsChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) IsChatAdmin(ctx context.Context, arg IsChatAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatAdmin, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeChatAdmin = `-- name: RemoveChatAdmin :exec
DELETE FROM chat_admins
WHERE chat_id = $1
  AND user_id = $2
`

type RemoveChatAdminParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) RemoveChatAdmin(ctx context.Context, arg RemoveChatAdminParams) error {
	_, err := q.db.Exec(ctx, removeChatAdmin, arg.ChatID, arg.UserID)
	return err
}

const removeChatMemberExempt = `-- name: RemoveChatMemberExempt :exec
UPDATE chat_members
SET exempt_until = null
WHERE user_id = $1
  AND chat_id = $2
`

type RemoveChatMemberExemptParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) RemoveChatMemberExempt(ctx context.Context, arg RemoveChatMemberExemptParams) error {
	_, err := q.db.Exec(ctx, removeChatMemberExempt, arg.UserID, arg.ChatID)
	return err
}

const updateChatMemberTitle = `-- name: UpdateChatMemberTitle :exec
UPDATE chat_members
SET custom_title = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateChatMemberTitleParams struct {
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	ChatID      int64       `db:"chat_id" json:"chatId"`
	UserID      int64       `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatMemberTitle(ctx context.Context, arg UpdateChatMemberTitleParams) error {
	_, err := q.db.Exec(ctx, updateChatMemberTitle, arg.CustomTitle, arg.ChatID, arg.UserID)
	return err
}

const updateChatNorm = `-- name: UpdateChatNorm :exec
UPDATE chats
SET weekly_norm = $1
WHERE id = $2
`

type UpdateChatNormParams struct {
	WeeklyNorm int32 `db:"weekly_norm" json:"weeklyNorm"`
	ID         int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateChatNorm(ctx context.Context, arg UpdateChatNormParams) error {
	_, err := q.db.Exec(ctx, updateChatNorm, arg.WeeklyNorm, arg.ID)
	return err
}

const upsertChatMembers = `-- name: UpsertChatMembers :exec
INSERT INTO chat_members(chat_id, user_id, custom_title)
SELECT $1, UNNEST($2::BIGINT[]), UNNEST($3::TEXT[])
ON CONFLICT (chat_id, user_id) DO UPDATE SET
    custom_title = EXCLUDED.custom_title
`

type UpsertChatMembersParams struct {
	ChatID       int64    `db:"chat_id" json:"chatId"`
	UserIds      []int64  `db:"user_ids" json:"userIds"`
	CustomTitles []string `db:"custom_titles" json:"customTitles"`
}

func (q *Queries) UpsertChatMembers(ctx context.Context, arg UpsertChatMembersParams) error {
	_, err := q.db.Exec(ctx, upsertChatMembers, arg.ChatID, arg.UserIds, arg.CustomTitles)
	return err
}

const weeklyMessageReport = `-- name: WeeklyMessageReport :many
SELECT cm.user_id,
       u.username,
       u.first_name,
       u.last_name,
       COUNT(*)                    AS messages_count,
       c.weekly_norm,
       (COUNT(*) >= c.weekly_norm) AS norm_done
FROM chat_members cm
         JOIN chats c ON c.id = cm.chat_id
         JOIN users u ON u.id = cm.user_id
         LEFT JOIN messages m
                   ON m.chat_id = cm.chat_id
                       AND m.user_id = cm.user_id
                       AND m.created_at >= $1
                       AND m.created_at < $1 + interval '7 days'
WHERE cm.chat_id = $2
  AND (cm.exempt_until IS NULL OR cm.exempt_until < now())
GROUP BY cm.user_id, u.username, u.first_name, u.last_name, c.weekly_norm
ORDER BY messages_count DESC
`

type WeeklyMessageReportParams struct {
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ChatID    int64              `db:"chat_id" json:"chatId"`
}

type WeeklyMessageReportRow struct {
	UserID        int64       `db:"user_id" json:"userId"`
	Username      pgtype.Text `db:"username" json:"username"`
	FirstName     pgtype.Text `db:"first_name" json:"firstName"`
	LastName      pgtype.Text `db:"last_name" json:"lastName"`
	MessagesCount int64       `db:"messages_count" json:"messagesCount"`
	WeeklyNorm    int32       `db:"weekly_norm" json:"weeklyNorm"`
	NormDone      bool        `db:"norm_done" json:"normDone"`
}

func (q *Queries) WeeklyMessageReport(ctx context.Context, arg WeeklyMessageReportParams) ([]WeeklyMessageReportRow, error) {
	rows, err := q.db.Query(ctx, weeklyMessageReport, arg.CreatedAt, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyMessageReportRow{}
	for rows.Next() {
		var i WeeklyMessageReportRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.MessagesCount,
			&i.WeeklyNorm,
			&i.NormDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
