// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureChatExists = `-- name: EnsureChatExists :one
WITH ins AS (
    INSERT INTO chats (id, norm_warn, newbie_threshold_days)
        VALUES ($1, $2, $3)
        ON CONFLICT (id) DO NOTHING
        RETURNING id, norm_warn, newbie_threshold_days, ai_system_prompt, max_ladder, call_on_join, welcome_call_message, week_start_day, max_warns, norm_ban, command_prefix)
SELECT id, norm_warn, newbie_threshold_days, ai_system_prompt, max_ladder, call_on_join, welcome_call_message, week_start_day, max_warns, norm_ban, command_prefix
FROM ins
UNION ALL
SELECT id, norm_warn, newbie_threshold_days, ai_system_prompt, max_ladder, call_on_join, welcome_call_message, week_start_day, max_warns, norm_ban, command_prefix
FROM chats
WHERE id = $1
LIMIT 1
`

type EnsureChatExistsParams struct {
	ID                  int64 `db:"id" json:"id"`
	NormWarn            int32 `db:"norm_warn" json:"normWarn"`
	NewbieThresholdDays int32 `db:"newbie_threshold_days" json:"newbieThresholdDays"`
}

type EnsureChatExistsRow struct {
	ID                  int64       `db:"id" json:"id"`
	NormWarn            int32       `db:"norm_warn" json:"normWarn"`
	NewbieThresholdDays int32       `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	AiSystemPrompt      pgtype.Text `db:"ai_system_prompt" json:"aiSystemPrompt"`
	MaxLadder           int32       `db:"max_ladder" json:"maxLadder"`
	CallOnJoin          bool        `db:"call_on_join" json:"callOnJoin"`
	WelcomeCallMessage  pgtype.Text `db:"welcome_call_message" json:"welcomeCallMessage"`
	WeekStartDay        int16       `db:"week_start_day" json:"weekStartDay"`
	MaxWarns            int32       `db:"max_warns" json:"maxWarns"`
	NormBan             pgtype.Int4 `db:"norm_ban" json:"normBan"`
	CommandPrefix       pgtype.Text `db:"command_prefix" json:"commandPrefix"`
}

func (q *Queries) EnsureChatExists(ctx context.Context, arg EnsureChatExistsParams) (EnsureChatExistsRow, error) {
	row := q.db.QueryRow(ctx, ensureChatExists, arg.ID, arg.NormWarn, arg.NewbieThresholdDays)
	var i EnsureChatExistsRow
	err := row.Scan(
		&i.ID,
		&i.NormWarn,
		&i.NewbieThresholdDays,
		&i.AiSystemPrompt,
		&i.MaxLadder,
		&i.CallOnJoin,
		&i.WelcomeCallMessage,
		&i.WeekStartDay,
		&i.MaxWarns,
		&i.NormBan,
		&i.CommandPrefix,
	)
	return i, err
}

const getChat = `-- name: GetChat :one
SELECT id, norm_warn, newbie_threshold_days, ai_system_prompt, max_ladder, call_on_join, welcome_call_message, week_start_day, max_warns, norm_ban, command_prefix
FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.NormWarn,
		&i.NewbieThresholdDays,
		&i.AiSystemPrompt,
		&i.MaxLadder,
		&i.CallOnJoin,
		&i.WelcomeCallMessage,
		&i.WeekStartDay,
		&i.MaxWarns,
		&i.NormBan,
		&i.CommandPrefix,
	)
	return i, err
}

const getChatMaxLadder = `-- name: GetChatMaxLadder :one
SELECT max_ladder
FROM chats
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetChatMaxLadder(ctx context.Context, chatID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getChatMaxLadder, chatID)
	var max_ladder int32
	err := row.Scan(&max_ladder)
	return max_ladder, err
}

const getOrCreateChat = `-- name: GetOrCreateChat :one
INSERT INTO chats(id, norm_warn)
VALUES ($1, $2)
ON CONFLICT(id) DO UPDATE SET norm = chats.norm
RETURNING id, norm_warn, newbie_threshold_days, ai_system_prompt, max_ladder, call_on_join, welcome_call_message, week_start_day, max_warns, norm_ban, command_prefix
`

type GetOrCreateChatParams struct {
	ID       int64 `db:"id" json:"id"`
	NormWarn int32 `db:"norm_warn" json:"normWarn"`
}

func (q *Queries) GetOrCreateChat(ctx context.Context, arg GetOrCreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, getOrCreateChat, arg.ID, arg.NormWarn)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.NormWarn,
		&i.NewbieThresholdDays,
		&i.AiSystemPrompt,
		&i.MaxLadder,
		&i.CallOnJoin,
		&i.WelcomeCallMessage,
		&i.WeekStartDay,
		&i.MaxWarns,
		&i.NormBan,
		&i.CommandPrefix,
	)
	return i, err
}

const setChatAISystemPrompt = `-- name: SetChatAISystemPrompt :exec
UPDATE chats
SET ai_system_prompt = $1
WHERE id = $2
`

type SetChatAISystemPromptParams struct {
	AiSystemPrompt pgtype.Text `db:"ai_system_prompt" json:"aiSystemPrompt"`
	ChatID         int64       `db:"chat_id" json:"chatId"`
}

func (q *Queries) SetChatAISystemPrompt(ctx context.Context, arg SetChatAISystemPromptParams) error {
	_, err := q.db.Exec(ctx, setChatAISystemPrompt, arg.AiSystemPrompt, arg.ChatID)
	return err
}

const setChatMaxLadder = `-- name: SetChatMaxLadder :exec
UPDATE chats
SET max_ladder = $1
WHERE id = $2
`

type SetChatMaxLadderParams struct {
	MaxLadder int32 `db:"max_ladder" json:"maxLadder"`
	ChatID    int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) SetChatMaxLadder(ctx context.Context, arg SetChatMaxLadderParams) error {
	_, err := q.db.Exec(ctx, setChatMaxLadder, arg.MaxLadder, arg.ChatID)
	return err
}

const setChatWelcomeCallMessage = `-- name: SetChatWelcomeCallMessage :exec
UPDATE chats
SET welcome_call_message = $1
WHERE id = $2
`

type SetChatWelcomeCallMessageParams struct {
	WelcomeCallMessage pgtype.Text `db:"welcome_call_message" json:"welcomeCallMessage"`
	ChatID             int64       `db:"chat_id" json:"chatId"`
}

func (q *Queries) SetChatWelcomeCallMessage(ctx context.Context, arg SetChatWelcomeCallMessageParams) error {
	_, err := q.db.Exec(ctx, setChatWelcomeCallMessage, arg.WelcomeCallMessage, arg.ChatID)
	return err
}

const updateChatBanNorm = `-- name: UpdateChatBanNorm :exec
UPDATE chats
SET norm_ban = $1
WHERE id = $2
`

type UpdateChatBanNormParams struct {
	NormBan pgtype.Int4 `db:"norm_ban" json:"normBan"`
	ID      int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateChatBanNorm(ctx context.Context, arg UpdateChatBanNormParams) error {
	_, err := q.db.Exec(ctx, updateChatBanNorm, arg.NormBan, arg.ID)
	return err
}

const updateChatCallOnJoin = `-- name: UpdateChatCallOnJoin :exec
UPDATE chats
SET call_on_join = $1
WHERE id = $2
`

type UpdateChatCallOnJoinParams struct {
	CallOnJoin bool  `db:"call_on_join" json:"callOnJoin"`
	ChatID     int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) UpdateChatCallOnJoin(ctx context.Context, arg UpdateChatCallOnJoinParams) error {
	_, err := q.db.Exec(ctx, updateChatCallOnJoin, arg.CallOnJoin, arg.ChatID)
	return err
}

const updateChatCommandPrefix = `-- name: UpdateChatCommandPrefix :exec
UPDATE chats
SET command_prefix = $1
WHERE id = $2
`

type UpdateChatCommandPrefixParams struct {
	CommandPrefix pgtype.Text `db:"command_prefix" json:"commandPrefix"`
	ChatID        int64       `db:"chat_id" json:"chatId"`
}

func (q *Queries) UpdateChatCommandPrefix(ctx context.Context, arg UpdateChatCommandPrefixParams) error {
	_, err := q.db.Exec(ctx, updateChatCommandPrefix, arg.CommandPrefix, arg.ChatID)
	return err
}

const updateChatNewbieThreshold = `-- name: UpdateChatNewbieThreshold :exec
UPDATE chats
SET newbie_threshold_days = $1
WHERE id = $2
`

type UpdateChatNewbieThresholdParams struct {
	NewbieThresholdDays int32 `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	ID                  int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateChatNewbieThreshold(ctx context.Context, arg UpdateChatNewbieThresholdParams) error {
	_, err := q.db.Exec(ctx, updateChatNewbieThreshold, arg.NewbieThresholdDays, arg.ID)
	return err
}

const updateChatWarnNorm = `-- name: UpdateChatWarnNorm :exec
UPDATE chats
SET norm_warn = $1
WHERE id = $2
`

type UpdateChatWarnNormParams struct {
	NormWarn int32 `db:"norm_warn" json:"normWarn"`
	ID       int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateChatWarnNorm(ctx context.Context, arg UpdateChatWarnNormParams) error {
	_, err := q.db.Exec(ctx, updateChatWarnNorm, arg.NormWarn, arg.ID)
	return err
}

const updateChatWeekStartDay = `-- name: UpdateChatWeekStartDay :exec
UPDATE chats
SET week_start_day = $1
WHERE id = $2
`

type UpdateChatWeekStartDayParams struct {
	WeekStartDay int16 `db:"week_start_day" json:"weekStartDay"`
	ChatID       int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) UpdateChatWeekStartDay(ctx context.Context, arg UpdateChatWeekStartDayParams) error {
	_, err := q.db.Exec(ctx, updateChatWeekStartDay, arg.WeekStartDay, arg.ChatID)
	return err
}
