// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: developer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllDevelopers = `-- name: GetAllDevelopers :many
SELECT bd.user_id, bd.role, u.username, u.first_name, u.last_name
FROM bot_developers bd
JOIN users u ON bd.user_id = u.id
ORDER BY bd.user_id
`

type GetAllDevelopersRow struct {
	UserID    int64       `db:"user_id" json:"userId"`
	Role      string      `db:"role" json:"role"`
	Username  pgtype.Text `db:"username" json:"username"`
	FirstName pgtype.Text `db:"first_name" json:"firstName"`
	LastName  pgtype.Text `db:"last_name" json:"lastName"`
}

func (q *Queries) GetAllDevelopers(ctx context.Context) ([]GetAllDevelopersRow, error) {
	rows, err := q.db.Query(ctx, getAllDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllDevelopersRow{}
	for rows.Next() {
		var i GetAllDevelopersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeveloper = `-- name: GetDeveloper :one
SELECT user_id, role FROM bot_developers WHERE user_id = $1
`

func (q *Queries) GetDeveloper(ctx context.Context, userID int64) (BotDeveloper, error) {
	row := q.db.QueryRow(ctx, getDeveloper, userID)
	var i BotDeveloper
	err := row.Scan(&i.UserID, &i.Role)
	return i, err
}

const getDevelopersCount = `-- name: GetDevelopersCount :one
SELECT COUNT(*) FROM bot_developers
`

func (q *Queries) GetDevelopersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDevelopersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isDeveloper = `-- name: IsDeveloper :one
SELECT EXISTS(SELECT 1 FROM bot_developers WHERE user_id = $1)
`

func (q *Queries) IsDeveloper(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isDeveloper, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeDeveloper = `-- name: RemoveDeveloper :exec
DELETE FROM bot_developers WHERE user_id = $1
`

func (q *Queries) RemoveDeveloper(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, removeDeveloper, userID)
	return err
}

const setDeveloper = `-- name: SetDeveloper :exec
INSERT INTO bot_developers (user_id, role)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET role = EXCLUDED.role
`

type SetDeveloperParams struct {
	UserID int64  `db:"user_id" json:"userId"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) SetDeveloper(ctx context.Context, arg SetDeveloperParams) error {
	_, err := q.db.Exec(ctx, setDeveloper, arg.UserID, arg.Role)
	return err
}
