// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: developer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureDeveloperUser = `-- name: EnsureDeveloperUser :one
INSERT INTO users (id, first_name, last_name)
VALUES ($1, 'Developer', '')
ON CONFLICT (id) DO UPDATE SET first_name = EXCLUDED.first_name
RETURNING id, username, first_name, last_name, created_at, gender
`

func (q *Queries) EnsureDeveloperUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, ensureDeveloperUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Gender,
	)
	return i, err
}

const getAllDevelopers = `-- name: GetAllDevelopers :many
SELECT bd.user_id, bd.level, bd.chat_id, u.username, u.first_name, u.last_name
FROM bot_developers bd
JOIN users u ON bd.user_id = u.id
WHERE bd.chat_id = $1
ORDER BY bd.user_id
`

type GetAllDevelopersRow struct {
	UserID    int64       `db:"user_id" json:"userId"`
	Level     int16       `db:"level" json:"level"`
	ChatID    int64       `db:"chat_id" json:"chatId"`
	Username  pgtype.Text `db:"username" json:"username"`
	FirstName pgtype.Text `db:"first_name" json:"firstName"`
	LastName  pgtype.Text `db:"last_name" json:"lastName"`
}

func (q *Queries) GetAllDevelopers(ctx context.Context, chatID int64) ([]GetAllDevelopersRow, error) {
	rows, err := q.db.Query(ctx, getAllDevelopers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllDevelopersRow{}
	for rows.Next() {
		var i GetAllDevelopersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Level,
			&i.ChatID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeveloper = `-- name: GetDeveloper :one
SELECT user_id, level, chat_id FROM bot_developers WHERE user_id = $1 AND chat_id = $2
`

type GetDeveloperParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) GetDeveloper(ctx context.Context, arg GetDeveloperParams) (BotDeveloper, error) {
	row := q.db.QueryRow(ctx, getDeveloper, arg.UserID, arg.ChatID)
	var i BotDeveloper
	err := row.Scan(&i.UserID, &i.Level, &i.ChatID)
	return i, err
}

const getDevelopersCount = `-- name: GetDevelopersCount :one
SELECT COUNT(*) FROM bot_developers WHERE chat_id = $1
`

func (q *Queries) GetDevelopersCount(ctx context.Context, chatID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDevelopersCount, chatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isDeveloper = `-- name: IsDeveloper :one
SELECT EXISTS(SELECT 1 FROM bot_developers WHERE user_id = $1 AND chat_id = $2)
`

type IsDeveloperParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) IsDeveloper(ctx context.Context, arg IsDeveloperParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDeveloper, arg.UserID, arg.ChatID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeDeveloper = `-- name: RemoveDeveloper :exec
DELETE FROM bot_developers WHERE user_id = $1 AND chat_id = $2
`

type RemoveDeveloperParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) RemoveDeveloper(ctx context.Context, arg RemoveDeveloperParams) error {
	_, err := q.db.Exec(ctx, removeDeveloper, arg.UserID, arg.ChatID)
	return err
}

const setDeveloper = `-- name: SetDeveloper :exec
INSERT INTO bot_developers (user_id, chat_id, level)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, chat_id) DO UPDATE SET level = EXCLUDED.level
`

type SetDeveloperParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
	Level  int16 `db:"level" json:"level"`
}

func (q *Queries) SetDeveloper(ctx context.Context, arg SetDeveloperParams) error {
	_, err := q.db.Exec(ctx, setDeveloper, arg.UserID, arg.ChatID, arg.Level)
	return err
}
