// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exempt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExemptRequest = `-- name: AddExemptRequest :exec
INSERT INTO exempt_requests(chat_id, user_id, exempt_until, message_id)
VALUES ($1, $2, $3, $4)
`

type AddExemptRequestParams struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	MessageID   int64              `db:"message_id" json:"messageId"`
}

func (q *Queries) AddExemptRequest(ctx context.Context, arg AddExemptRequestParams) error {
	_, err := q.db.Exec(ctx, addExemptRequest,
		arg.ChatID,
		arg.UserID,
		arg.ExemptUntil,
		arg.MessageID,
	)
	return err
}

const approveExemptRequest = `-- name: ApproveExemptRequest :exec
UPDATE exempt_requests
SET status = 'approved'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type ApproveExemptRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) ApproveExemptRequest(ctx context.Context, arg ApproveExemptRequestParams) error {
	_, err := q.db.Exec(ctx, approveExemptRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const chatExemptUsers = `-- name: ChatExemptUsers :many
SELECT cm.user_id,
       u.username,
       u.first_name,
       u.last_name,
       cm.exempt_until
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.exempt_until IS NOT NULL
  AND cm.exempt_until >= now()
ORDER BY cm.exempt_until
`

type ChatExemptUsersRow struct {
	UserID      int64              `db:"user_id" json:"userId"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
}

func (q *Queries) ChatExemptUsers(ctx context.Context, chatID int64) ([]ChatExemptUsersRow, error) {
	rows, err := q.db.Query(ctx, chatExemptUsers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatExemptUsersRow{}
	for rows.Next() {
		var i ChatExemptUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.ExemptUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exemptChatMember = `-- name: ExemptChatMember :exec
UPDATE chat_members
SET exempt_until = $1
WHERE chat_id = $2
  AND user_id = $3
`

type ExemptChatMemberParams struct {
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
}

func (q *Queries) ExemptChatMember(ctx context.Context, arg ExemptChatMemberParams) error {
	_, err := q.db.Exec(ctx, exemptChatMember, arg.ExemptUntil, arg.ChatID, arg.UserID)
	return err
}

const getExemptRequest = `-- name: GetExemptRequest :one
SELECT chat_id, user_id, requested_at, exempt_until, status, message_id
FROM exempt_requests
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type GetExemptRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) GetExemptRequest(ctx context.Context, arg GetExemptRequestParams) (ExemptRequest, error) {
	row := q.db.QueryRow(ctx, getExemptRequest, arg.ChatID, arg.UserID, arg.MessageID)
	var i ExemptRequest
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.RequestedAt,
		&i.ExemptUntil,
		&i.Status,
		&i.MessageID,
	)
	return i, err
}

const rejectExemptRequest = `-- name: RejectExemptRequest :exec
UPDATE exempt_requests
SET status = 'rejected'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type RejectExemptRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) RejectExemptRequest(ctx context.Context, arg RejectExemptRequestParams) error {
	_, err := q.db.Exec(ctx, rejectExemptRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const removeChatMemberExempt = `-- name: RemoveChatMemberExempt :exec
UPDATE chat_members
SET exempt_until = null
WHERE user_id = $1
  AND chat_id = $2
`

type RemoveChatMemberExemptParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) RemoveChatMemberExempt(ctx context.Context, arg RemoveChatMemberExemptParams) error {
	_, err := q.db.Exec(ctx, removeChatMemberExempt, arg.UserID, arg.ChatID)
	return err
}
