// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exempt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExemptRequest = `-- name: AddExemptRequest :exec
INSERT INTO exempt_requests(chat_id, user_id, exempt_until, message_id)
VALUES ($1, $2, $3, $4)
`

type AddExemptRequestParams struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	MessageID   int64              `db:"message_id" json:"messageId"`
}

func (q *Queries) AddExemptRequest(ctx context.Context, arg AddExemptRequestParams) error {
	_, err := q.db.Exec(ctx, addExemptRequest,
		arg.ChatID,
		arg.UserID,
		arg.ExemptUntil,
		arg.MessageID,
	)
	return err
}

const approveExemptRequest = `-- name: ApproveExemptRequest :exec
UPDATE exempt_requests
SET status = 'approved'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type ApproveExemptRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) ApproveExemptRequest(ctx context.Context, arg ApproveExemptRequestParams) error {
	_, err := q.db.Exec(ctx, approveExemptRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const getExemptRequest = `-- name: GetExemptRequest :one
SELECT chat_id, user_id, requested_at, exempt_until, status, message_id
FROM exempt_requests
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type GetExemptRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) GetExemptRequest(ctx context.Context, arg GetExemptRequestParams) (ExemptRequest, error) {
	row := q.db.QueryRow(ctx, getExemptRequest, arg.ChatID, arg.UserID, arg.MessageID)
	var i ExemptRequest
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.RequestedAt,
		&i.ExemptUntil,
		&i.Status,
		&i.MessageID,
	)
	return i, err
}

const rejectExemptRequest = `-- name: RejectExemptRequest :exec
UPDATE exempt_requests
SET status = 'rejected'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type RejectExemptRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) RejectExemptRequest(ctx context.Context, arg RejectExemptRequestParams) error {
	_, err := q.db.Exec(ctx, rejectExemptRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}
