// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: marriage.sql

package db

import (
	"context"
)

const createMarriage = `-- name: CreateMarriage :one
INSERT INTO marriages (chat_id,
                       user1_id,
                       user2_id)
VALUES ($1, $2, $3)
RETURNING id, chat_id, user1_id, user2_id, married_at, divorced_at
`

type CreateMarriageParams struct {
	ChatID  int64 `db:"chat_id" json:"chatId"`
	User1ID int64 `db:"user1_id" json:"user1Id"`
	User2ID int64 `db:"user2_id" json:"user2Id"`
}

func (q *Queries) CreateMarriage(ctx context.Context, arg CreateMarriageParams) (Marriage, error) {
	row := q.db.QueryRow(ctx, createMarriage, arg.ChatID, arg.User1ID, arg.User2ID)
	var i Marriage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.User1ID,
		&i.User2ID,
		&i.MarriedAt,
		&i.DivorcedAt,
	)
	return i, err
}

const createMarriageRequest = `-- name: CreateMarriageRequest :one
INSERT INTO marriage_requests (chat_id,
                               from_user_id,
                               to_user_id,
                               status,
                               created_at)
VALUES ($1, $2, $3, 'pending', now())
RETURNING id, chat_id, from_user_id, to_user_id, status, created_at, responded_at
`

type CreateMarriageRequestParams struct {
	ChatID     int64 `db:"chat_id" json:"chatId"`
	FromUserID int64 `db:"from_user_id" json:"fromUserId"`
	ToUserID   int64 `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) CreateMarriageRequest(ctx context.Context, arg CreateMarriageRequestParams) (MarriageRequest, error) {
	row := q.db.QueryRow(ctx, createMarriageRequest, arg.ChatID, arg.FromUserID, arg.ToUserID)
	var i MarriageRequest
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const divorceMarriage = `-- name: DivorceMarriage :exec
UPDATE marriages
SET divorced_at = now()
WHERE id = $1
  AND chat_id = $2
  AND divorced_at IS NULL
`

type DivorceMarriageParams struct {
	ID     int64 `db:"id" json:"id"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) DivorceMarriage(ctx context.Context, arg DivorceMarriageParams) error {
	_, err := q.db.Exec(ctx, divorceMarriage, arg.ID, arg.ChatID)
	return err
}

const getActiveMarriage = `-- name: GetActiveMarriage :one
SELECT m.id, m.chat_id, m.user1_id, m.user2_id, m.married_at, m.divorced_at, cm1.chat_id, cm1.user_id, cm1.joined_at, cm1.rest_until, cm1.tag, cm1.left_at, cm1.rest_reason, cm1.emoji, cm1.status, cm1.emoji_json, cm1.exclude_from_call, u1.id, u1.username, u1.first_name, u1.last_name, u1.created_at, u1.gender, u1.emoji, u1.custom_emoji_id, u1.emoji_json, u1.is_bot, cm2.chat_id, cm2.user_id, cm2.joined_at, cm2.rest_until, cm2.tag, cm2.left_at, cm2.rest_reason, cm2.emoji, cm2.status, cm2.emoji_json, cm2.exclude_from_call, u2.id, u2.username, u2.first_name, u2.last_name, u2.created_at, u2.gender, u2.emoji, u2.custom_emoji_id, u2.emoji_json, u2.is_bot
FROM marriages m
         JOIN chat_members cm1 ON cm1.chat_id = m.chat_id AND cm1.user_id = m.user1_id
         JOIN users u1 ON u1.id = cm1.user_id
         JOIN chat_members cm2 ON cm2.chat_id = m.chat_id AND cm2.user_id = m.user2_id
         JOIN users u2 ON u2.id = cm2.user_id
WHERE m.chat_id = $1
  AND m.divorced_at IS NULL
  AND (m.user1_id = $2 OR m.user2_id = $2)
LIMIT 1
`

type GetActiveMarriageParams struct {
	ChatID  int64 `db:"chat_id" json:"chatId"`
	User1ID int64 `db:"user1_id" json:"user1Id"`
}

type GetActiveMarriageRow struct {
	Marriage     Marriage   `db:"marriage" json:"marriage"`
	ChatMember   ChatMember `db:"chat_member" json:"chatMember"`
	User         User       `db:"user" json:"user"`
	ChatMember_2 ChatMember `db:"chat_member_2" json:"chatMember2"`
	User_2       User       `db:"user_2" json:"user2"`
}

func (q *Queries) GetActiveMarriage(ctx context.Context, arg GetActiveMarriageParams) (GetActiveMarriageRow, error) {
	row := q.db.QueryRow(ctx, getActiveMarriage, arg.ChatID, arg.User1ID)
	var i GetActiveMarriageRow
	err := row.Scan(
		&i.Marriage.ID,
		&i.Marriage.ChatID,
		&i.Marriage.User1ID,
		&i.Marriage.User2ID,
		&i.Marriage.MarriedAt,
		&i.Marriage.DivorcedAt,
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.ChatMember.ExcludeFromCall,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
		&i.User.IsBot,
		&i.ChatMember_2.ChatID,
		&i.ChatMember_2.UserID,
		&i.ChatMember_2.JoinedAt,
		&i.ChatMember_2.RestUntil,
		&i.ChatMember_2.Tag,
		&i.ChatMember_2.LeftAt,
		&i.ChatMember_2.RestReason,
		&i.ChatMember_2.Emoji,
		&i.ChatMember_2.Status,
		&i.ChatMember_2.EmojiJson,
		&i.ChatMember_2.ExcludeFromCall,
		&i.User_2.ID,
		&i.User_2.Username,
		&i.User_2.FirstName,
		&i.User_2.LastName,
		&i.User_2.CreatedAt,
		&i.User_2.Gender,
		&i.User_2.Emoji,
		&i.User_2.CustomEmojiID,
		&i.User_2.EmojiJson,
		&i.User_2.IsBot,
	)
	return i, err
}

const getActiveMarriageRequest = `-- name: GetActiveMarriageRequest :one
SELECT id, chat_id, from_user_id, to_user_id, status, created_at, responded_at
FROM marriage_requests
WHERE chat_id = $1
  AND from_user_id = $2
  AND to_user_id = $3
  AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveMarriageRequestParams struct {
	ChatID     int64 `db:"chat_id" json:"chatId"`
	FromUserID int64 `db:"from_user_id" json:"fromUserId"`
	ToUserID   int64 `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) GetActiveMarriageRequest(ctx context.Context, arg GetActiveMarriageRequestParams) (MarriageRequest, error) {
	row := q.db.QueryRow(ctx, getActiveMarriageRequest, arg.ChatID, arg.FromUserID, arg.ToUserID)
	var i MarriageRequest
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getIncomingMarriageRequests = `-- name: GetIncomingMarriageRequests :many
SELECT id, chat_id, from_user_id, to_user_id, status, created_at, responded_at
FROM marriage_requests
WHERE chat_id = $1
  AND to_user_id = $2
  AND status = 'pending'
ORDER BY created_at DESC
`

type GetIncomingMarriageRequestsParams struct {
	ChatID   int64 `db:"chat_id" json:"chatId"`
	ToUserID int64 `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) GetIncomingMarriageRequests(ctx context.Context, arg GetIncomingMarriageRequestsParams) ([]MarriageRequest, error) {
	rows, err := q.db.Query(ctx, getIncomingMarriageRequests, arg.ChatID, arg.ToUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarriageRequest{}
	for rows.Next() {
		var i MarriageRequest
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarriageBetweenUsers = `-- name: GetMarriageBetweenUsers :one
SELECT m.id, m.chat_id, m.user1_id, m.user2_id, m.married_at, m.divorced_at, cm1.chat_id, cm1.user_id, cm1.joined_at, cm1.rest_until, cm1.tag, cm1.left_at, cm1.rest_reason, cm1.emoji, cm1.status, cm1.emoji_json, cm1.exclude_from_call, u1.id, u1.username, u1.first_name, u1.last_name, u1.created_at, u1.gender, u1.emoji, u1.custom_emoji_id, u1.emoji_json, u1.is_bot, cm2.chat_id, cm2.user_id, cm2.joined_at, cm2.rest_until, cm2.tag, cm2.left_at, cm2.rest_reason, cm2.emoji, cm2.status, cm2.emoji_json, cm2.exclude_from_call, u2.id, u2.username, u2.first_name, u2.last_name, u2.created_at, u2.gender, u2.emoji, u2.custom_emoji_id, u2.emoji_json, u2.is_bot
FROM marriages m
         JOIN chat_members cm1 ON cm1.chat_id = m.chat_id AND cm1.user_id = m.user1_id
         JOIN users u1 ON u1.id = cm1.user_id
         JOIN chat_members cm2 ON cm2.chat_id = m.chat_id AND cm2.user_id = m.user2_id
         JOIN users u2 ON u2.id = cm2.user_id
WHERE m.chat_id = $1
  AND m.user1_id = LEAST($2, $3)
  AND m.user2_id = GREATEST($2, $3)
  AND m.divorced_at IS NULL
`

type GetMarriageBetweenUsersParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	User1ID   int64 `db:"user1_id" json:"user1Id"`
	User1ID_2 int64 `db:"user1_id_2" json:"user1Id2"`
}

type GetMarriageBetweenUsersRow struct {
	Marriage     Marriage   `db:"marriage" json:"marriage"`
	ChatMember   ChatMember `db:"chat_member" json:"chatMember"`
	User         User       `db:"user" json:"user"`
	ChatMember_2 ChatMember `db:"chat_member_2" json:"chatMember2"`
	User_2       User       `db:"user_2" json:"user2"`
}

func (q *Queries) GetMarriageBetweenUsers(ctx context.Context, arg GetMarriageBetweenUsersParams) (GetMarriageBetweenUsersRow, error) {
	row := q.db.QueryRow(ctx, getMarriageBetweenUsers, arg.ChatID, arg.User1ID, arg.User1ID_2)
	var i GetMarriageBetweenUsersRow
	err := row.Scan(
		&i.Marriage.ID,
		&i.Marriage.ChatID,
		&i.Marriage.User1ID,
		&i.Marriage.User2ID,
		&i.Marriage.MarriedAt,
		&i.Marriage.DivorcedAt,
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.ChatMember.ExcludeFromCall,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
		&i.User.IsBot,
		&i.ChatMember_2.ChatID,
		&i.ChatMember_2.UserID,
		&i.ChatMember_2.JoinedAt,
		&i.ChatMember_2.RestUntil,
		&i.ChatMember_2.Tag,
		&i.ChatMember_2.LeftAt,
		&i.ChatMember_2.RestReason,
		&i.ChatMember_2.Emoji,
		&i.ChatMember_2.Status,
		&i.ChatMember_2.EmojiJson,
		&i.ChatMember_2.ExcludeFromCall,
		&i.User_2.ID,
		&i.User_2.Username,
		&i.User_2.FirstName,
		&i.User_2.LastName,
		&i.User_2.CreatedAt,
		&i.User_2.Gender,
		&i.User_2.Emoji,
		&i.User_2.CustomEmojiID,
		&i.User_2.EmojiJson,
		&i.User_2.IsBot,
	)
	return i, err
}

const listActiveMarriages = `-- name: ListActiveMarriages :many
SELECT m.id, m.chat_id, m.user1_id, m.user2_id, m.married_at, m.divorced_at, cm1.chat_id, cm1.user_id, cm1.joined_at, cm1.rest_until, cm1.tag, cm1.left_at, cm1.rest_reason, cm1.emoji, cm1.status, cm1.emoji_json, cm1.exclude_from_call, u1.id, u1.username, u1.first_name, u1.last_name, u1.created_at, u1.gender, u1.emoji, u1.custom_emoji_id, u1.emoji_json, u1.is_bot, cm2.chat_id, cm2.user_id, cm2.joined_at, cm2.rest_until, cm2.tag, cm2.left_at, cm2.rest_reason, cm2.emoji, cm2.status, cm2.emoji_json, cm2.exclude_from_call, u2.id, u2.username, u2.first_name, u2.last_name, u2.created_at, u2.gender, u2.emoji, u2.custom_emoji_id, u2.emoji_json, u2.is_bot
FROM marriages m
         JOIN chat_members cm1 ON cm1.chat_id = m.chat_id AND cm1.user_id = m.user1_id
         JOIN users u1 ON u1.id = cm1.user_id
         JOIN chat_members cm2 ON cm2.chat_id = m.chat_id AND cm2.user_id = m.user2_id
         JOIN users u2 ON u2.id = cm2.user_id
WHERE m.chat_id = $1
  AND m.divorced_at IS NULL
ORDER BY m.married_at DESC
`

type ListActiveMarriagesRow struct {
	Marriage     Marriage   `db:"marriage" json:"marriage"`
	ChatMember   ChatMember `db:"chat_member" json:"chatMember"`
	User         User       `db:"user" json:"user"`
	ChatMember_2 ChatMember `db:"chat_member_2" json:"chatMember2"`
	User_2       User       `db:"user_2" json:"user2"`
}

func (q *Queries) ListActiveMarriages(ctx context.Context, chatID int64) ([]ListActiveMarriagesRow, error) {
	rows, err := q.db.Query(ctx, listActiveMarriages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMarriagesRow{}
	for rows.Next() {
		var i ListActiveMarriagesRow
		if err := rows.Scan(
			&i.Marriage.ID,
			&i.Marriage.ChatID,
			&i.Marriage.User1ID,
			&i.Marriage.User2ID,
			&i.Marriage.MarriedAt,
			&i.Marriage.DivorcedAt,
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.User.IsBot,
			&i.ChatMember_2.ChatID,
			&i.ChatMember_2.UserID,
			&i.ChatMember_2.JoinedAt,
			&i.ChatMember_2.RestUntil,
			&i.ChatMember_2.Tag,
			&i.ChatMember_2.LeftAt,
			&i.ChatMember_2.RestReason,
			&i.ChatMember_2.Emoji,
			&i.ChatMember_2.Status,
			&i.ChatMember_2.EmojiJson,
			&i.ChatMember_2.ExcludeFromCall,
			&i.User_2.ID,
			&i.User_2.Username,
			&i.User_2.FirstName,
			&i.User_2.LastName,
			&i.User_2.CreatedAt,
			&i.User_2.Gender,
			&i.User_2.Emoji,
			&i.User_2.CustomEmojiID,
			&i.User_2.EmojiJson,
			&i.User_2.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarriageRequestStatus = `-- name: UpdateMarriageRequestStatus :exec
UPDATE marriage_requests
SET status       = $3,
    responded_at = now()
WHERE id = $1
  AND chat_id = $2
`

type UpdateMarriageRequestStatusParams struct {
	ID     int64                 `db:"id" json:"id"`
	ChatID int64                 `db:"chat_id" json:"chatId"`
	Status MarriageRequestStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateMarriageRequestStatus(ctx context.Context, arg UpdateMarriageRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateMarriageRequestStatus, arg.ID, arg.ChatID, arg.Status)
	return err
}
