// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChatMember = `-- name: DeleteChatMember :exec
UPDATE chat_members
SET left_at = now()
WHERE chat_id = $1
  AND user_id = $2
  AND left_at IS NULL
`

type DeleteChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteChatMember(ctx context.Context, arg DeleteChatMemberParams) error {
	_, err := q.db.Exec(ctx, deleteChatMember, arg.ChatID, arg.UserID)
	return err
}

const ensureChatMemberExists = `-- name: EnsureChatMemberExists :one
INSERT INTO chat_members(chat_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT(chat_id, user_id) DO UPDATE SET status  = EXCLUDED.status,
                                            left_at = NULL
RETURNING chat_id, user_id, joined_at, rest_until, custom_title, status, left_at, rest_reason, level
`

type EnsureChatMemberExistsParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	UserID int64  `db:"user_id" json:"userId"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) EnsureChatMemberExists(ctx context.Context, arg EnsureChatMemberExistsParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, ensureChatMemberExists, arg.ChatID, arg.UserID, arg.Status)
	var i ChatMember
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.RestUntil,
		&i.CustomTitle,
		&i.Status,
		&i.LeftAt,
		&i.RestReason,
		&i.Level,
	)
	return i, err
}

const ensureMemberFull = `-- name: EnsureMemberFull :one
WITH chat_upsert AS (
    INSERT INTO chats (id, norm_warn)
        VALUES ($3, $4)
        ON CONFLICT (id) DO UPDATE
            SET norm_warn = chats.norm_warn
        RETURNING id),
     user_upsert AS (
         INSERT INTO users (id, username, first_name, last_name)
             VALUES ($5, $6, $7, $8)
             ON CONFLICT (id) DO UPDATE
                 SET username = EXCLUDED.username,
                     first_name = EXCLUDED.first_name,
                     last_name = EXCLUDED.last_name
             RETURNING id)
INSERT INTO chat_members (chat_id, user_id, custom_title, level)
SELECT chat_upsert.id,
       user_upsert.id,
       $1,
       $2
FROM chat_upsert,
     user_upsert
ON CONFLICT (chat_id, user_id) DO UPDATE
    SET custom_title = CASE
                           WHEN $1 IS NOT NULL AND $1 <> ''
                               THEN $1
                           ELSE chat_members.custom_title
        END,
        level = CASE
                    WHEN $2 > 0 THEN $2
                    ELSE chat_members.level
        END,
        left_at = NULL
RETURNING chat_id, user_id, joined_at, rest_until, custom_title, status, left_at, rest_reason, level
`

type EnsureMemberFullParams struct {
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	Level       int16       `db:"level" json:"level"`
	ChatID      int64       `db:"chat_id" json:"chatId"`
	NormWarn    int32       `db:"norm_warn" json:"normWarn"`
	UserID      int64       `db:"user_id" json:"userId"`
	Username    pgtype.Text `db:"username" json:"username"`
	FirstName   pgtype.Text `db:"first_name" json:"firstName"`
	LastName    pgtype.Text `db:"last_name" json:"lastName"`
}

func (q *Queries) EnsureMemberFull(ctx context.Context, arg EnsureMemberFullParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, ensureMemberFull,
		arg.CustomTitle,
		arg.Level,
		arg.ChatID,
		arg.NormWarn,
		arg.UserID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	var i ChatMember
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.RestUntil,
		&i.CustomTitle,
		&i.Status,
		&i.LeftAt,
		&i.RestReason,
		&i.Level,
	)
	return i, err
}

const getAnyChatMembersWithTitles = `-- name: GetAnyChatMembersWithTitles :many
SELECT cm.user_id, cm.custom_title, cm.status, u.first_name, u.last_name, u.username, cm.level
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
WHERE cm.chat_id = $1
  AND cm.custom_title IS NOT NULL
  AND cm.custom_title <> ''
  AND cm.left_at IS NULL
`

type GetAnyChatMembersWithTitlesRow struct {
	UserID      int64       `db:"user_id" json:"userId"`
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	Status      string      `db:"status" json:"status"`
	FirstName   pgtype.Text `db:"first_name" json:"firstName"`
	LastName    pgtype.Text `db:"last_name" json:"lastName"`
	Username    pgtype.Text `db:"username" json:"username"`
	Level       int16       `db:"level" json:"level"`
}

func (q *Queries) GetAnyChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetAnyChatMembersWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, getAnyChatMembersWithTitles, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnyChatMembersWithTitlesRow{}
	for rows.Next() {
		var i GetAnyChatMembersWithTitlesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CustomTitle,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatCommandLevels = `-- name: GetChatCommandLevels :many
SELECT command_id, level
FROM chat_command_levels
WHERE chat_id = $1
`

type GetChatCommandLevelsRow struct {
	CommandID string `db:"command_id" json:"commandId"`
	Level     int16  `db:"level" json:"level"`
}

func (q *Queries) GetChatCommandLevels(ctx context.Context, chatID int64) ([]GetChatCommandLevelsRow, error) {
	rows, err := q.db.Query(ctx, getChatCommandLevels, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatCommandLevelsRow{}
	for rows.Next() {
		var i GetChatCommandLevelsRow
		if err := rows.Scan(&i.CommandID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_id, user_id, joined_at, rest_until, custom_title, status, left_at, rest_reason, level, id, username, first_name, last_name, created_at, gender
FROM chat_members
         JOIN users ON users.id = user_id
WHERE left_at IS NULL
  AND chat_id = $1
  AND user_id = $2
`

type GetChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type GetChatMemberRow struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	CustomTitle pgtype.Text        `db:"custom_title" json:"customTitle"`
	Status      string             `db:"status" json:"status"`
	LeftAt      pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	RestReason  pgtype.Text        `db:"rest_reason" json:"restReason"`
	Level       int16              `db:"level" json:"level"`
	ID          int64              `db:"id" json:"id"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	Gender      string             `db:"gender" json:"gender"`
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (GetChatMemberRow, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChatID, arg.UserID)
	var i GetChatMemberRow
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.RestUntil,
		&i.CustomTitle,
		&i.Status,
		&i.LeftAt,
		&i.RestReason,
		&i.Level,
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Gender,
	)
	return i, err
}

const getChatMembers = `-- name: GetChatMembers :many
SELECT chat_id, user_id, joined_at, rest_until, custom_title, status, left_at, rest_reason, level, id, username, first_name, last_name, created_at, gender
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.left_at IS NULL
`

type GetChatMembersRow struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	CustomTitle pgtype.Text        `db:"custom_title" json:"customTitle"`
	Status      string             `db:"status" json:"status"`
	LeftAt      pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	RestReason  pgtype.Text        `db:"rest_reason" json:"restReason"`
	Level       int16              `db:"level" json:"level"`
	ID          int64              `db:"id" json:"id"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	Gender      string             `db:"gender" json:"gender"`
}

func (q *Queries) GetChatMembers(ctx context.Context, chatID int64) ([]GetChatMembersRow, error) {
	rows, err := q.db.Query(ctx, getChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersRow{}
	for rows.Next() {
		var i GetChatMembersRow
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.JoinedAt,
			&i.RestUntil,
			&i.CustomTitle,
			&i.Status,
			&i.LeftAt,
			&i.RestReason,
			&i.Level,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMembersWithTitles = `-- name: GetChatMembersWithTitles :many
SELECT cm.user_id, cm.custom_title, cm.status, u.first_name, u.last_name, u.username, cm.level
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
WHERE cm.chat_id = $1
  AND cm.left_at IS NULL
  AND cm.custom_title IS NOT NULL
  AND cm.custom_title <> ''
`

type GetChatMembersWithTitlesRow struct {
	UserID      int64       `db:"user_id" json:"userId"`
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	Status      string      `db:"status" json:"status"`
	FirstName   pgtype.Text `db:"first_name" json:"firstName"`
	LastName    pgtype.Text `db:"last_name" json:"lastName"`
	Username    pgtype.Text `db:"username" json:"username"`
	Level       int16       `db:"level" json:"level"`
}

func (q *Queries) GetChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetChatMembersWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, getChatMembersWithTitles, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersWithTitlesRow{}
	for rows.Next() {
		var i GetChatMembersWithTitlesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CustomTitle,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberCustomTitle = `-- name: GetMemberCustomTitle :one
SELECT custom_title
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type GetMemberCustomTitleParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetMemberCustomTitle(ctx context.Context, arg GetMemberCustomTitleParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getMemberCustomTitle, arg.ChatID, arg.UserID)
	var custom_title pgtype.Text
	err := row.Scan(&custom_title)
	return custom_title, err
}

const markChatMembersLeftNotInList = `-- name: MarkChatMembersLeftNotInList :exec
UPDATE chat_members
SET left_at = now()
WHERE chat_id = $1
  AND left_at IS NULL
  AND user_id <> ALL ($2::BIGINT[])
`

type MarkChatMembersLeftNotInListParams struct {
	ChatID  int64   `db:"chat_id" json:"chatId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) MarkChatMembersLeftNotInList(ctx context.Context, arg MarkChatMembersLeftNotInListParams) error {
	_, err := q.db.Exec(ctx, markChatMembersLeftNotInList, arg.ChatID, arg.UserIds)
	return err
}

const moveChatMembersToNew = `-- name: MoveChatMembersToNew :exec
UPDATE chat_members cm
SET joined_at = now()
FROM chats c
WHERE c.id = cm.chat_id
  AND cm.chat_id = $1
  AND cm.user_id = ANY ($2::BIGINT[])
`

type MoveChatMembersToNewParams struct {
	ChatID  int64   `db:"chat_id" json:"chatId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) MoveChatMembersToNew(ctx context.Context, arg MoveChatMembersToNewParams) error {
	_, err := q.db.Exec(ctx, moveChatMembersToNew, arg.ChatID, arg.UserIds)
	return err
}

const moveChatMembersToOldExcept = `-- name: MoveChatMembersToOldExcept :exec
UPDATE chat_members cm
SET joined_at = joined_at - ((c.newbie_threshold_days + 1) || ' days')::interval
FROM chats c
WHERE c.id = cm.chat_id
  AND cm.chat_id = $1
  AND cm.user_id <> ALL ($2::BIGINT[])
`

type MoveChatMembersToOldExceptParams struct {
	ChatID  int64   `db:"chat_id" json:"chatId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) MoveChatMembersToOldExcept(ctx context.Context, arg MoveChatMembersToOldExceptParams) error {
	_, err := q.db.Exec(ctx, moveChatMembersToOldExcept, arg.ChatID, arg.UserIds)
	return err
}

const setChatCommandLevel = `-- name: SetChatCommandLevel :exec
INSERT INTO chat_command_levels (chat_id, command_id, level)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id, command_id) DO UPDATE SET level = EXCLUDED.level
`

type SetChatCommandLevelParams struct {
	ChatID    int64  `db:"chat_id" json:"chatId"`
	CommandID string `db:"command_id" json:"commandId"`
	Level     int16  `db:"level" json:"level"`
}

func (q *Queries) SetChatCommandLevel(ctx context.Context, arg SetChatCommandLevelParams) error {
	_, err := q.db.Exec(ctx, setChatCommandLevel, arg.ChatID, arg.CommandID, arg.Level)
	return err
}

const updateChatMemberTitle = `-- name: UpdateChatMemberTitle :exec
UPDATE chat_members
SET custom_title = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateChatMemberTitleParams struct {
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	ChatID      int64       `db:"chat_id" json:"chatId"`
	UserID      int64       `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatMemberTitle(ctx context.Context, arg UpdateChatMemberTitleParams) error {
	_, err := q.db.Exec(ctx, updateChatMemberTitle, arg.CustomTitle, arg.ChatID, arg.UserID)
	return err
}

const updateMemberLevel = `-- name: UpdateMemberLevel :exec
UPDATE chat_members
SET level = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateMemberLevelParams struct {
	Level  int16 `db:"level" json:"level"`
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateMemberLevel(ctx context.Context, arg UpdateMemberLevelParams) error {
	_, err := q.db.Exec(ctx, updateMemberLevel, arg.Level, arg.ChatID, arg.UserID)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE chat_members
SET status = $1,
    level = $2
WHERE chat_id = $3
  AND user_id = $4
`

type UpdateMemberStatusParams struct {
	Status string `db:"status" json:"status"`
	Level  int16  `db:"level" json:"level"`
	ChatID int64  `db:"chat_id" json:"chatId"`
	UserID int64  `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateMemberStatus,
		arg.Status,
		arg.Level,
		arg.ChatID,
		arg.UserID,
	)
	return err
}

const upsertChatMembers = `-- name: UpsertChatMembers :exec
INSERT INTO chat_members(chat_id, user_id, custom_title, status, level)
SELECT $1, UNNEST($2::BIGINT[]), UNNEST($3::TEXT[]), UNNEST($4::TEXT[]), UNNEST($5::SMALLINT[])
ON CONFLICT (chat_id, user_id) DO UPDATE SET custom_title = CASE
                                                                WHEN EXCLUDED.custom_title <> ''
                                                                    THEN EXCLUDED.custom_title
                                                                ELSE chat_members.custom_title
    END,
                                             status       = CASE
                                                                WHEN EXCLUDED.status = 'creator' THEN 'creator'
                                                                WHEN chat_members.status = 'administrator'
                                                                    THEN 'administrator'
                                                                ELSE EXCLUDED.status
                                                 END,
                                             level        = EXCLUDED.level,
                                             left_at      = NULL
`

type UpsertChatMembersParams struct {
	ChatID       int64    `db:"chat_id" json:"chatId"`
	UserIds      []int64  `db:"user_ids" json:"userIds"`
	CustomTitles []string `db:"custom_titles" json:"customTitles"`
	Statuses     []string `db:"statuses" json:"statuses"`
	Levels       []int16  `db:"levels" json:"levels"`
}

func (q *Queries) UpsertChatMembers(ctx context.Context, arg UpsertChatMembersParams) error {
	_, err := q.db.Exec(ctx, upsertChatMembers,
		arg.ChatID,
		arg.UserIds,
		arg.CustomTitles,
		arg.Statuses,
		arg.Levels,
	)
	return err
}
