// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChatMember = `-- name: DeleteChatMember :exec
DELETE
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type DeleteChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteChatMember(ctx context.Context, arg DeleteChatMemberParams) error {
	_, err := q.db.Exec(ctx, deleteChatMember, arg.ChatID, arg.UserID)
	return err
}

const ensureChatMemberExists = `-- name: EnsureChatMemberExists :one
INSERT INTO chat_members(chat_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT(chat_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING chat_id, user_id, joined_at, exempt_until, custom_title, role
`

type EnsureChatMemberExistsParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	UserID int64  `db:"user_id" json:"userId"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) EnsureChatMemberExists(ctx context.Context, arg EnsureChatMemberExistsParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, ensureChatMemberExists, arg.ChatID, arg.UserID, arg.Role)
	var i ChatMember
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.ExemptUntil,
		&i.CustomTitle,
		&i.Role,
	)
	return i, err
}

const ensureMemberFull = `-- name: EnsureMemberFull :one
WITH chat_upsert AS (
    INSERT INTO chats (id, weekly_norm)
    VALUES ($2, $3)
    ON CONFLICT (id) DO UPDATE SET weekly_norm = chats.weekly_norm
    RETURNING id
),
user_upsert AS (
    INSERT INTO users (id, username, first_name, last_name)
    VALUES ($4, $5, $6, $7)
    ON CONFLICT (id) DO UPDATE SET username   = EXCLUDED.username,
                                   first_name = EXCLUDED.first_name,
                                   last_name  = EXCLUDED.last_name
    RETURNING id
)
INSERT INTO chat_members (chat_id, user_id, role)
SELECT chat_upsert.id, user_upsert.id, $1
FROM chat_upsert, user_upsert
ON CONFLICT (chat_id, user_id) DO UPDATE SET 
    role = CASE 
        WHEN EXCLUDED.role = 'creator' THEN 'creator'
        WHEN chat_members.role = 'administrator' THEN 'administrator'
        WHEN chat_members.role = 'creator' AND EXCLUDED.role <> 'creator' THEN 'creator' -- creator remains creator unless EXCLUDED specifically says otherwise (sync might not have it)
        ELSE EXCLUDED.role
    END
RETURNING chat_id, user_id, joined_at, exempt_until, custom_title, role
`

type EnsureMemberFullParams struct {
	Role       string      `db:"role" json:"role"`
	ChatID     int64       `db:"chat_id" json:"chatId"`
	WeeklyNorm int32       `db:"weekly_norm" json:"weeklyNorm"`
	UserID     int64       `db:"user_id" json:"userId"`
	Username   pgtype.Text `db:"username" json:"username"`
	FirstName  pgtype.Text `db:"first_name" json:"firstName"`
	LastName   pgtype.Text `db:"last_name" json:"lastName"`
}

func (q *Queries) EnsureMemberFull(ctx context.Context, arg EnsureMemberFullParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, ensureMemberFull,
		arg.Role,
		arg.ChatID,
		arg.WeeklyNorm,
		arg.UserID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	var i ChatMember
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.ExemptUntil,
		&i.CustomTitle,
		&i.Role,
	)
	return i, err
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_id, user_id, joined_at, exempt_until, custom_title, role, id, username, first_name, last_name, created_at
FROM chat_members
         JOIN users ON users.id = user_id
WHERE chat_id = $1
  AND user_id = $2
`

type GetChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type GetChatMemberRow struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	CustomTitle pgtype.Text        `db:"custom_title" json:"customTitle"`
	Role        string             `db:"role" json:"role"`
	ID          int64              `db:"id" json:"id"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (GetChatMemberRow, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChatID, arg.UserID)
	var i GetChatMemberRow
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.JoinedAt,
		&i.ExemptUntil,
		&i.CustomTitle,
		&i.Role,
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMembers = `-- name: GetChatMembers :many
SELECT chat_id, user_id, joined_at, exempt_until, custom_title, role, id, username, first_name, last_name, created_at
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
`

type GetChatMembersRow struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	CustomTitle pgtype.Text        `db:"custom_title" json:"customTitle"`
	Role        string             `db:"role" json:"role"`
	ID          int64              `db:"id" json:"id"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) GetChatMembers(ctx context.Context, chatID int64) ([]GetChatMembersRow, error) {
	rows, err := q.db.Query(ctx, getChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersRow{}
	for rows.Next() {
		var i GetChatMembersRow
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.JoinedAt,
			&i.ExemptUntil,
			&i.CustomTitle,
			&i.Role,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMembersWithTitles = `-- name: GetChatMembersWithTitles :many
SELECT cm.user_id, cm.custom_title, cm.role, u.first_name, u.last_name, u.username
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
WHERE cm.chat_id = $1
  AND cm.custom_title IS NOT NULL
  AND cm.custom_title <> ''
`

type GetChatMembersWithTitlesRow struct {
	UserID      int64       `db:"user_id" json:"userId"`
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	Role        string      `db:"role" json:"role"`
	FirstName   pgtype.Text `db:"first_name" json:"firstName"`
	LastName    pgtype.Text `db:"last_name" json:"lastName"`
	Username    pgtype.Text `db:"username" json:"username"`
}

func (q *Queries) GetChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetChatMembersWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, getChatMembersWithTitles, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersWithTitlesRow{}
	for rows.Next() {
		var i GetChatMembersWithTitlesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CustomTitle,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberCustomTitle = `-- name: GetMemberCustomTitle :one
SELECT custom_title
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type GetMemberCustomTitleParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetMemberCustomTitle(ctx context.Context, arg GetMemberCustomTitleParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getMemberCustomTitle, arg.ChatID, arg.UserID)
	var custom_title pgtype.Text
	err := row.Scan(&custom_title)
	return custom_title, err
}

const updateChatMemberRole = `-- name: UpdateChatMemberRole :exec
UPDATE chat_members
SET role = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateChatMemberRoleParams struct {
	Role   string `db:"role" json:"role"`
	ChatID int64  `db:"chat_id" json:"chatId"`
	UserID int64  `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatMemberRole(ctx context.Context, arg UpdateChatMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateChatMemberRole, arg.Role, arg.ChatID, arg.UserID)
	return err
}

const updateChatMemberTitle = `-- name: UpdateChatMemberTitle :exec
UPDATE chat_members
SET custom_title = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateChatMemberTitleParams struct {
	CustomTitle pgtype.Text `db:"custom_title" json:"customTitle"`
	ChatID      int64       `db:"chat_id" json:"chatId"`
	UserID      int64       `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatMemberTitle(ctx context.Context, arg UpdateChatMemberTitleParams) error {
	_, err := q.db.Exec(ctx, updateChatMemberTitle, arg.CustomTitle, arg.ChatID, arg.UserID)
	return err
}

const upsertChatMembersWithRole = `-- name: UpsertChatMembersWithRole :exec
INSERT INTO chat_members(chat_id, user_id, custom_title, role)
SELECT $1, UNNEST($2::BIGINT[]), UNNEST($3::TEXT[]), UNNEST($4::TEXT[])
ON CONFLICT (chat_id, user_id) DO UPDATE SET 
    custom_title = EXCLUDED.custom_title, 
    role = CASE 
        WHEN EXCLUDED.role = 'creator' THEN 'creator'
        WHEN chat_members.role = 'administrator' THEN 'administrator'
        ELSE EXCLUDED.role
    END
`

type UpsertChatMembersWithRoleParams struct {
	ChatID       int64    `db:"chat_id" json:"chatId"`
	UserIds      []int64  `db:"user_ids" json:"userIds"`
	CustomTitles []string `db:"custom_titles" json:"customTitles"`
	Roles        []string `db:"roles" json:"roles"`
}

func (q *Queries) UpsertChatMembersWithRole(ctx context.Context, arg UpsertChatMembersWithRoleParams) error {
	_, err := q.db.Exec(ctx, upsertChatMembersWithRole,
		arg.ChatID,
		arg.UserIds,
		arg.CustomTitles,
		arg.Roles,
	)
	return err
}
