// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package db

import (
	"context"

	"activity-bot/internal/model"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChatMember = `-- name: DeleteChatMember :exec
UPDATE chat_members
SET left_at = now()
WHERE chat_id = $1
  AND user_id = $2
  AND left_at IS NULL
`

type DeleteChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteChatMember(ctx context.Context, arg DeleteChatMemberParams) error {
	_, err := q.db.Exec(ctx, deleteChatMember, arg.ChatID, arg.UserID)
	return err
}

const ensureMemberFull = `-- name: EnsureMemberFull :one
WITH chat_upsert AS (
    INSERT INTO chats (id)
        VALUES ($1)
        ON CONFLICT (id) DO NOTHING
        RETURNING id
),
     chat_id_resolve AS (
         SELECT id FROM chat_upsert
         UNION ALL
         SELECT id FROM chats WHERE id = $1
         LIMIT 1
     ),
     user_upsert AS (
         INSERT INTO users (id, username, first_name, last_name)
             VALUES ($2, $3, $4, $5)
             ON CONFLICT (id) DO UPDATE
                 SET username = EXCLUDED.username,
                     first_name = EXCLUDED.first_name,
                     last_name = EXCLUDED.last_name
             RETURNING id
     ),
     member_upsert AS (
         INSERT INTO chat_members (chat_id, user_id, tag)
             SELECT chat_id_resolve.id,
                    user_upsert.id,
                    $6
             FROM chat_id_resolve, user_upsert
             ON CONFLICT (chat_id, user_id) DO UPDATE
                 SET tag = CASE
                               WHEN $6 IS NOT NULL AND $6 <> ''
                                   THEN $6
                               ELSE chat_members.tag
                     END,
                     left_at = NULL
             RETURNING chat_id, user_id, joined_at, rest_until, tag, left_at, rest_reason, emoji, status, emoji_json
     )
SELECT
    chat_members.chat_id, chat_members.user_id, chat_members.joined_at, chat_members.rest_until, chat_members.tag, chat_members.left_at, chat_members.rest_reason, chat_members.emoji, chat_members.status, chat_members.emoji_json,
    users.id, users.username, users.first_name, users.last_name, users.created_at, users.gender, users.emoji, users.custom_emoji_id, users.emoji_json
FROM member_upsert cm
         JOIN chat_members ON chat_members.chat_id = cm.chat_id
    AND chat_members.user_id = cm.user_id
         JOIN users ON users.id = cm.user_id
`

type EnsureMemberFullParams struct {
	ChatID    int64       `db:"chat_id" json:"chatId"`
	UserID    int64       `db:"user_id" json:"userId"`
	Username  pgtype.Text `db:"username" json:"username"`
	FirstName pgtype.Text `db:"first_name" json:"firstName"`
	LastName  pgtype.Text `db:"last_name" json:"lastName"`
	Tag       pgtype.Text `db:"tag" json:"tag"`
}

type EnsureMemberFullRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) EnsureMemberFull(ctx context.Context, arg EnsureMemberFullParams) (EnsureMemberFullRow, error) {
	row := q.db.QueryRow(ctx, ensureMemberFull,
		arg.ChatID,
		arg.UserID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Tag,
	)
	var i EnsureMemberFullRow
	err := row.Scan(
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
	)
	return i, err
}

const findChatMembersByTag = `-- name: FindChatMembersByTag :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND (
    (length($2::text) < 2 AND lower(cm.tag::text) = lower($2::text))
        OR
    (length($2::text) >= 2 AND cm.tag ILIKE '%' || $2::text || '%')
    )
ORDER BY cm.left_at IS NOT NULL, cm.left_at
`

type FindChatMembersByTagParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Tag    string `db:"tag" json:"tag"`
}

type FindChatMembersByTagRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) FindChatMembersByTag(ctx context.Context, arg FindChatMembersByTagParams) ([]FindChatMembersByTagRow, error) {
	rows, err := q.db.Query(ctx, findChatMembersByTag, arg.ChatID, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindChatMembersByTagRow{}
	for rows.Next() {
		var i FindChatMembersByTagRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnyChatMembersWithTitles = `-- name: GetAnyChatMembersWithTitles :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
WHERE cm.chat_id = $1
  AND cm.tag IS NOT NULL
  AND cm.tag <> ''
  AND cm.left_at IS NULL
`

type GetAnyChatMembersWithTitlesRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetAnyChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetAnyChatMembersWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, getAnyChatMembersWithTitles, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnyChatMembersWithTitlesRow{}
	for rows.Next() {
		var i GetAnyChatMembersWithTitlesRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatAdmins = `-- name: GetChatAdmins :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.status > 0
ORDER BY cm.joined_at
`

type GetChatAdminsRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatAdmins(ctx context.Context, chatID int64) ([]GetChatAdminsRow, error) {
	rows, err := q.db.Query(ctx, getChatAdmins, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAdminsRow{}
	for rows.Next() {
		var i GetChatAdminsRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_members.chat_id, chat_members.user_id, chat_members.joined_at, chat_members.rest_until, chat_members.tag, chat_members.left_at, chat_members.rest_reason, chat_members.emoji, chat_members.status, chat_members.emoji_json, users.id, users.username, users.first_name, users.last_name, users.created_at, users.gender, users.emoji, users.custom_emoji_id, users.emoji_json
FROM chat_members
         JOIN users ON users.id = user_id
  AND chat_id = $1
  AND user_id = $2
`

type GetChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type GetChatMemberRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (GetChatMemberRow, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChatID, arg.UserID)
	var i GetChatMemberRow
	err := row.Scan(
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
	)
	return i, err
}

const getChatMemberByUsername = `-- name: GetChatMemberByUsername :one
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND u.username ILIKE $2
LIMIT 1
`

type GetChatMemberByUsernameParams struct {
	ChatID   int64       `db:"chat_id" json:"chatId"`
	Username pgtype.Text `db:"username" json:"username"`
}

type GetChatMemberByUsernameRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatMemberByUsername(ctx context.Context, arg GetChatMemberByUsernameParams) (GetChatMemberByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getChatMemberByUsername, arg.ChatID, arg.Username)
	var i GetChatMemberByUsernameRow
	err := row.Scan(
		&i.ChatMember.ChatID,
		&i.ChatMember.UserID,
		&i.ChatMember.JoinedAt,
		&i.ChatMember.RestUntil,
		&i.ChatMember.Tag,
		&i.ChatMember.LeftAt,
		&i.ChatMember.RestReason,
		&i.ChatMember.Emoji,
		&i.ChatMember.Status,
		&i.ChatMember.EmojiJson,
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.CreatedAt,
		&i.User.Gender,
		&i.User.Emoji,
		&i.User.CustomEmojiID,
		&i.User.EmojiJson,
	)
	return i, err
}

const getChatMembers = `-- name: GetChatMembers :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.left_at IS NULL
`

type GetChatMembersRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatMembers(ctx context.Context, chatID int64) ([]GetChatMembersRow, error) {
	rows, err := q.db.Query(ctx, getChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersRow{}
	for rows.Next() {
		var i GetChatMembersRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMembersWithTitles = `-- name: GetChatMembersWithTitles :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
WHERE cm.chat_id = $1
  AND cm.left_at IS NULL
  AND cm.tag IS NOT NULL
  AND cm.tag <> ''
ORDER BY cm.tag COLLATE "und-x-icu"
`

type GetChatMembersWithTitlesRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetChatMembersWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, getChatMembersWithTitles, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMembersWithTitlesRow{}
	for rows.Next() {
		var i GetChatMembersWithTitlesRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberCustomTitle = `-- name: GetMemberCustomTitle :one
SELECT tag
FROM chat_members
WHERE chat_id = $1
  AND user_id = $2
`

type GetMemberCustomTitleParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetMemberCustomTitle(ctx context.Context, arg GetMemberCustomTitleParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getMemberCustomTitle, arg.ChatID, arg.UserID)
	var tag pgtype.Text
	err := row.Scan(&tag)
	return tag, err
}

const getMembersWithExpiredMute = `-- name: GetMembersWithExpiredMute :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json
FROM moderation_actions ma
         JOIN chat_members cm ON ma.chat_id = cm.chat_id AND ma.user_id = cm.user_id
WHERE ma.type = 'mute'
  AND ma.revoked_at IS NULL
  AND ma.expires_at <= NOW()
`

type GetMembersWithExpiredMuteRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
}

func (q *Queries) GetMembersWithExpiredMute(ctx context.Context) ([]GetMembersWithExpiredMuteRow, error) {
	rows, err := q.db.Query(ctx, getMembersWithExpiredMute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMembersWithExpiredMuteRow{}
	for rows.Next() {
		var i GetMembersWithExpiredMuteRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoNormMembers = `-- name: GetNoNormMembers :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN chats c ON c.id = cm.chat_id
         JOIN users u ON u.id = cm.user_id
         LEFT JOIN (SELECT chat_id, user_id, COUNT(*) AS msg_count
                    FROM messages
                    WHERE (messages.created_at >= $1 OR $1::timestamptz IS NULL)
                      AND (messages.created_at < $2 OR $2::timestamptz IS NULL)
                    GROUP BY chat_id, user_id) m ON m.chat_id = cm.chat_id AND m.user_id = cm.user_id

WHERE cm.chat_id = $3
  AND cm.left_at IS NULL
  AND (cm.rest_until IS NULL OR cm.rest_until < now())
  AND (
    ($4 = 'warn' AND (c.norm_ban IS NULL OR COALESCE(m.msg_count, 0) > c.norm_ban) AND
     COALESCE(m.msg_count, 0) < c.norm_warn)
        OR ($4 = 'ban' AND COALESCE(m.msg_count, 0) < c.norm_ban)
        OR ($4 = 'any' AND COALESCE(m.msg_count, 0) < GREATEST(c.norm_warn, c.norm_ban))
    )
`

type GetNoNormMembersParams struct {
	FromDate pgtype.Timestamptz `db:"from_date" json:"fromDate"`
	ToDate   pgtype.Timestamptz `db:"to_date" json:"toDate"`
	ChatID   int64              `db:"chat_id" json:"chatId"`
	Mode     interface{}        `db:"mode" json:"mode"`
}

type GetNoNormMembersRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetNoNormMembers(ctx context.Context, arg GetNoNormMembersParams) ([]GetNoNormMembersRow, error) {
	rows, err := q.db.Query(ctx, getNoNormMembers,
		arg.FromDate,
		arg.ToDate,
		arg.ChatID,
		arg.Mode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNoNormMembersRow{}
	for rows.Next() {
		var i GetNoNormMembersRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inactiveChatMembers = `-- name: InactiveChatMembers :many
SELECT u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json,
       cm.tag,
       cm.status,
       cm.rest_until,
       MAX(m.created_at)::timestamptz AS last_message_at
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
         LEFT JOIN messages m
                   ON m.user_id = cm.user_id AND m.chat_id = cm.chat_id
WHERE cm.left_at IS NULL
  AND cm.chat_id = $1
  AND (cm.rest_until IS NULL OR cm.rest_until < now())
GROUP BY cm.user_id, u.id, u.first_name, u.last_name, u.username, cm.tag, cm.status, cm.rest_until
HAVING MAX(m.created_at) IS NULL
    OR MAX(m.created_at) < NOW() - INTERVAL '1 days'
ORDER BY MAX(m.created_at) NULLS FIRST
`

type InactiveChatMembersRow struct {
	User          User               `db:"user" json:"user"`
	Tag           pgtype.Text        `db:"tag" json:"tag"`
	Status        int16              `db:"status" json:"status"`
	RestUntil     pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	LastMessageAt pgtype.Timestamptz `db:"last_message_at" json:"lastMessageAt"`
}

func (q *Queries) InactiveChatMembers(ctx context.Context, chatID int64) ([]InactiveChatMembersRow, error) {
	rows, err := q.db.Query(ctx, inactiveChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InactiveChatMembersRow{}
	for rows.Next() {
		var i InactiveChatMembersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.Tag,
			&i.Status,
			&i.RestUntil,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChatMembersLeftNotInList = `-- name: MarkChatMembersLeftNotInList :exec
UPDATE chat_members
SET left_at = now()
WHERE chat_id = $1
  AND left_at IS NULL
  AND user_id <> ALL ($2::BIGINT[])
`

type MarkChatMembersLeftNotInListParams struct {
	ChatID  int64   `db:"chat_id" json:"chatId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) MarkChatMembersLeftNotInList(ctx context.Context, arg MarkChatMembersLeftNotInListParams) error {
	_, err := q.db.Exec(ctx, markChatMembersLeftNotInList, arg.ChatID, arg.UserIds)
	return err
}

const moveChatMembersToNew = `-- name: MoveChatMembersToNew :exec
UPDATE chat_members cm
SET joined_at = now()
FROM chats c
WHERE c.id = cm.chat_id
  AND cm.chat_id = $1
  AND cm.user_id = ANY ($2::BIGINT[])
`

type MoveChatMembersToNewParams struct {
	ChatID  int64   `db:"chat_id" json:"chatId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) MoveChatMembersToNew(ctx context.Context, arg MoveChatMembersToNewParams) error {
	_, err := q.db.Exec(ctx, moveChatMembersToNew, arg.ChatID, arg.UserIds)
	return err
}

const moveChatMembersToOldExcept = `-- name: MoveChatMembersToOldExcept :exec
UPDATE chat_members cm
SET joined_at = joined_at - ((c.newbie_threshold_days + 1) || ' days')::interval
FROM chats c
WHERE c.id = cm.chat_id
  AND cm.chat_id = $1
  AND cm.user_id <> ALL ($2::BIGINT[])
`

type MoveChatMembersToOldExceptParams struct {
	ChatID  int64   `db:"chat_id" json:"chatId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) MoveChatMembersToOldExcept(ctx context.Context, arg MoveChatMembersToOldExceptParams) error {
	_, err := q.db.Exec(ctx, moveChatMembersToOldExcept, arg.ChatID, arg.UserIds)
	return err
}

const resetChatMemberCreators = `-- name: ResetChatMemberCreators :exec
UPDATE chat_members
SET status = 0
WHERE chat_id = $1
  AND status = 5
`

func (q *Queries) ResetChatMemberCreators(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, resetChatMemberCreators, chatID)
	return err
}

const setChatMemberEmoji = `-- name: SetChatMemberEmoji :exec
UPDATE chat_members
SET emoji = $1
WHERE user_id = $2
  AND chat_id = $3
`

type SetChatMemberEmojiParams struct {
	Emoji  pgtype.Text `db:"emoji" json:"emoji"`
	UserID int64       `db:"user_id" json:"userId"`
	ChatID int64       `db:"chat_id" json:"chatId"`
}

func (q *Queries) SetChatMemberEmoji(ctx context.Context, arg SetChatMemberEmojiParams) error {
	_, err := q.db.Exec(ctx, setChatMemberEmoji, arg.Emoji, arg.UserID, arg.ChatID)
	return err
}

const setChatMemberEmojiJSON = `-- name: SetChatMemberEmojiJSON :exec
UPDATE chat_members
SET emoji_json = $1
WHERE user_id = $2
  AND chat_id = $3
`

type SetChatMemberEmojiJSONParams struct {
	EmojiJson model.Emojis `db:"emoji_json" json:"emojiJson"`
	UserID    int64        `db:"user_id" json:"userId"`
	ChatID    int64        `db:"chat_id" json:"chatId"`
}

func (q *Queries) SetChatMemberEmojiJSON(ctx context.Context, arg SetChatMemberEmojiJSONParams) error {
	_, err := q.db.Exec(ctx, setChatMemberEmojiJSON, arg.EmojiJson, arg.UserID, arg.ChatID)
	return err
}

const setChatMemberStatus = `-- name: SetChatMemberStatus :exec
UPDATE chat_members
SET status = $1
WHERE chat_id = $2
  AND user_id = $3
`

type SetChatMemberStatusParams struct {
	Status int16 `db:"status" json:"status"`
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) SetChatMemberStatus(ctx context.Context, arg SetChatMemberStatusParams) error {
	_, err := q.db.Exec(ctx, setChatMemberStatus, arg.Status, arg.ChatID, arg.UserID)
	return err
}

const updateChatMemberTitle = `-- name: UpdateChatMemberTitle :exec
UPDATE chat_members
SET tag = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateChatMemberTitleParams struct {
	Tag    pgtype.Text `db:"tag" json:"tag"`
	ChatID int64       `db:"chat_id" json:"chatId"`
	UserID int64       `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateChatMemberTitle(ctx context.Context, arg UpdateChatMemberTitleParams) error {
	_, err := q.db.Exec(ctx, updateChatMemberTitle, arg.Tag, arg.ChatID, arg.UserID)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE chat_members
SET status = $1
WHERE chat_id = $2
  AND user_id = $3
`

type UpdateMemberStatusParams struct {
	Status int16 `db:"status" json:"status"`
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateMemberStatus, arg.Status, arg.ChatID, arg.UserID)
	return err
}

const upsertChatMembers = `-- name: UpsertChatMembers :exec
INSERT INTO chat_members(chat_id, user_id, tag, status)
SELECT $1, UNNEST($2::BIGINT[]), UNNEST($3::TEXT[]), UNNEST($4::SMALLINT[])
ON CONFLICT (chat_id, user_id) DO UPDATE SET tag     = CASE
                                                           WHEN EXCLUDED.tag <> ''
                                                               THEN EXCLUDED.tag
                                                           ELSE chat_members.tag
    END,
                                             status  = GREATEST(EXCLUDED.status, chat_members.status),
                                             left_at = NULL
`

type UpsertChatMembersParams struct {
	ChatID   int64    `db:"chat_id" json:"chatId"`
	UserIds  []int64  `db:"user_ids" json:"userIds"`
	Tags     []string `db:"tags" json:"tags"`
	Statuses []int16  `db:"statuses" json:"statuses"`
}

func (q *Queries) UpsertChatMembers(ctx context.Context, arg UpsertChatMembersParams) error {
	_, err := q.db.Exec(ctx, upsertChatMembers,
		arg.ChatID,
		arg.UserIds,
		arg.Tags,
		arg.Statuses,
	)
	return err
}
