// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(chat_id, user_id, created_at, deleted_at)
VALUES ($1, $2, $3, $4)
RETURNING chat_id, user_id, created_at, deleted_at
`

type CreateMessageParams struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deletedAt"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatID,
		arg.UserID,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Message
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
