// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(chat_id, user_id, created_at, message_id)
VALUES ($1, $2, $3, $4)
RETURNING chat_id, user_id, created_at, id, message_id
`

type CreateMessageParams struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	MessageID pgtype.Int8        `db:"message_id" json:"messageId"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatID,
		arg.UserID,
		arg.CreatedAt,
		arg.MessageID,
	)
	var i Message
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.CreatedAt,
		&i.ID,
		&i.MessageID,
	)
	return i, err
}

const inactiveChatMembers = `-- name: InactiveChatMembers :many
SELECT u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, cm.custom_title, cm.status, cm.rest_until, MAX(m.created_at)::timestamptz AS last_message_at
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
         LEFT JOIN messages m
                   ON m.user_id = cm.user_id AND m.chat_id = cm.chat_id
WHERE cm.left_at IS NULL
  AND cm.chat_id = $1
  AND (cm.rest_until IS NULL OR cm.rest_until < now())
GROUP BY cm.user_id, u.id, u.first_name, u.last_name, u.username, cm.custom_title, cm.status, cm.rest_until
HAVING MAX(m.created_at) IS NULL
    OR MAX(m.created_at) < NOW() - INTERVAL '1 days'
ORDER BY MAX(m.created_at) NULLS FIRST
`

type InactiveChatMembersRow struct {
	ID            int64              `db:"id" json:"id"`
	Username      pgtype.Text        `db:"username" json:"username"`
	FirstName     pgtype.Text        `db:"first_name" json:"firstName"`
	LastName      pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	Gender        string             `db:"gender" json:"gender"`
	CustomTitle   pgtype.Text        `db:"custom_title" json:"customTitle"`
	Status        string             `db:"status" json:"status"`
	RestUntil     pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	LastMessageAt pgtype.Timestamptz `db:"last_message_at" json:"lastMessageAt"`
}

func (q *Queries) InactiveChatMembers(ctx context.Context, chatID int64) ([]InactiveChatMembersRow, error) {
	rows, err := q.db.Query(ctx, inactiveChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InactiveChatMembersRow{}
	for rows.Next() {
		var i InactiveChatMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.Gender,
			&i.CustomTitle,
			&i.Status,
			&i.RestUntil,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageActivityByDay = `-- name: MessageActivityByDay :many
SELECT date_trunc('day', m.created_at)::date AS day,
       COUNT(m.chat_id)                      AS messages_count
FROM messages m
         JOIN chat_members cm ON cm.chat_id = m.chat_id AND cm.user_id = m.user_id
WHERE m.chat_id = $1
  AND m.user_id = $2
  AND m.created_at >= GREATEST(
        now() - interval '30 days',
        cm.joined_at
                      )
GROUP BY day
ORDER BY day
`

type MessageActivityByDayParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type MessageActivityByDayRow struct {
	Day           pgtype.Date `db:"day" json:"day"`
	MessagesCount int64       `db:"messages_count" json:"messagesCount"`
}

func (q *Queries) MessageActivityByDay(ctx context.Context, arg MessageActivityByDayParams) ([]MessageActivityByDayRow, error) {
	rows, err := q.db.Query(ctx, messageActivityByDay, arg.ChatID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageActivityByDayRow{}
	for rows.Next() {
		var i MessageActivityByDayRow
		if err := rows.Scan(&i.Day, &i.MessagesCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageActivityByDayAll = `-- name: MessageActivityByDayAll :many
SELECT date_trunc('day', m.created_at)::date AS day,
       COUNT(*)                              AS messages_count
FROM messages m
WHERE m.chat_id = $1
  AND m.created_at >= COALESCE($2, now() - interval '30 days')
  AND m.created_at <= COALESCE($3, now())
GROUP BY day
ORDER BY day
`

type MessageActivityByDayAllParams struct {
	ChatID   int64              `db:"chat_id" json:"chatId"`
	FromDate pgtype.Timestamptz `db:"from_date" json:"fromDate"`
	ToDate   pgtype.Timestamptz `db:"to_date" json:"toDate"`
}

type MessageActivityByDayAllRow struct {
	Day           pgtype.Date `db:"day" json:"day"`
	MessagesCount int64       `db:"messages_count" json:"messagesCount"`
}

func (q *Queries) MessageActivityByDayAll(ctx context.Context, arg MessageActivityByDayAllParams) ([]MessageActivityByDayAllRow, error) {
	rows, err := q.db.Query(ctx, messageActivityByDayAll, arg.ChatID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageActivityByDayAllRow{}
	for rows.Next() {
		var i MessageActivityByDayAllRow
		if err := rows.Scan(&i.Day, &i.MessagesCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageReport = `-- name: MessageReport :many
SELECT cm.user_id,
       u.username,
       u.first_name,
       u.last_name,
       COUNT(m.chat_id) AS messages_count,
       c.norm_warn,
       c.norm_ban,
       cm.joined_at,
       c.newbie_threshold_days,
       cm.status,
       cm.custom_title
FROM chat_members cm
         JOIN chats c ON c.id = cm.chat_id
         JOIN users u ON u.id = cm.user_id
         LEFT JOIN messages m
                   ON m.chat_id = cm.chat_id
                       AND m.user_id = cm.user_id
                       AND (
                          (m.created_at >= $1 OR $1::timestamptz IS NULL)
                              AND (m.created_at < $2 OR $2::timestamptz IS NULL)
                          )
WHERE cm.chat_id = $3
  AND cm.left_at IS NULL
  AND (cm.rest_until IS NULL OR cm.rest_until < now())
GROUP BY cm.user_id, u.username, u.first_name, u.last_name,
         c.norm_warn, c.norm_ban, cm.joined_at, c.newbie_threshold_days,
         cm.status, cm.custom_title
ORDER BY messages_count DESC
`

type MessageReportParams struct {
	FromDate pgtype.Timestamptz `db:"from_date" json:"fromDate"`
	ToDate   pgtype.Timestamptz `db:"to_date" json:"toDate"`
	ChatID   int64              `db:"chat_id" json:"chatId"`
}

type MessageReportRow struct {
	UserID              int64              `db:"user_id" json:"userId"`
	Username            pgtype.Text        `db:"username" json:"username"`
	FirstName           pgtype.Text        `db:"first_name" json:"firstName"`
	LastName            pgtype.Text        `db:"last_name" json:"lastName"`
	MessagesCount       int64              `db:"messages_count" json:"messagesCount"`
	NormWarn            int32              `db:"norm_warn" json:"normWarn"`
	NormBan             pgtype.Int4        `db:"norm_ban" json:"normBan"`
	JoinedAt            pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	NewbieThresholdDays int32              `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	Status              string             `db:"status" json:"status"`
	CustomTitle         pgtype.Text        `db:"custom_title" json:"customTitle"`
}

func (q *Queries) MessageReport(ctx context.Context, arg MessageReportParams) ([]MessageReportRow, error) {
	rows, err := q.db.Query(ctx, messageReport, arg.FromDate, arg.ToDate, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageReportRow{}
	for rows.Next() {
		var i MessageReportRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.MessagesCount,
			&i.NormWarn,
			&i.NormBan,
			&i.JoinedAt,
			&i.NewbieThresholdDays,
			&i.Status,
			&i.CustomTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageReportOne = `-- name: MessageReportOne :one
SELECT cm.user_id,
       u.username,
       u.first_name,
       u.last_name,

       COALESCE(COUNT(m.chat_id) FILTER (WHERE m.created_at >= date_trunc('day', now())), 0)::bigint   AS day_count,
       COALESCE(COUNT(m.chat_id) FILTER (WHERE m.created_at >= now() - interval '1 day'),
                0)::bigint                                                                             AS day_rolling_count,
       COALESCE(
                       COUNT(m.chat_id) FILTER (
                   WHERE m.created_at >= (
                       date_trunc('day', now())
                           - ((extract(isodow from now())::int - c.week_start_day + 7) % 7)
                           * interval '1 day'
                       )
                   ),
                       0
       )::bigint                                                                                       AS week_count,

       COALESCE(COUNT(m.chat_id) FILTER (WHERE m.created_at >= now() - interval '7 days'),
                0)::bigint                                                                             AS week_rolling_count,
       COALESCE(COUNT(m.chat_id) FILTER (WHERE m.created_at >= date_trunc('month', now())), 0)::bigint AS month_count,
       COALESCE(COUNT(m.chat_id) FILTER (WHERE m.created_at >= now() - interval '30 days'),
                0)::bigint                                                                             AS month_rolling_count,
       COALESCE(COUNT(m.chat_id), 0)::bigint                                                           AS all_time_count,

       c.norm_ban,
       c.norm_warn,
       cm.joined_at,
       c.newbie_threshold_days,
       cm.status,
       cm.custom_title,
       cm.rest_until,
       cm.left_at
FROM chat_members cm
         JOIN chats c ON c.id = cm.chat_id
         JOIN users u ON u.id = cm.user_id
         LEFT JOIN messages m
                   ON m.chat_id = cm.chat_id
                       AND m.user_id = cm.user_id

WHERE cm.chat_id = $1
  AND cm.user_id = $2
GROUP BY cm.user_id,
         u.username,
         u.first_name,
         u.last_name,
         c.norm_warn,
         c.norm_ban,
         cm.joined_at,
         c.newbie_threshold_days,
         cm.status,
         cm.custom_title,
         cm.rest_until,
         cm.left_at
`

type MessageReportOneParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type MessageReportOneRow struct {
	UserID              int64              `db:"user_id" json:"userId"`
	Username            pgtype.Text        `db:"username" json:"username"`
	FirstName           pgtype.Text        `db:"first_name" json:"firstName"`
	LastName            pgtype.Text        `db:"last_name" json:"lastName"`
	DayCount            int64              `db:"day_count" json:"dayCount"`
	DayRollingCount     int64              `db:"day_rolling_count" json:"dayRollingCount"`
	WeekCount           int64              `db:"week_count" json:"weekCount"`
	WeekRollingCount    int64              `db:"week_rolling_count" json:"weekRollingCount"`
	MonthCount          int64              `db:"month_count" json:"monthCount"`
	MonthRollingCount   int64              `db:"month_rolling_count" json:"monthRollingCount"`
	AllTimeCount        int64              `db:"all_time_count" json:"allTimeCount"`
	NormBan             pgtype.Int4        `db:"norm_ban" json:"normBan"`
	NormWarn            int32              `db:"norm_warn" json:"normWarn"`
	JoinedAt            pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	NewbieThresholdDays int32              `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	Status              string             `db:"status" json:"status"`
	CustomTitle         pgtype.Text        `db:"custom_title" json:"customTitle"`
	RestUntil           pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	LeftAt              pgtype.Timestamptz `db:"left_at" json:"leftAt"`
}

func (q *Queries) MessageReportOne(ctx context.Context, arg MessageReportOneParams) (MessageReportOneRow, error) {
	row := q.db.QueryRow(ctx, messageReportOne, arg.ChatID, arg.UserID)
	var i MessageReportOneRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.DayCount,
		&i.DayRollingCount,
		&i.WeekCount,
		&i.WeekRollingCount,
		&i.MonthCount,
		&i.MonthRollingCount,
		&i.AllTimeCount,
		&i.NormBan,
		&i.NormWarn,
		&i.JoinedAt,
		&i.NewbieThresholdDays,
		&i.Status,
		&i.CustomTitle,
		&i.RestUntil,
		&i.LeftAt,
	)
	return i, err
}
