// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWarns = `-- name: ClearWarns :exec
DELETE
FROM moderation_actions
WHERE chat_id = $1
  AND user_id = $2
  AND type = 'warn'
`

type ClearWarnsParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) ClearWarns(ctx context.Context, arg ClearWarnsParams) error {
	_, err := q.db.Exec(ctx, clearWarns, arg.ChatID, arg.UserID)
	return err
}

const createModerationAction = `-- name: CreateModerationAction :exec
INSERT INTO moderation_actions (type, chat_id, user_id, moderator_id, reason, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateModerationActionParams struct {
	Type        ModerationType     `db:"type" json:"type"`
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	ModeratorID int64              `db:"moderator_id" json:"moderatorId"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) error {
	_, err := q.db.Exec(ctx, createModerationAction,
		arg.Type,
		arg.ChatID,
		arg.UserID,
		arg.ModeratorID,
		arg.Reason,
		arg.ExpiresAt,
	)
	return err
}

const deleteModerationActionsForUser = `-- name: DeleteModerationActionsForUser :exec
DELETE
FROM moderation_actions
WHERE chat_id = $1
  AND user_id = $2
`

type DeleteModerationActionsForUserParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteModerationActionsForUser(ctx context.Context, arg DeleteModerationActionsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteModerationActionsForUser, arg.ChatID, arg.UserID)
	return err
}

const getActiveWarns = `-- name: GetActiveWarns :many
SELECT um.id, um.username, um.first_name, um.last_name, um.created_at, um.gender, um.emoji, um.custom_emoji_id, um.emoji_json, cmm.chat_id, cmm.user_id, cmm.joined_at, cmm.rest_until, cmm.tag, cmm.left_at, cmm.rest_reason, cmm.emoji, cmm.status, cmm.emoji_json, cmm.exclude_from_call, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json, cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, cm.exclude_from_call, ma.id, ma.type, ma.chat_id, ma.user_id, ma.moderator_id, ma.reason, ma.created_at, ma.revoked_at, ma.expires_at
FROM moderation_actions ma
         JOIN chat_members cmm ON cmm.user_id = ma.moderator_id AND cmm.chat_id = ma.chat_id
         JOIN users um ON um.id = ma.moderator_id

         JOIN chat_members cm ON cm.user_id = ma.user_id AND cm.chat_id = ma.chat_id
         JOIN users u ON u.id = ma.user_id
WHERE ma.chat_id = $1
  AND ma.user_id = $2
  AND ma.type = 'warn'
ORDER BY ma.created_at
`

type GetActiveWarnsParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

type GetActiveWarnsRow struct {
	User         User               `db:"user" json:"user"`
	ChatMember   ChatMember         `db:"chat_member" json:"chatMember"`
	User_2       User               `db:"user_2" json:"user2"`
	ChatMember_2 ChatMember         `db:"chat_member_2" json:"chatMember2"`
	ID           int64              `db:"id" json:"id"`
	Type         ModerationType     `db:"type" json:"type"`
	ChatID       int64              `db:"chat_id" json:"chatId"`
	UserID       int64              `db:"user_id" json:"userId"`
	ModeratorID  int64              `db:"moderator_id" json:"moderatorId"`
	Reason       pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revokedAt"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) GetActiveWarns(ctx context.Context, arg GetActiveWarnsParams) ([]GetActiveWarnsRow, error) {
	rows, err := q.db.Query(ctx, getActiveWarns, arg.ChatID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveWarnsRow{}
	for rows.Next() {
		var i GetActiveWarnsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
			&i.User_2.ID,
			&i.User_2.Username,
			&i.User_2.FirstName,
			&i.User_2.LastName,
			&i.User_2.CreatedAt,
			&i.User_2.Gender,
			&i.User_2.Emoji,
			&i.User_2.CustomEmojiID,
			&i.User_2.EmojiJson,
			&i.ChatMember_2.ChatID,
			&i.ChatMember_2.UserID,
			&i.ChatMember_2.JoinedAt,
			&i.ChatMember_2.RestUntil,
			&i.ChatMember_2.Tag,
			&i.ChatMember_2.LeftAt,
			&i.ChatMember_2.RestReason,
			&i.ChatMember_2.Emoji,
			&i.ChatMember_2.Status,
			&i.ChatMember_2.EmojiJson,
			&i.ChatMember_2.ExcludeFromCall,
			&i.ID,
			&i.Type,
			&i.ChatID,
			&i.UserID,
			&i.ModeratorID,
			&i.Reason,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveWarnsByChat = `-- name: GetActiveWarnsByChat :many
SELECT um.id, um.username, um.first_name, um.last_name, um.created_at, um.gender, um.emoji, um.custom_emoji_id, um.emoji_json, cmm.chat_id, cmm.user_id, cmm.joined_at, cmm.rest_until, cmm.tag, cmm.left_at, cmm.rest_reason, cmm.emoji, cmm.status, cmm.emoji_json, cmm.exclude_from_call, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json, cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, cm.exclude_from_call, ma.id, ma.type, ma.chat_id, ma.user_id, ma.moderator_id, ma.reason, ma.created_at, ma.revoked_at, ma.expires_at
FROM moderation_actions ma
         JOIN chat_members cmm ON cmm.user_id = ma.moderator_id AND cmm.chat_id = ma.chat_id
         JOIN users um ON um.id = ma.moderator_id

         JOIN chat_members cm ON cm.user_id = ma.user_id AND cm.chat_id = ma.chat_id
         JOIN users u ON u.id = ma.user_id
WHERE ma.chat_id = $1
  AND ma.type = 'warn'
ORDER BY ma.created_at
`

type GetActiveWarnsByChatRow struct {
	User         User               `db:"user" json:"user"`
	ChatMember   ChatMember         `db:"chat_member" json:"chatMember"`
	User_2       User               `db:"user_2" json:"user2"`
	ChatMember_2 ChatMember         `db:"chat_member_2" json:"chatMember2"`
	ID           int64              `db:"id" json:"id"`
	Type         ModerationType     `db:"type" json:"type"`
	ChatID       int64              `db:"chat_id" json:"chatId"`
	UserID       int64              `db:"user_id" json:"userId"`
	ModeratorID  int64              `db:"moderator_id" json:"moderatorId"`
	Reason       pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revokedAt"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) GetActiveWarnsByChat(ctx context.Context, chatID int64) ([]GetActiveWarnsByChatRow, error) {
	rows, err := q.db.Query(ctx, getActiveWarnsByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveWarnsByChatRow{}
	for rows.Next() {
		var i GetActiveWarnsByChatRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
			&i.User_2.ID,
			&i.User_2.Username,
			&i.User_2.FirstName,
			&i.User_2.LastName,
			&i.User_2.CreatedAt,
			&i.User_2.Gender,
			&i.User_2.Emoji,
			&i.User_2.CustomEmojiID,
			&i.User_2.EmojiJson,
			&i.ChatMember_2.ChatID,
			&i.ChatMember_2.UserID,
			&i.ChatMember_2.JoinedAt,
			&i.ChatMember_2.RestUntil,
			&i.ChatMember_2.Tag,
			&i.ChatMember_2.LeftAt,
			&i.ChatMember_2.RestReason,
			&i.ChatMember_2.Emoji,
			&i.ChatMember_2.Status,
			&i.ChatMember_2.EmojiJson,
			&i.ChatMember_2.ExcludeFromCall,
			&i.ID,
			&i.Type,
			&i.ChatID,
			&i.UserID,
			&i.ModeratorID,
			&i.Reason,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveWarnsCount = `-- name: GetActiveWarnsCount :one
SELECT count(*)
FROM moderation_actions
WHERE chat_id = $1
  AND user_id = $2
  AND type = 'warn'
`

type GetActiveWarnsCountParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) GetActiveWarnsCount(ctx context.Context, arg GetActiveWarnsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveWarnsCount, arg.ChatID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChatMaxWarns = `-- name: GetChatMaxWarns :one
SELECT max_warns
FROM chats
WHERE id = $1
`

func (q *Queries) GetChatMaxWarns(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getChatMaxWarns, id)
	var max_warns int32
	err := row.Scan(&max_warns)
	return max_warns, err
}

const removeLatestWarn = `-- name: RemoveLatestWarn :exec
DELETE
FROM moderation_actions
WHERE id = (SELECT ma.id
            FROM moderation_actions ma
            WHERE ma.chat_id = $1
              AND ma.user_id = $2
              AND ma.type = 'warn'
            ORDER BY ma.created_at DESC
            LIMIT 1)
`

type RemoveLatestWarnParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) RemoveLatestWarn(ctx context.Context, arg RemoveLatestWarnParams) error {
	_, err := q.db.Exec(ctx, removeLatestWarn, arg.ChatID, arg.UserID)
	return err
}

const updateChatMaxWarns = `-- name: UpdateChatMaxWarns :exec
UPDATE chats
SET max_warns = $1
WHERE id = $2
`

type UpdateChatMaxWarnsParams struct {
	MaxWarns int32 `db:"max_warns" json:"maxWarns"`
	ID       int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateChatMaxWarns(ctx context.Context, arg UpdateChatMaxWarnsParams) error {
	_, err := q.db.Exec(ctx, updateChatMaxWarns, arg.MaxWarns, arg.ID)
	return err
}
