// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ModerationType string

const (
	ModerationTypeKick ModerationType = "kick"
	ModerationTypeMute ModerationType = "mute"
	ModerationTypeBan  ModerationType = "ban"
	ModerationTypeWarn ModerationType = "warn"
)

func (e *ModerationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationType(s)
	case string:
		*e = ModerationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationType: %T", src)
	}
	return nil
}

type NullModerationType struct {
	ModerationType ModerationType `json:"moderationType"`
	Valid          bool           `json:"valid"` // Valid is true if ModerationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationType) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationType), nil
}

type RestStatus string

const (
	RestStatusPending  RestStatus = "pending"
	RestStatusApproved RestStatus = "approved"
	RestStatusRejected RestStatus = "rejected"
)

func (e *RestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestStatus(s)
	case string:
		*e = RestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RestStatus: %T", src)
	}
	return nil
}

type NullRestStatus struct {
	RestStatus RestStatus `json:"restStatus"`
	Valid      bool       `json:"valid"` // Valid is true if RestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestStatus), nil
}

type BotDeveloper struct {
	UserID int64  `db:"user_id" json:"userId"`
	Role   string `db:"role" json:"role"`
	ChatID int64  `db:"chat_id" json:"chatId"`
}

type Chat struct {
	ID                  int64              `db:"id" json:"id"`
	NormWarn            pgtype.Int4        `db:"norm_warn" json:"normWarn"`
	NewbieThresholdDays int32              `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	AiSystemPrompt      pgtype.Text        `db:"ai_system_prompt" json:"aiSystemPrompt"`
	MaxLadder           int32              `db:"max_ladder" json:"maxLadder"`
	CallOnJoin          bool               `db:"call_on_join" json:"callOnJoin"`
	WelcomeCallMessage  pgtype.Text        `db:"welcome_call_message" json:"welcomeCallMessage"`
	WeekStartDay        int16              `db:"week_start_day" json:"weekStartDay"`
	MaxWarns            int32              `db:"max_warns" json:"maxWarns"`
	NormBan             pgtype.Int4        `db:"norm_ban" json:"normBan"`
	CommandPrefix       pgtype.Text        `db:"command_prefix" json:"commandPrefix"`
	AllowPrefixless     bool               `db:"allow_prefixless" json:"allowPrefixless"`
	MentionsPerMessage  int32              `db:"mentions_per_message" json:"mentionsPerMessage"`
	MentionTypes        int32              `db:"mention_types" json:"mentionTypes"`
	Title               string             `db:"title" json:"title"`
	TagsEnabled         bool               `db:"tags_enabled" json:"tagsEnabled"`
	WeekStartTime       pgtype.Time        `db:"week_start_time" json:"weekStartTime"`
	BroadcastEnabled    bool               `db:"broadcast_enabled" json:"broadcastEnabled"`
	BotRemovedAt        pgtype.Timestamptz `db:"bot_removed_at" json:"botRemovedAt"`
}

type ChatMember struct {
	ChatID     int64              `db:"chat_id" json:"chatId"`
	UserID     int64              `db:"user_id" json:"userId"`
	JoinedAt   pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	RestUntil  pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	Tag        pgtype.Text        `db:"tag" json:"tag"`
	LeftAt     pgtype.Timestamptz `db:"left_at" json:"leftAt"`
	RestReason pgtype.Text        `db:"rest_reason" json:"restReason"`
	Emoji      pgtype.Text        `db:"emoji" json:"emoji"`
	Status     int16              `db:"status" json:"status"`
}

type CommandPermission struct {
	ChatID         int64  `db:"chat_id" json:"chatId"`
	CommandKey     string `db:"command_key" json:"commandKey"`
	RequiredStatus int16  `db:"required_status" json:"requiredStatus"`
}

type Message struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ID        int64              `db:"id" json:"id"`
	MessageID pgtype.Int8        `db:"message_id" json:"messageId"`
}

type ModerationAction struct {
	ID          int64              `db:"id" json:"id"`
	Type        ModerationType     `db:"type" json:"type"`
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	ModeratorID int64              `db:"moderator_id" json:"moderatorId"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revokedAt"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}

type RestRequest struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	RequestedAt pgtype.Timestamptz `db:"requested_at" json:"requestedAt"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	Status      RestStatus         `db:"status" json:"status"`
	MessageID   pgtype.Int8        `db:"message_id" json:"messageId"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	ID          pgtype.Int8        `db:"id" json:"id"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID            int64              `db:"id" json:"id"`
	Username      pgtype.Text        `db:"username" json:"username"`
	FirstName     pgtype.Text        `db:"first_name" json:"firstName"`
	LastName      pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	Gender        string             `db:"gender" json:"gender"`
	Emoji         pgtype.Text        `db:"emoji" json:"emoji"`
	CustomEmojiID pgtype.Text        `db:"custom_emoji_id" json:"customEmojiId"`
}

type UserPmSession struct {
	UserID       int64              `db:"user_id" json:"userId"`
	TargetChatID int64              `db:"target_chat_id" json:"targetChatId"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
