// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RestStatus string

const (
	RestStatusPending  RestStatus = "pending"
	RestStatusApproved RestStatus = "approved"
	RestStatusRejected RestStatus = "rejected"
)

func (e *RestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestStatus(s)
	case string:
		*e = RestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RestStatus: %T", src)
	}
	return nil
}

type NullRestStatus struct {
	RestStatus RestStatus `json:"restStatus"`
	Valid      bool       `json:"valid"` // Valid is true if RestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestStatus), nil
}

type Chat struct {
	ID                  int64       `db:"id" json:"id"`
	WeeklyNorm          int32       `db:"weekly_norm" json:"weeklyNorm"`
	NewbieThresholdDays int32       `db:"newbie_threshold_days" json:"newbieThresholdDays"`
	AiSystemPrompt      pgtype.Text `db:"ai_system_prompt" json:"aiSystemPrompt"`
	MaxLadder           int32       `db:"max_ladder" json:"maxLadder"`
	CallOnJoin          bool        `db:"call_on_join" json:"callOnJoin"`
	WelcomeCallMessage  pgtype.Text `db:"welcome_call_message" json:"welcomeCallMessage"`
	WeekStartDay        int16       `db:"week_start_day" json:"weekStartDay"`
}

type ChatMember struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	CustomTitle pgtype.Text        `db:"custom_title" json:"customTitle"`
	Status      string             `db:"status" json:"status"`
	LeftAt      pgtype.Timestamptz `db:"left_at" json:"leftAt"`
}

type Message struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deletedAt"`
}

type RestRequest struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	RequestedAt pgtype.Timestamptz `db:"requested_at" json:"requestedAt"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	Status      RestStatus         `db:"status" json:"status"`
	MessageID   int64              `db:"message_id" json:"messageId"`
}

type User struct {
	ID        int64              `db:"id" json:"id"`
	Username  pgtype.Text        `db:"username" json:"username"`
	FirstName pgtype.Text        `db:"first_name" json:"firstName"`
	LastName  pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}
