// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ExemptStatus string

const (
	ExemptStatusPending  ExemptStatus = "pending"
	ExemptStatusApproved ExemptStatus = "approved"
	ExemptStatusRejected ExemptStatus = "rejected"
)

func (e *ExemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExemptStatus(s)
	case string:
		*e = ExemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExemptStatus: %T", src)
	}
	return nil
}

type NullExemptStatus struct {
	ExemptStatus ExemptStatus `json:"exemptStatus"`
	Valid        bool         `json:"valid"` // Valid is true if ExemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExemptStatus), nil
}

type Chat struct {
	ID         int64 `db:"id" json:"id"`
	WeeklyNorm int32 `db:"weekly_norm" json:"weeklyNorm"`
}

type ChatMember struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
}

type ExemptRequest struct {
	ChatID      int64              `db:"chat_id" json:"chatId"`
	UserID      int64              `db:"user_id" json:"userId"`
	RequestedAt pgtype.Timestamptz `db:"requested_at" json:"requestedAt"`
	ExemptUntil pgtype.Timestamptz `db:"exempt_until" json:"exemptUntil"`
	Status      ExemptStatus       `db:"status" json:"status"`
	MessageID   int64              `db:"message_id" json:"messageId"`
}

type Message struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deletedAt"`
}

type User struct {
	ID        int64              `db:"id" json:"id"`
	Username  pgtype.Text        `db:"username" json:"username"`
	FirstName pgtype.Text        `db:"first_name" json:"firstName"`
	LastName  pgtype.Text        `db:"last_name" json:"lastName"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}
