// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: norm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignNormMembers = `-- name: AssignNormMembers :exec
INSERT INTO chat_member_norms (norm_id, user_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT (norm_id, user_id) DO NOTHING
`

type AssignNormMembersParams struct {
	NormID  int64   `db:"norm_id" json:"normId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) AssignNormMembers(ctx context.Context, arg AssignNormMembersParams) error {
	_, err := q.db.Exec(ctx, assignNormMembers, arg.NormID, arg.UserIds)
	return err
}

const deleteNorm = `-- name: DeleteNorm :exec
DELETE
FROM chat_norms
WHERE id = $1
`

func (q *Queries) DeleteNorm(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNorm, id)
	return err
}

const getNorm = `-- name: GetNorm :one
SELECT id, chat_id, name, value
FROM chat_norms
WHERE chat_id = $1
  AND name ILIKE '%' || $2::text || '%'
LIMIT 1
`

type GetNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) GetNorm(ctx context.Context, arg GetNormParams) (ChatNorm, error) {
	row := q.db.QueryRow(ctx, getNorm, arg.ChatID, arg.Name)
	var i ChatNorm
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Value,
	)
	return i, err
}

const getNormByID = `-- name: GetNormByID :one
SELECT id, chat_id, name, value
FROM chat_norms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetNormByID(ctx context.Context, id int64) (ChatNorm, error) {
	row := q.db.QueryRow(ctx, getNormByID, id)
	var i ChatNorm
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Value,
	)
	return i, err
}

const getNormMembers = `-- name: GetNormMembers :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, cm.exclude_from_call, cm.description, cm.birthday, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json, u.is_bot, u.birthday
FROM chat_norms cn
         JOIN chat_member_norms cmn ON cmn.norm_id = cn.id
         JOIN chat_members cm ON cm.user_id = cmn.user_id AND cm.chat_id = cn.chat_id
         JOIN users u ON u.id = cm.user_id
WHERE cn.id = $1
`

type GetNormMembersRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetNormMembers(ctx context.Context, id int64) ([]GetNormMembersRow, error) {
	rows, err := q.db.Query(ctx, getNormMembers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNormMembersRow{}
	for rows.Next() {
		var i GetNormMembersRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
			&i.ChatMember.Description,
			&i.ChatMember.Birthday,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.User.IsBot,
			&i.User.Birthday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNorms = `-- name: ListNorms :many
SELECT id, chat_id, name, value
FROM chat_norms
WHERE chat_id = $1
`

func (q *Queries) ListNorms(ctx context.Context, chatID int64) ([]ChatNorm, error) {
	rows, err := q.db.Query(ctx, listNorms, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatNorm{}
	for rows.Next() {
		var i ChatNorm
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNormsWithMembers = `-- name: ListNormsWithMembers :many
SELECT n.id, n.chat_id, n.name, n.value,
       cmn.user_id
FROM chat_norms n
         LEFT JOIN chat_member_norms cmn
                   ON cmn.norm_id = n.id
WHERE n.chat_id = $1
ORDER BY n.id
`

type ListNormsWithMembersRow struct {
	ChatNorm ChatNorm    `db:"chat_norm" json:"chatNorm"`
	UserID   pgtype.Int8 `db:"user_id" json:"userId"`
}

func (q *Queries) ListNormsWithMembers(ctx context.Context, chatID int64) ([]ListNormsWithMembersRow, error) {
	rows, err := q.db.Query(ctx, listNormsWithMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNormsWithMembersRow{}
	for rows.Next() {
		var i ListNormsWithMembersRow
		if err := rows.Scan(
			&i.ChatNorm.ID,
			&i.ChatNorm.ChatID,
			&i.ChatNorm.Name,
			&i.ChatNorm.Value,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNorm = `-- name: SetNorm :one
INSERT INTO chat_norms(chat_id, name, value)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id, name) DO UPDATE SET value = $3
RETURNING id
`

type SetNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
	Value  int32  `db:"value" json:"value"`
}

func (q *Queries) SetNorm(ctx context.Context, arg SetNormParams) (int64, error) {
	row := q.db.QueryRow(ctx, setNorm, arg.ChatID, arg.Name, arg.Value)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const unassignNormMembers = `-- name: UnassignNormMembers :exec
DELETE
FROM chat_member_norms
WHERE norm_id = $1
  AND user_id = ANY ($2::bigint[])
`

type UnassignNormMembersParams struct {
	NormID  int64   `db:"norm_id" json:"normId"`
	UserIds []int64 `db:"user_ids" json:"userIds"`
}

func (q *Queries) UnassignNormMembers(ctx context.Context, arg UnassignNormMembersParams) error {
	_, err := q.db.Exec(ctx, unassignNormMembers, arg.NormID, arg.UserIds)
	return err
}
