// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: norm.sql

package db

import (
	"context"
)

const createNorm = `-- name: CreateNorm :exec
INSERT INTO chat_norms(chat_id, name, value)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id, name) DO UPDATE SET value = $3
`

type CreateNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
	Value  int32  `db:"value" json:"value"`
}

func (q *Queries) CreateNorm(ctx context.Context, arg CreateNormParams) error {
	_, err := q.db.Exec(ctx, createNorm, arg.ChatID, arg.Name, arg.Value)
	return err
}

const getNorm = `-- name: GetNorm :one
SELECT id, chat_id, name, value
FROM chat_norms
WHERE chat_id = $1
  AND name ILIKE '%' || $2::text || '%'
LIMIT 1
`

type GetNormParams struct {
	ChatID int64  `db:"chat_id" json:"chatId"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) GetNorm(ctx context.Context, arg GetNormParams) (ChatNorm, error) {
	row := q.db.QueryRow(ctx, getNorm, arg.ChatID, arg.Name)
	var i ChatNorm
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Value,
	)
	return i, err
}

const listNorms = `-- name: ListNorms :many
SELECT id, chat_id, name, value
FROM chat_norms
WHERE chat_id = $1
`

func (q *Queries) ListNorms(ctx context.Context, chatID int64) ([]ChatNorm, error) {
	rows, err := q.db.Query(ctx, listNorms, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatNorm{}
	for rows.Next() {
		var i ChatNorm
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
