// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChatAdmin(ctx context.Context, arg AddChatAdminParams) error
	AddRestRequest(ctx context.Context, arg AddRestRequestParams) error
	ApproveRestRequest(ctx context.Context, arg ApproveRestRequestParams) error
	ClearWarns(ctx context.Context, arg ClearWarnsParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) error
	DeleteChatMember(ctx context.Context, arg DeleteChatMemberParams) error
	DeleteModerationActionsForUser(ctx context.Context, arg DeleteModerationActionsForUserParams) error
	EndMemberRest(ctx context.Context, arg EndMemberRestParams) error
	EnsureChatExists(ctx context.Context, arg EnsureChatExistsParams) (EnsureChatExistsRow, error)
	EnsureChatMemberExists(ctx context.Context, arg EnsureChatMemberExistsParams) (ChatMember, error)
	EnsureDeveloperUser(ctx context.Context, id int64) error
	EnsureMemberFull(ctx context.Context, arg EnsureMemberFullParams) (ChatMember, error)
	EnsureUserExists(ctx context.Context, arg EnsureUserExistsParams) (User, error)
	GetActiveWarnsCount(ctx context.Context, arg GetActiveWarnsCountParams) (int64, error)
	GetAllDevelopers(ctx context.Context) ([]GetAllDevelopersRow, error)
	GetAnyChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetAnyChatMembersWithTitlesRow, error)
	GetChat(ctx context.Context, id int64) (Chat, error)
	GetChatAdmins(ctx context.Context, chatID int64) ([]GetChatAdminsRow, error)
	GetChatMaxLadder(ctx context.Context, chatID int64) (int32, error)
	GetChatMaxWarns(ctx context.Context, id int64) (int32, error)
	GetChatMember(ctx context.Context, arg GetChatMemberParams) (GetChatMemberRow, error)
	GetChatMemberStatus(ctx context.Context, arg GetChatMemberStatusParams) (string, error)
	GetChatMembers(ctx context.Context, chatID int64) ([]GetChatMembersRow, error)
	GetChatMembersWithTitles(ctx context.Context, chatID int64) ([]GetChatMembersWithTitlesRow, error)
	GetDeveloper(ctx context.Context, userID int64) (BotDeveloper, error)
	GetDevelopersCount(ctx context.Context) (int64, error)
	GetMemberCustomTitle(ctx context.Context, arg GetMemberCustomTitleParams) (pgtype.Text, error)
	GetOrCreateChat(ctx context.Context, arg GetOrCreateChatParams) (Chat, error)
	GetRestMembers(ctx context.Context, chatID int64) ([]GetRestMembersRow, error)
	GetRestRequest(ctx context.Context, arg GetRestRequestParams) (RestRequest, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	InactiveChatMembers(ctx context.Context, chatID int64) ([]InactiveChatMembersRow, error)
	IsChatAdmin(ctx context.Context, arg IsChatAdminParams) (bool, error)
	IsChatCreator(ctx context.Context, arg IsChatCreatorParams) (bool, error)
	IsDeveloper(ctx context.Context, userID int64) (bool, error)
	MarkChatMembersLeftNotInList(ctx context.Context, arg MarkChatMembersLeftNotInListParams) error
	MessageActivityByDay(ctx context.Context, arg MessageActivityByDayParams) ([]MessageActivityByDayRow, error)
	MessageReport(ctx context.Context, arg MessageReportParams) ([]MessageReportRow, error)
	MessageReportOne(ctx context.Context, arg MessageReportOneParams) (MessageReportOneRow, error)
	MoveChatMembersToNew(ctx context.Context, arg MoveChatMembersToNewParams) error
	MoveChatMembersToOldExcept(ctx context.Context, arg MoveChatMembersToOldExceptParams) error
	RejectRestRequest(ctx context.Context, arg RejectRestRequestParams) error
	RemoveChatAdmin(ctx context.Context, arg RemoveChatAdminParams) error
	RemoveDeveloper(ctx context.Context, userID int64) error
	RemoveLatestWarn(ctx context.Context, arg RemoveLatestWarnParams) error
	SetChatAISystemPrompt(ctx context.Context, arg SetChatAISystemPromptParams) error
	SetChatMaxLadder(ctx context.Context, arg SetChatMaxLadderParams) error
	SetChatWelcomeCallMessage(ctx context.Context, arg SetChatWelcomeCallMessageParams) error
	SetDeveloper(ctx context.Context, arg SetDeveloperParams) error
	SetMemberRest(ctx context.Context, arg SetMemberRestParams) error
	UpdateChatCallOnJoin(ctx context.Context, arg UpdateChatCallOnJoinParams) error
	UpdateChatMaxWarns(ctx context.Context, arg UpdateChatMaxWarnsParams) error
	UpdateChatMemberTitle(ctx context.Context, arg UpdateChatMemberTitleParams) error
	UpdateChatNewbieThreshold(ctx context.Context, arg UpdateChatNewbieThresholdParams) error
	UpdateChatNorm(ctx context.Context, arg UpdateChatNormParams) error
	UpdateChatWeekStartDay(ctx context.Context, arg UpdateChatWeekStartDayParams) error
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error
	UpsertChatMembers(ctx context.Context, arg UpsertChatMembersParams) error
	UpsertUsers(ctx context.Context, arg UpsertUsersParams) error
}

var _ Querier = (*Queries)(nil)
