// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddExemptRequest(ctx context.Context, arg AddExemptRequestParams) error
	ApproveExemptRequest(ctx context.Context, arg ApproveExemptRequestParams) error
	ChatExemptUsers(ctx context.Context, chatID int64) ([]ChatExemptUsersRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	EnsureChatExists(ctx context.Context, arg EnsureChatExistsParams) error
	EnsureChatMemberExists(ctx context.Context, arg EnsureChatMemberExistsParams) error
	EnsureUserExists(ctx context.Context, arg EnsureUserExistsParams) error
	ExemptChatMember(ctx context.Context, arg ExemptChatMemberParams) error
	GetChatMember(ctx context.Context, arg GetChatMemberParams) (ChatMember, error)
	GetExemptRequest(ctx context.Context, arg GetExemptRequestParams) (ExemptRequest, error)
	GetOrCreateChat(ctx context.Context, arg GetOrCreateChatParams) (Chat, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	RejectExemptRequest(ctx context.Context, arg RejectExemptRequestParams) error
	RemoveChatMemberExempt(ctx context.Context, arg RemoveChatMemberExemptParams) error
	UpdateChatNorm(ctx context.Context, arg UpdateChatNormParams) error
	WeeklyMessageReport(ctx context.Context, arg WeeklyMessageReportParams) ([]WeeklyMessageReportRow, error)
}

var _ Querier = (*Queries)(nil)
