// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rest.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRestRequest = `-- name: AddRestRequest :exec
INSERT INTO rest_requests(chat_id, user_id, rest_until, message_id)
VALUES ($1, $2, $3, $4)
`

type AddRestRequestParams struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	RestUntil pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	MessageID int64              `db:"message_id" json:"messageId"`
}

func (q *Queries) AddRestRequest(ctx context.Context, arg AddRestRequestParams) error {
	_, err := q.db.Exec(ctx, addRestRequest,
		arg.ChatID,
		arg.UserID,
		arg.RestUntil,
		arg.MessageID,
	)
	return err
}

const approveRestRequest = `-- name: ApproveRestRequest :exec
UPDATE rest_requests
SET status = 'approved'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type ApproveRestRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) ApproveRestRequest(ctx context.Context, arg ApproveRestRequestParams) error {
	_, err := q.db.Exec(ctx, approveRestRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const endMemberRest = `-- name: EndMemberRest :exec
UPDATE chat_members
SET rest_until = null
WHERE user_id = $1
  AND chat_id = $2
`

type EndMemberRestParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) EndMemberRest(ctx context.Context, arg EndMemberRestParams) error {
	_, err := q.db.Exec(ctx, endMemberRest, arg.UserID, arg.ChatID)
	return err
}

const getRestMembers = `-- name: GetRestMembers :many
SELECT cm.user_id,
       u.username,
       u.first_name,
       u.last_name,
       cm.rest_until,
       cm.status,
       cm.custom_title
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.rest_until IS NOT NULL
  AND cm.rest_until >= now()
ORDER BY cm.rest_until
`

type GetRestMembersRow struct {
	UserID      int64              `db:"user_id" json:"userId"`
	Username    pgtype.Text        `db:"username" json:"username"`
	FirstName   pgtype.Text        `db:"first_name" json:"firstName"`
	LastName    pgtype.Text        `db:"last_name" json:"lastName"`
	RestUntil   pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	Status      string             `db:"status" json:"status"`
	CustomTitle pgtype.Text        `db:"custom_title" json:"customTitle"`
}

func (q *Queries) GetRestMembers(ctx context.Context, chatID int64) ([]GetRestMembersRow, error) {
	rows, err := q.db.Query(ctx, getRestMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRestMembersRow{}
	for rows.Next() {
		var i GetRestMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.RestUntil,
			&i.Status,
			&i.CustomTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestRequest = `-- name: GetRestRequest :one
SELECT chat_id, user_id, requested_at, rest_until, status, message_id
FROM rest_requests
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type GetRestRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) GetRestRequest(ctx context.Context, arg GetRestRequestParams) (RestRequest, error) {
	row := q.db.QueryRow(ctx, getRestRequest, arg.ChatID, arg.UserID, arg.MessageID)
	var i RestRequest
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.RequestedAt,
		&i.RestUntil,
		&i.Status,
		&i.MessageID,
	)
	return i, err
}

const rejectRestRequest = `-- name: RejectRestRequest :exec
UPDATE rest_requests
SET status = 'rejected'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type RejectRestRequestParams struct {
	ChatID    int64 `db:"chat_id" json:"chatId"`
	UserID    int64 `db:"user_id" json:"userId"`
	MessageID int64 `db:"message_id" json:"messageId"`
}

func (q *Queries) RejectRestRequest(ctx context.Context, arg RejectRestRequestParams) error {
	_, err := q.db.Exec(ctx, rejectRestRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const setMemberRest = `-- name: SetMemberRest :exec
UPDATE chat_members
SET rest_until = $1
WHERE chat_id = $2
  AND user_id = $3
`

type SetMemberRestParams struct {
	RestUntil pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
}

func (q *Queries) SetMemberRest(ctx context.Context, arg SetMemberRestParams) error {
	_, err := q.db.Exec(ctx, setMemberRest, arg.RestUntil, arg.ChatID, arg.UserID)
	return err
}
