// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: rest.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRestRequest = `-- name: AddRestRequest :exec
INSERT INTO rest_requests(chat_id, user_id, rest_until, message_id, reason, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddRestRequestParams struct {
	ChatID    int64              `db:"chat_id" json:"chatId"`
	UserID    int64              `db:"user_id" json:"userId"`
	RestUntil pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	MessageID pgtype.Int8        `db:"message_id" json:"messageId"`
	Reason    pgtype.Text        `db:"reason" json:"reason"`
	Status    RestStatus         `db:"status" json:"status"`
}

func (q *Queries) AddRestRequest(ctx context.Context, arg AddRestRequestParams) error {
	_, err := q.db.Exec(ctx, addRestRequest,
		arg.ChatID,
		arg.UserID,
		arg.RestUntil,
		arg.MessageID,
		arg.Reason,
		arg.Status,
	)
	return err
}

const approveRestRequest = `-- name: ApproveRestRequest :exec
UPDATE rest_requests
SET status = 'approved'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type ApproveRestRequestParams struct {
	ChatID    int64       `db:"chat_id" json:"chatId"`
	UserID    int64       `db:"user_id" json:"userId"`
	MessageID pgtype.Int8 `db:"message_id" json:"messageId"`
}

func (q *Queries) ApproveRestRequest(ctx context.Context, arg ApproveRestRequestParams) error {
	_, err := q.db.Exec(ctx, approveRestRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const deleteRestRequest = `-- name: DeleteRestRequest :exec
DELETE
FROM rest_requests
WHERE id = $1
`

func (q *Queries) DeleteRestRequest(ctx context.Context, id pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteRestRequest, id)
	return err
}

const endMemberRest = `-- name: EndMemberRest :exec
UPDATE chat_members
SET rest_until = null
WHERE user_id = $1
  AND chat_id = $2
`

type EndMemberRestParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

func (q *Queries) EndMemberRest(ctx context.Context, arg EndMemberRestParams) error {
	_, err := q.db.Exec(ctx, endMemberRest, arg.UserID, arg.ChatID)
	return err
}

const getAllActiveRests = `-- name: GetAllActiveRests :many
SELECT chat_id, user_id, rest_until, rest_reason
FROM chat_members
WHERE rest_until IS NOT NULL
  AND rest_until >= now()
`

type GetAllActiveRestsRow struct {
	ChatID     int64              `db:"chat_id" json:"chatId"`
	UserID     int64              `db:"user_id" json:"userId"`
	RestUntil  pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	RestReason pgtype.Text        `db:"rest_reason" json:"restReason"`
}

func (q *Queries) GetAllActiveRests(ctx context.Context) ([]GetAllActiveRestsRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveRests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllActiveRestsRow{}
	for rows.Next() {
		var i GetAllActiveRestsRow
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.RestUntil,
			&i.RestReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestMembers = `-- name: GetRestMembers :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, cm.exclude_from_call, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json
FROM chat_members cm
         JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
  AND cm.left_at IS NULL
  AND cm.rest_until IS NOT NULL
  AND cm.rest_until >= now()
ORDER BY cm.rest_until
`

type GetRestMembersRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetRestMembers(ctx context.Context, chatID int64) ([]GetRestMembersRow, error) {
	rows, err := q.db.Query(ctx, getRestMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRestMembersRow{}
	for rows.Next() {
		var i GetRestMembersRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestRequest = `-- name: GetRestRequest :one
SELECT chat_id, user_id, requested_at, rest_until, status, message_id, reason, id, updated_at
FROM rest_requests
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type GetRestRequestParams struct {
	ChatID    int64       `db:"chat_id" json:"chatId"`
	UserID    int64       `db:"user_id" json:"userId"`
	MessageID pgtype.Int8 `db:"message_id" json:"messageId"`
}

func (q *Queries) GetRestRequest(ctx context.Context, arg GetRestRequestParams) (RestRequest, error) {
	row := q.db.QueryRow(ctx, getRestRequest, arg.ChatID, arg.UserID, arg.MessageID)
	var i RestRequest
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.RequestedAt,
		&i.RestUntil,
		&i.Status,
		&i.MessageID,
		&i.Reason,
		&i.ID,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRestRequests = `-- name: GetUserRestRequests :many
SELECT rr.chat_id, rr.user_id, rr.requested_at, rr.rest_until, rr.status, rr.message_id, rr.reason, rr.id, rr.updated_at, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id, u.emoji_json, cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.left_at, cm.rest_reason, cm.emoji, cm.status, cm.emoji_json, cm.exclude_from_call
FROM rest_requests rr
         JOIN users u ON u.id = rr.user_id
         JOIN chat_members cm ON cm.user_id = u.id AND cm.chat_id = rr.chat_id
WHERE rr.user_id = $1
  AND rr.chat_id = $2
ORDER BY rr.requested_at DESC
`

type GetUserRestRequestsParams struct {
	UserID int64 `db:"user_id" json:"userId"`
	ChatID int64 `db:"chat_id" json:"chatId"`
}

type GetUserRestRequestsRow struct {
	RestRequest RestRequest `db:"rest_request" json:"restRequest"`
	User        User        `db:"user" json:"user"`
	ChatMember  ChatMember  `db:"chat_member" json:"chatMember"`
}

func (q *Queries) GetUserRestRequests(ctx context.Context, arg GetUserRestRequestsParams) ([]GetUserRestRequestsRow, error) {
	rows, err := q.db.Query(ctx, getUserRestRequests, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRestRequestsRow{}
	for rows.Next() {
		var i GetUserRestRequestsRow
		if err := rows.Scan(
			&i.RestRequest.ChatID,
			&i.RestRequest.UserID,
			&i.RestRequest.RequestedAt,
			&i.RestRequest.RestUntil,
			&i.RestRequest.Status,
			&i.RestRequest.MessageID,
			&i.RestRequest.Reason,
			&i.RestRequest.ID,
			&i.RestRequest.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
			&i.User.EmojiJson,
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.ChatMember.Status,
			&i.ChatMember.EmojiJson,
			&i.ChatMember.ExcludeFromCall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRestRequest = `-- name: RejectRestRequest :exec
UPDATE rest_requests
SET status = 'rejected'
WHERE chat_id = $1
  AND user_id = $2
  AND message_id = $3
`

type RejectRestRequestParams struct {
	ChatID    int64       `db:"chat_id" json:"chatId"`
	UserID    int64       `db:"user_id" json:"userId"`
	MessageID pgtype.Int8 `db:"message_id" json:"messageId"`
}

func (q *Queries) RejectRestRequest(ctx context.Context, arg RejectRestRequestParams) error {
	_, err := q.db.Exec(ctx, rejectRestRequest, arg.ChatID, arg.UserID, arg.MessageID)
	return err
}

const setMemberRest = `-- name: SetMemberRest :exec
UPDATE chat_members
SET rest_until  = $1,
    rest_reason = $2
WHERE chat_id = $3
  AND user_id = $4
`

type SetMemberRestParams struct {
	RestUntil  pgtype.Timestamptz `db:"rest_until" json:"restUntil"`
	RestReason pgtype.Text        `db:"rest_reason" json:"restReason"`
	ChatID     int64              `db:"chat_id" json:"chatId"`
	UserID     int64              `db:"user_id" json:"userId"`
}

func (q *Queries) SetMemberRest(ctx context.Context, arg SetMemberRestParams) error {
	_, err := q.db.Exec(ctx, setMemberRest,
		arg.RestUntil,
		arg.RestReason,
		arg.ChatID,
		arg.UserID,
	)
	return err
}
