// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reward.sql

package db

import (
	"context"
)

const addReward = `-- name: AddReward :exec
INSERT INTO rewards(chat_id, user_id, author_id, rank, reason)
VALUES ($1, $2, $3, $4, $5)
`

type AddRewardParams struct {
	ChatID   int64  `db:"chat_id" json:"chatId"`
	UserID   int64  `db:"user_id" json:"userId"`
	AuthorID int64  `db:"author_id" json:"authorId"`
	Rank     int16  `db:"rank" json:"rank"`
	Reason   string `db:"reason" json:"reason"`
}

func (q *Queries) AddReward(ctx context.Context, arg AddRewardParams) error {
	_, err := q.db.Exec(ctx, addReward,
		arg.ChatID,
		arg.UserID,
		arg.AuthorID,
		arg.Rank,
		arg.Reason,
	)
	return err
}

const listUserRewards = `-- name: ListUserRewards :many
SELECT id, chat_id, user_id, author_id, rank, reason, created_at
FROM rewards
WHERE chat_id = $1
  AND user_id = $2
ORDER BY created_at
`

type ListUserRewardsParams struct {
	ChatID int64 `db:"chat_id" json:"chatId"`
	UserID int64 `db:"user_id" json:"userId"`
}

func (q *Queries) ListUserRewards(ctx context.Context, arg ListUserRewardsParams) ([]Reward, error) {
	rows, err := q.db.Query(ctx, listUserRewards, arg.ChatID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reward{}
	for rows.Next() {
		var i Reward
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.AuthorID,
			&i.Rank,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReward = `-- name: RemoveReward :exec
DELETE
FROM rewards
WHERE id = $1
`

func (q *Queries) RemoveReward(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeReward, id)
	return err
}
