// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: rp_command.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRPCommand = `-- name: DeleteRPCommand :exec
DELETE
FROM chat_rp_commands
WHERE chat_id = $1
  AND trigger_normalized = $2
`

type DeleteRPCommandParams struct {
	ChatID            int64  `db:"chat_id" json:"chatId"`
	TriggerNormalized string `db:"trigger_normalized" json:"triggerNormalized"`
}

func (q *Queries) DeleteRPCommand(ctx context.Context, arg DeleteRPCommandParams) error {
	_, err := q.db.Exec(ctx, deleteRPCommand, arg.ChatID, arg.TriggerNormalized)
	return err
}

const getRPCommandByTrigger = `-- name: GetRPCommandByTrigger :one
SELECT chat_id, trigger, trigger_normalized, template, emoji_json, created_by, created_at, updated_at
FROM chat_rp_commands
WHERE chat_id = $1
  AND trigger_normalized = $2
`

type GetRPCommandByTriggerParams struct {
	ChatID            int64  `db:"chat_id" json:"chatId"`
	TriggerNormalized string `db:"trigger_normalized" json:"triggerNormalized"`
}

func (q *Queries) GetRPCommandByTrigger(ctx context.Context, arg GetRPCommandByTriggerParams) (ChatRpCommand, error) {
	row := q.db.QueryRow(ctx, getRPCommandByTrigger, arg.ChatID, arg.TriggerNormalized)
	var i ChatRpCommand
	err := row.Scan(
		&i.ChatID,
		&i.Trigger,
		&i.TriggerNormalized,
		&i.Template,
		&i.EmojiJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRPCommandsByChat = `-- name: ListRPCommandsByChat :many
SELECT chat_id, trigger, trigger_normalized, template, emoji_json, created_by, created_at, updated_at
FROM chat_rp_commands
WHERE chat_id = $1
ORDER BY trigger
`

func (q *Queries) ListRPCommandsByChat(ctx context.Context, chatID int64) ([]ChatRpCommand, error) {
	rows, err := q.db.Query(ctx, listRPCommandsByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRpCommand{}
	for rows.Next() {
		var i ChatRpCommand
		if err := rows.Scan(
			&i.ChatID,
			&i.Trigger,
			&i.TriggerNormalized,
			&i.Template,
			&i.EmojiJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRPCommand = `-- name: UpsertRPCommand :exec
INSERT INTO chat_rp_commands (chat_id, trigger, trigger_normalized, template, emoji_json, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (chat_id, trigger_normalized) DO UPDATE
    SET trigger    = EXCLUDED.trigger,
        template   = EXCLUDED.template,
        emoji_json = EXCLUDED.emoji_json,
        updated_at = now()
`

type UpsertRPCommandParams struct {
	ChatID            int64       `db:"chat_id" json:"chatId"`
	Trigger           string      `db:"trigger" json:"trigger"`
	TriggerNormalized string      `db:"trigger_normalized" json:"triggerNormalized"`
	Template          pgtype.Text `db:"template" json:"template"`
	EmojiJson         []byte      `db:"emoji_json" json:"emojiJson"`
	CreatedBy         int64       `db:"created_by" json:"createdBy"`
}

func (q *Queries) UpsertRPCommand(ctx context.Context, arg UpsertRPCommandParams) error {
	_, err := q.db.Exec(ctx, upsertRPCommand,
		arg.ChatID,
		arg.Trigger,
		arg.TriggerNormalized,
		arg.Template,
		arg.EmojiJson,
		arg.CreatedBy,
	)
	return err
}
