// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rp_command.sql

package db

import (
	"context"
)

const deleteRPCommand = `-- name: DeleteRPCommand :exec
DELETE
FROM chat_rp_commands
WHERE chat_id = $1
  AND trigger = $2
`

type DeleteRPCommandParams struct {
	ChatID  int64  `db:"chat_id" json:"chatId"`
	Trigger string `db:"trigger" json:"trigger"`
}

func (q *Queries) DeleteRPCommand(ctx context.Context, arg DeleteRPCommandParams) error {
	_, err := q.db.Exec(ctx, deleteRPCommand, arg.ChatID, arg.Trigger)
	return err
}

const getRPCommandByTrigger = `-- name: GetRPCommandByTrigger :one
SELECT id, chat_id, trigger, action, emojis, created_by, created_at, updated_at
FROM chat_rp_commands
WHERE chat_id = $1
  AND trigger = $2
`

type GetRPCommandByTriggerParams struct {
	ChatID  int64  `db:"chat_id" json:"chatId"`
	Trigger string `db:"trigger" json:"trigger"`
}

func (q *Queries) GetRPCommandByTrigger(ctx context.Context, arg GetRPCommandByTriggerParams) (ChatRpCommand, error) {
	row := q.db.QueryRow(ctx, getRPCommandByTrigger, arg.ChatID, arg.Trigger)
	var i ChatRpCommand
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Trigger,
		&i.Action,
		&i.Emojis,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRPCommandsByChat = `-- name: ListRPCommandsByChat :many
SELECT id, chat_id, trigger, action, emojis, created_by, created_at, updated_at
FROM chat_rp_commands
WHERE chat_id = $1
ORDER BY trigger
`

func (q *Queries) ListRPCommandsByChat(ctx context.Context, chatID int64) ([]ChatRpCommand, error) {
	rows, err := q.db.Query(ctx, listRPCommandsByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRpCommand{}
	for rows.Next() {
		var i ChatRpCommand
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Trigger,
			&i.Action,
			&i.Emojis,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRPCommand = `-- name: UpsertRPCommand :exec
INSERT INTO chat_rp_commands (chat_id, trigger, action, emojis, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chat_id, trigger) DO UPDATE
    SET action     = EXCLUDED.action,
        emojis     = EXCLUDED.emojis,
        updated_at = now()
`

type UpsertRPCommandParams struct {
	ChatID    int64  `db:"chat_id" json:"chatId"`
	Trigger   string `db:"trigger" json:"trigger"`
	Action    string `db:"action" json:"action"`
	Emojis    string `db:"emojis" json:"emojis"`
	CreatedBy int64  `db:"created_by" json:"createdBy"`
}

func (q *Queries) UpsertRPCommand(ctx context.Context, arg UpsertRPCommandParams) error {
	_, err := q.db.Exec(ctx, upsertRPCommand,
		arg.ChatID,
		arg.Trigger,
		arg.Action,
		arg.Emojis,
		arg.CreatedBy,
	)
	return err
}
