// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: session.sql

package db

import (
	"context"
)

const deletePMSession = `-- name: DeletePMSession :exec
DELETE FROM user_pm_sessions
WHERE user_id = $1
`

func (q *Queries) DeletePMSession(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePMSession, userID)
	return err
}

const getChatPMSession = `-- name: GetChatPMSession :one
SELECT c.id, c.norm_warn, c.newbie_threshold_days, c.ai_system_prompt, c.max_ladder, c.call_on_join, c.welcome_call_message, c.week_start_day, c.max_warns, c.norm_ban, c.command_prefix, c.allow_prefixless, c.mentions_per_message, c.mention_types, c.title, c.tags_enabled, c.week_start_time, c.broadcast_enabled, c.removed_at
FROM user_pm_sessions
JOIN chats c ON c.id = target_chat_id
WHERE user_id = $1 LIMIT 1
`

type GetChatPMSessionRow struct {
	Chat Chat `db:"chat" json:"chat"`
}

func (q *Queries) GetChatPMSession(ctx context.Context, userID int64) (GetChatPMSessionRow, error) {
	row := q.db.QueryRow(ctx, getChatPMSession, userID)
	var i GetChatPMSessionRow
	err := row.Scan(
		&i.Chat.ID,
		&i.Chat.NormWarn,
		&i.Chat.NewbieThresholdDays,
		&i.Chat.AiSystemPrompt,
		&i.Chat.MaxLadder,
		&i.Chat.CallOnJoin,
		&i.Chat.WelcomeCallMessage,
		&i.Chat.WeekStartDay,
		&i.Chat.MaxWarns,
		&i.Chat.NormBan,
		&i.Chat.CommandPrefix,
		&i.Chat.AllowPrefixless,
		&i.Chat.MentionsPerMessage,
		&i.Chat.MentionTypes,
		&i.Chat.Title,
		&i.Chat.TagsEnabled,
		&i.Chat.WeekStartTime,
		&i.Chat.BroadcastEnabled,
		&i.Chat.RemovedAt,
	)
	return i, err
}

const getPMSession = `-- name: GetPMSession :one
SELECT target_chat_id
FROM user_pm_sessions
WHERE user_id = $1
`

func (q *Queries) GetPMSession(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPMSession, userID)
	var target_chat_id int64
	err := row.Scan(&target_chat_id)
	return target_chat_id, err
}

const upsertPMSession = `-- name: UpsertPMSession :exec
INSERT INTO user_pm_sessions (user_id, target_chat_id, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id) DO UPDATE
SET target_chat_id = EXCLUDED.target_chat_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertPMSessionParams struct {
	UserID       int64 `db:"user_id" json:"userId"`
	TargetChatID int64 `db:"target_chat_id" json:"targetChatId"`
}

func (q *Queries) UpsertPMSession(ctx context.Context, arg UpsertPMSessionParams) error {
	_, err := q.db.Exec(ctx, upsertPMSession, arg.UserID, arg.TargetChatID)
	return err
}
