// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
)

const deletePMSession = `-- name: DeletePMSession :exec
DELETE FROM user_pm_sessions
WHERE user_id = $1
`

func (q *Queries) DeletePMSession(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePMSession, userID)
	return err
}

const getPMSession = `-- name: GetPMSession :one
SELECT target_chat_id
FROM user_pm_sessions
WHERE user_id = $1
`

func (q *Queries) GetPMSession(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPMSession, userID)
	var target_chat_id int64
	err := row.Scan(&target_chat_id)
	return target_chat_id, err
}

const upsertPMSession = `-- name: UpsertPMSession :exec
INSERT INTO user_pm_sessions (user_id, target_chat_id, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id) DO UPDATE
SET target_chat_id = EXCLUDED.target_chat_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertPMSessionParams struct {
	UserID       int64 `db:"user_id" json:"userId"`
	TargetChatID int64 `db:"target_chat_id" json:"targetChatId"`
}

func (q *Queries) UpsertPMSession(ctx context.Context, arg UpsertPMSessionParams) error {
	_, err := q.db.Exec(ctx, upsertPMSession, arg.UserID, arg.TargetChatID)
	return err
}
