// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tag.sql

package db

import (
	"context"
)

const setChatTagsEnabled = `-- name: SetChatTagsEnabled :exec
UPDATE chats
SET tags_enabled = $1
WHERE id = $2
`

type SetChatTagsEnabledParams struct {
	TagsEnabled bool  `db:"tags_enabled" json:"tagsEnabled"`
	ID          int64 `db:"id" json:"id"`
}

func (q *Queries) SetChatTagsEnabled(ctx context.Context, arg SetChatTagsEnabledParams) error {
	_, err := q.db.Exec(ctx, setChatTagsEnabled, arg.TagsEnabled, arg.ID)
	return err
}
