// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureUserExists = `-- name: EnsureUserExists :one
INSERT INTO users(id, username, first_name, last_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET username   = $2,
                               first_name = $3,
                               last_name  = $4
RETURNING id, username, first_name, last_name, created_at, gender, emoji, custom_emoji_id
`

type EnsureUserExistsParams struct {
	ID        int64       `db:"id" json:"id"`
	Username  pgtype.Text `db:"username" json:"username"`
	FirstName pgtype.Text `db:"first_name" json:"firstName"`
	LastName  pgtype.Text `db:"last_name" json:"lastName"`
}

func (q *Queries) EnsureUserExists(ctx context.Context, arg EnsureUserExistsParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureUserExists,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Gender,
		&i.Emoji,
		&i.CustomEmojiID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, first_name, last_name, created_at, gender, emoji, custom_emoji_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Gender,
		&i.Emoji,
		&i.CustomEmojiID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, first_name, last_name, created_at, gender, emoji, custom_emoji_id
FROM users
WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Gender,
		&i.Emoji,
		&i.CustomEmojiID,
	)
	return i, err
}

const getUsersByCustomTitle = `-- name: GetUsersByCustomTitle :many
SELECT cm.chat_id, cm.user_id, cm.joined_at, cm.rest_until, cm.tag, cm.status, cm.left_at, cm.rest_reason, cm.emoji, u.id, u.username, u.first_name, u.last_name, u.created_at, u.gender, u.emoji, u.custom_emoji_id
FROM chat_members cm
         JOIN users u ON cm.user_id = u.id
WHERE cm.tag ILIKE '%' || $1 || '%'
  AND cm.chat_id = $2
LIMIT 10
`

type GetUsersByCustomTitleParams struct {
	Tag    pgtype.Text `db:"tag" json:"tag"`
	ChatID int64       `db:"chat_id" json:"chatId"`
}

type GetUsersByCustomTitleRow struct {
	ChatMember ChatMember `db:"chat_member" json:"chatMember"`
	User       User       `db:"user" json:"user"`
}

func (q *Queries) GetUsersByCustomTitle(ctx context.Context, arg GetUsersByCustomTitleParams) ([]GetUsersByCustomTitleRow, error) {
	rows, err := q.db.Query(ctx, getUsersByCustomTitle, arg.Tag, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByCustomTitleRow{}
	for rows.Next() {
		var i GetUsersByCustomTitleRow
		if err := rows.Scan(
			&i.ChatMember.ChatID,
			&i.ChatMember.UserID,
			&i.ChatMember.JoinedAt,
			&i.ChatMember.RestUntil,
			&i.ChatMember.Tag,
			&i.ChatMember.Status,
			&i.ChatMember.LeftAt,
			&i.ChatMember.RestReason,
			&i.ChatMember.Emoji,
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.CreatedAt,
			&i.User.Gender,
			&i.User.Emoji,
			&i.User.CustomEmojiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCustomEmojiID = `-- name: SetUserCustomEmojiID :exec
UPDATE users SET custom_emoji_id = $2 WHERE id = $1
`

type SetUserCustomEmojiIDParams struct {
	ID            int64       `db:"id" json:"id"`
	CustomEmojiID pgtype.Text `db:"custom_emoji_id" json:"customEmojiId"`
}

func (q *Queries) SetUserCustomEmojiID(ctx context.Context, arg SetUserCustomEmojiIDParams) error {
	_, err := q.db.Exec(ctx, setUserCustomEmojiID, arg.ID, arg.CustomEmojiID)
	return err
}

const setUserEmoji = `-- name: SetUserEmoji :exec
UPDATE users SET emoji = $2 WHERE id = $1
`

type SetUserEmojiParams struct {
	ID    int64       `db:"id" json:"id"`
	Emoji pgtype.Text `db:"emoji" json:"emoji"`
}

func (q *Queries) SetUserEmoji(ctx context.Context, arg SetUserEmojiParams) error {
	_, err := q.db.Exec(ctx, setUserEmoji, arg.ID, arg.Emoji)
	return err
}

const setUserGender = `-- name: SetUserGender :exec
UPDATE users SET gender = $2 WHERE id = $1
`

type SetUserGenderParams struct {
	ID     int64  `db:"id" json:"id"`
	Gender string `db:"gender" json:"gender"`
}

func (q *Queries) SetUserGender(ctx context.Context, arg SetUserGenderParams) error {
	_, err := q.db.Exec(ctx, setUserGender, arg.ID, arg.Gender)
	return err
}

const upsertUsers = `-- name: UpsertUsers :exec
INSERT INTO users(id, username, first_name, last_name)
SELECT unnest($1::bigint[]),
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::text[])
ON CONFLICT (id) DO UPDATE SET username   = EXCLUDED.username,
                               first_name = EXCLUDED.first_name,
                               last_name  = EXCLUDED.last_name
`

type UpsertUsersParams struct {
	Ids        []int64  `db:"ids" json:"ids"`
	Usernames  []string `db:"usernames" json:"usernames"`
	FirstNames []string `db:"first_names" json:"firstNames"`
	LastNames  []string `db:"last_names" json:"lastNames"`
}

func (q *Queries) UpsertUsers(ctx context.Context, arg UpsertUsersParams) error {
	_, err := q.db.Exec(ctx, upsertUsers,
		arg.Ids,
		arg.Usernames,
		arg.FirstNames,
		arg.LastNames,
	)
	return err
}
