// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: words.sql

package db

import (
	"context"
)

const getRandomCrocodileWord = `-- name: GetRandomCrocodileWord :one
SELECT id, word, category, difficulty, used_count, created_at, last_used_at
FROM crocodile_words
WHERE last_used_at IS NULL
   OR last_used_at < NOW() - INTERVAL '7 days'
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomCrocodileWord(ctx context.Context) (CrocodileWord, error) {
	row := q.db.QueryRow(ctx, getRandomCrocodileWord)
	var i CrocodileWord
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Category,
		&i.Difficulty,
		&i.UsedCount,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertCrocodileWord = `-- name: InsertCrocodileWord :exec
INSERT INTO crocodile_words (word)
VALUES ($1)
ON CONFLICT(word) DO NOTHING
`

func (q *Queries) InsertCrocodileWord(ctx context.Context, word string) error {
	_, err := q.db.Exec(ctx, insertCrocodileWord, word)
	return err
}

const markCrocodileWordUsed = `-- name: MarkCrocodileWordUsed :exec
UPDATE crocodile_words
SET
    used_count = used_count + 1,
    last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkCrocodileWordUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markCrocodileWordUsed, id)
	return err
}
