// Code generated by go generate; DO NOT EDIT.

package i18n

type MessageID string

var (
	ArgType = struct {
		Datetime MessageID
		Duration MessageID
		Number   MessageID
		Text     MessageID
		User     MessageID
	}{
		Datetime: "arg_type.datetime",
		Duration: "arg_type.duration",
		Number:   "arg_type.number",
		Text:     "arg_type.text",
		User:     "arg_type.user",
	}
	Category = struct {
		Help       MessageID
		Moderation MessageID
		Norm       MessageID
		Rest       MessageID
		Stats      MessageID
		Summon     MessageID
	}{
		Help:       "category.help",
		Moderation: "category.moderation",
		Norm:       "category.norm",
		Rest:       "category.rest",
		Stats:      "category.stats",
		Summon:     "category.summon",
	}
	Cmd = struct {
		AddNorm struct {
			Added           MessageID
			Desc            MessageID
			ErrInvalidValue MessageID
			ExampleNamed    MessageID
			ExampleSimple   MessageID
			ExampleUsers    MessageID
			NormGeneral     MessageID
		}
		AssignNorm struct {
			Assigned MessageID
			Desc     MessageID
			Example  MessageID
			NoUsers  MessageID
		}
		DeleteNorm struct {
			Deleted            MessageID
			Desc               MessageID
			ErrNothingToDelete MessageID
			Example            MessageID
		}
		EndRest struct {
			Desc          MessageID
			Ended         MessageID
			EndedSelf     MessageID
			NotInRest     MessageID
			NotInRestSelf MessageID
		}
		Help struct {
			AliasesLabel MessageID
			Body         MessageID
			Desc         MessageID
			Examples     MessageID
			Syntax       MessageID
		}
		HelpCommand struct {
			Desc MessageID
		}
		ListNorms struct {
			Desc  MessageID
			Empty MessageID
			Item  MessageID
			Title MessageID
		}
		Moderation struct {
			SetRole struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}
			SetRoleAdmin struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}
		}
		Profile struct {
			Activity        MessageID
			Desc            MessageID
			ExampleDate     MessageID
			ExampleDuration MessageID
			MemberPeriod    MessageID
			MemberSince     MessageID
			NormFailed      MessageID
			NormPassed      MessageID
			RestExempt      MessageID
			RestUntil       MessageID
			Title           MessageID
			TotalMessages   MessageID
		}
		Rest struct {
			Desc       MessageID
			Info       MessageID
			InfoReason MessageID
			NoRest     MessageID
			Set        MessageID
			SetReason  MessageID
		}
		RestRequest struct {
			ApproveButton MessageID
			Approved      MessageID
			ApprovedShort MessageID
			Created       MessageID
			Empty         MessageID
			Item          MessageID
			NoRequest     MessageID
			RejectButton  MessageID
			Rejected      MessageID
			Text          MessageID
			TextReason    MessageID
			Title         MessageID
		}
		Rests struct {
			Delete struct {
				Deleted       MessageID
				DeletedActive MessageID
				Desc          MessageID
			}
			Desc              MessageID
			HistoryEmpty      MessageID
			HistoryItem       MessageID
			HistoryItemReason MessageID
			HistoryTitle      MessageID
			HistoryTotal      MessageID
		}
		ShowNorm struct {
			AllMembers MessageID
			Body       MessageID
			Desc       MessageID
			Example    MessageID
			Members    MessageID
			NotFound   MessageID
		}
		Stats struct {
			Desc            MessageID
			ExampleDate     MessageID
			ExampleDuration MessageID
			Failed          MessageID
			NormTitle       MessageID
			Passed          MessageID
			Title           MessageID
			TotalMessages   MessageID
			UserFailed      MessageID
			UserPassed      MessageID
		}
		Summon struct {
			AlreadyRunning MessageID
			Completed      MessageID
			Confirm        struct {
				Canceled             MessageID
				Disabled             MessageID
				No                   MessageID
				OnlyInitiatorCancel  MessageID
				OnlyInitiatorConfirm MessageID
				Text                 MessageID
				Yes                  MessageID
				YesAndDisable        MessageID
			}
			Desc MessageID
			Reg  struct {
				Desc MessageID
				Set  MessageID
			}
			Style struct {
				Desc   MessageID
				Emoji  MessageID
				Name   MessageID
				Role   MessageID
				Text   MessageID
				Toggle struct {
					Desc MessageID
				}
			}
			Unreg struct {
				Desc MessageID
				Set  MessageID
			}
		}
		UnassignNorm struct {
			Desc       MessageID
			Example    MessageID
			NoUsers    MessageID
			Unassigned MessageID
		}
	}{
		AddNorm: struct {
			Added           MessageID
			Desc            MessageID
			ErrInvalidValue MessageID
			ExampleNamed    MessageID
			ExampleSimple   MessageID
			ExampleUsers    MessageID
			NormGeneral     MessageID
		}{
			Added:           "cmd.add_norm.added",
			Desc:            "cmd.add_norm.desc",
			ErrInvalidValue: "cmd.add_norm.err_invalid_value",
			ExampleNamed:    "cmd.add_norm.example_named",
			ExampleSimple:   "cmd.add_norm.example_simple",
			ExampleUsers:    "cmd.add_norm.example_users",
			NormGeneral:     "cmd.add_norm.norm_general",
		},
		AssignNorm: struct {
			Assigned MessageID
			Desc     MessageID
			Example  MessageID
			NoUsers  MessageID
		}{
			Assigned: "cmd.assign_norm.assigned",
			Desc:     "cmd.assign_norm.desc",
			Example:  "cmd.assign_norm.example",
			NoUsers:  "cmd.assign_norm.no_users",
		},
		DeleteNorm: struct {
			Deleted            MessageID
			Desc               MessageID
			ErrNothingToDelete MessageID
			Example            MessageID
		}{
			Deleted:            "cmd.delete_norm.deleted",
			Desc:               "cmd.delete_norm.desc",
			ErrNothingToDelete: "cmd.delete_norm.err_nothing_to_delete",
			Example:            "cmd.delete_norm.example",
		},
		EndRest: struct {
			Desc          MessageID
			Ended         MessageID
			EndedSelf     MessageID
			NotInRest     MessageID
			NotInRestSelf MessageID
		}{
			Desc:          "cmd.end_rest.desc",
			Ended:         "cmd.end_rest.ended",
			EndedSelf:     "cmd.end_rest.ended_self",
			NotInRest:     "cmd.end_rest.not_in_rest",
			NotInRestSelf: "cmd.end_rest.not_in_rest_self",
		},
		Help: struct {
			AliasesLabel MessageID
			Body         MessageID
			Desc         MessageID
			Examples     MessageID
			Syntax       MessageID
		}{
			AliasesLabel: "cmd.help.aliases_label",
			Body:         "cmd.help.body",
			Desc:         "cmd.help.desc",
			Examples:     "cmd.help.examples",
			Syntax:       "cmd.help.syntax",
		},
		HelpCommand: struct {
			Desc MessageID
		}{
			Desc: "cmd.help_command.desc",
		},
		ListNorms: struct {
			Desc  MessageID
			Empty MessageID
			Item  MessageID
			Title MessageID
		}{
			Desc:  "cmd.list_norms.desc",
			Empty: "cmd.list_norms.empty",
			Item:  "cmd.list_norms.item",
			Title: "cmd.list_norms.title",
		},
		Moderation: struct {
			SetRole struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}
			SetRoleAdmin struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}
		}{
			SetRole: struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}{
				ChatAdmin:   "cmd.moderation.set_role.chat_admin",
				ChatCreator: "cmd.moderation.set_role.chat_creator",
				Desc:        "cmd.moderation.set_role.desc",
				NoRights:    "cmd.moderation.set_role.no_rights",
				Set:         "cmd.moderation.set_role.set",
			},
			SetRoleAdmin: struct {
				ChatAdmin   MessageID
				ChatCreator MessageID
				Desc        MessageID
				NoRights    MessageID
				Set         MessageID
			}{
				ChatAdmin:   "cmd.moderation.set_role_admin.chat_admin",
				ChatCreator: "cmd.moderation.set_role_admin.chat_creator",
				Desc:        "cmd.moderation.set_role_admin.desc",
				NoRights:    "cmd.moderation.set_role_admin.no_rights",
				Set:         "cmd.moderation.set_role_admin.set",
			},
		},
		Profile: struct {
			Activity        MessageID
			Desc            MessageID
			ExampleDate     MessageID
			ExampleDuration MessageID
			MemberPeriod    MessageID
			MemberSince     MessageID
			NormFailed      MessageID
			NormPassed      MessageID
			RestExempt      MessageID
			RestUntil       MessageID
			Title           MessageID
			TotalMessages   MessageID
		}{
			Activity:        "cmd.profile.activity",
			Desc:            "cmd.profile.desc",
			ExampleDate:     "cmd.profile.example_date",
			ExampleDuration: "cmd.profile.example_duration",
			MemberPeriod:    "cmd.profile.member_period",
			MemberSince:     "cmd.profile.member_since",
			NormFailed:      "cmd.profile.norm_failed",
			NormPassed:      "cmd.profile.norm_passed",
			RestExempt:      "cmd.profile.rest_exempt",
			RestUntil:       "cmd.profile.rest_until",
			Title:           "cmd.profile.title",
			TotalMessages:   "cmd.profile.total_messages",
		},
		Rest: struct {
			Desc       MessageID
			Info       MessageID
			InfoReason MessageID
			NoRest     MessageID
			Set        MessageID
			SetReason  MessageID
		}{
			Desc:       "cmd.rest.desc",
			Info:       "cmd.rest.info",
			InfoReason: "cmd.rest.info_reason",
			NoRest:     "cmd.rest.no_rest",
			Set:        "cmd.rest.set",
			SetReason:  "cmd.rest.set_reason",
		},
		RestRequest: struct {
			ApproveButton MessageID
			Approved      MessageID
			ApprovedShort MessageID
			Created       MessageID
			Empty         MessageID
			Item          MessageID
			NoRequest     MessageID
			RejectButton  MessageID
			Rejected      MessageID
			Text          MessageID
			TextReason    MessageID
			Title         MessageID
		}{
			ApproveButton: "cmd.rest_request.approve_button",
			Approved:      "cmd.rest_request.approved",
			ApprovedShort: "cmd.rest_request.approved_short",
			Created:       "cmd.rest_request.created",
			Empty:         "cmd.rest_request.empty",
			Item:          "cmd.rest_request.item",
			NoRequest:     "cmd.rest_request.no_request",
			RejectButton:  "cmd.rest_request.reject_button",
			Rejected:      "cmd.rest_request.rejected",
			Text:          "cmd.rest_request.text",
			TextReason:    "cmd.rest_request.text_reason",
			Title:         "cmd.rest_request.title",
		},
		Rests: struct {
			Delete struct {
				Deleted       MessageID
				DeletedActive MessageID
				Desc          MessageID
			}
			Desc              MessageID
			HistoryEmpty      MessageID
			HistoryItem       MessageID
			HistoryItemReason MessageID
			HistoryTitle      MessageID
			HistoryTotal      MessageID
		}{
			Delete: struct {
				Deleted       MessageID
				DeletedActive MessageID
				Desc          MessageID
			}{
				Deleted:       "cmd.rests.delete.deleted",
				DeletedActive: "cmd.rests.delete.deleted_active",
				Desc:          "cmd.rests.delete.desc",
			},
			Desc:              "cmd.rests.desc",
			HistoryEmpty:      "cmd.rests.history_empty",
			HistoryItem:       "cmd.rests.history_item",
			HistoryItemReason: "cmd.rests.history_item_reason",
			HistoryTitle:      "cmd.rests.history_title",
			HistoryTotal:      "cmd.rests.history_total",
		},
		ShowNorm: struct {
			AllMembers MessageID
			Body       MessageID
			Desc       MessageID
			Example    MessageID
			Members    MessageID
			NotFound   MessageID
		}{
			AllMembers: "cmd.show_norm.all_members",
			Body:       "cmd.show_norm.body",
			Desc:       "cmd.show_norm.desc",
			Example:    "cmd.show_norm.example",
			Members:    "cmd.show_norm.members",
			NotFound:   "cmd.show_norm.not_found",
		},
		Stats: struct {
			Desc            MessageID
			ExampleDate     MessageID
			ExampleDuration MessageID
			Failed          MessageID
			NormTitle       MessageID
			Passed          MessageID
			Title           MessageID
			TotalMessages   MessageID
			UserFailed      MessageID
			UserPassed      MessageID
		}{
			Desc:            "cmd.stats.desc",
			ExampleDate:     "cmd.stats.example_date",
			ExampleDuration: "cmd.stats.example_duration",
			Failed:          "cmd.stats.failed",
			NormTitle:       "cmd.stats.norm_title",
			Passed:          "cmd.stats.passed",
			Title:           "cmd.stats.title",
			TotalMessages:   "cmd.stats.total_messages",
			UserFailed:      "cmd.stats.user_failed",
			UserPassed:      "cmd.stats.user_passed",
		},
		Summon: struct {
			AlreadyRunning MessageID
			Completed      MessageID
			Confirm        struct {
				Canceled             MessageID
				Disabled             MessageID
				No                   MessageID
				OnlyInitiatorCancel  MessageID
				OnlyInitiatorConfirm MessageID
				Text                 MessageID
				Yes                  MessageID
				YesAndDisable        MessageID
			}
			Desc MessageID
			Reg  struct {
				Desc MessageID
				Set  MessageID
			}
			Style struct {
				Desc   MessageID
				Emoji  MessageID
				Name   MessageID
				Role   MessageID
				Text   MessageID
				Toggle struct {
					Desc MessageID
				}
			}
			Unreg struct {
				Desc MessageID
				Set  MessageID
			}
		}{
			AlreadyRunning: "cmd.summon.already_running",
			Completed:      "cmd.summon.completed",
			Confirm: struct {
				Canceled             MessageID
				Disabled             MessageID
				No                   MessageID
				OnlyInitiatorCancel  MessageID
				OnlyInitiatorConfirm MessageID
				Text                 MessageID
				Yes                  MessageID
				YesAndDisable        MessageID
			}{
				Canceled:             "cmd.summon.confirm.canceled",
				Disabled:             "cmd.summon.confirm.disabled",
				No:                   "cmd.summon.confirm.no",
				OnlyInitiatorCancel:  "cmd.summon.confirm.only_initiator_cancel",
				OnlyInitiatorConfirm: "cmd.summon.confirm.only_initiator_confirm",
				Text:                 "cmd.summon.confirm.text",
				Yes:                  "cmd.summon.confirm.yes",
				YesAndDisable:        "cmd.summon.confirm.yes_and_disable",
			},
			Desc: "cmd.summon.desc",
			Reg: struct {
				Desc MessageID
				Set  MessageID
			}{
				Desc: "cmd.summon.reg.desc",
				Set:  "cmd.summon.reg.set",
			},
			Style: struct {
				Desc   MessageID
				Emoji  MessageID
				Name   MessageID
				Role   MessageID
				Text   MessageID
				Toggle struct {
					Desc MessageID
				}
			}{
				Desc:  "cmd.summon.style.desc",
				Emoji: "cmd.summon.style.emoji",
				Name:  "cmd.summon.style.name",
				Role:  "cmd.summon.style.role",
				Text:  "cmd.summon.style.text",
				Toggle: struct {
					Desc MessageID
				}{
					Desc: "cmd.summon.style.toggle.desc",
				},
			},
			Unreg: struct {
				Desc MessageID
				Set  MessageID
			}{
				Desc: "cmd.summon.unreg.desc",
				Set:  "cmd.summon.unreg.set",
			},
		},
		UnassignNorm: struct {
			Desc       MessageID
			Example    MessageID
			NoUsers    MessageID
			Unassigned MessageID
		}{
			Desc:       "cmd.unassign_norm.desc",
			Example:    "cmd.unassign_norm.example",
			NoUsers:    "cmd.unassign_norm.no_users",
			Unassigned: "cmd.unassign_norm.unassigned",
		},
	}
	Common = struct {
		Close MessageID
	}{
		Close: "common.close",
	}
	Status = struct {
		Coowner     MessageID
		JuniorAdmin MessageID
		Member      MessageID
		Moderator   MessageID
		Owner       MessageID
		SeniorAdmin MessageID
	}{
		Coowner:     "status.coowner",
		JuniorAdmin: "status.junior_admin",
		Member:      "status.member",
		Moderator:   "status.moderator",
		Owner:       "status.owner",
		SeniorAdmin: "status.senior_admin",
	}
	System = struct {
		AddBotButton    MessageID
		BotAdded        MessageID
		BotAddedAdmin   MessageID
		BotCommands     MessageID
		NoPermission    MessageID
		UsernameChanged struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}
	}{
		AddBotButton:  "system.add_bot_button",
		BotAdded:      "system.bot_added",
		BotAddedAdmin: "system.bot_added_admin",
		BotCommands:   "system.bot_commands",
		NoPermission:  "system.no_permission",
		UsernameChanged: struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}{
			Female:  "system.username_changed.female",
			Male:    "system.username_changed.male",
			Unknown: "system.username_changed.unknown",
		},
	}
	User = struct {
		Joined struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}
		Left struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}
		Returned struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}
		Unknown MessageID
	}{
		Joined: struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}{
			Female:  "user.joined.female",
			Male:    "user.joined.male",
			Unknown: "user.joined.unknown",
		},
		Left: struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}{
			Female:  "user.left.female",
			Male:    "user.left.male",
			Unknown: "user.left.unknown",
		},
		Returned: struct {
			Female  MessageID
			Male    MessageID
			Unknown MessageID
		}{
			Female:  "user.returned.female",
			Male:    "user.returned.male",
			Unknown: "user.returned.unknown",
		},
		Unknown: "user.unknown",
	}
)

type CmdRestRequestEmptyData struct {
	User any
}

type CmdRestRequestTextData struct {
	User any
	Date any
}

type CmdRestRequestTextReasonData struct {
	User   any
	Date   any
	Reason any
}

type CmdRestRequestApprovedData struct {
	User any
	Date any
}

type CmdRestRequestTitleData struct {
	User any
}

type CmdRestRequestItemData struct {
	Index any
	From  any
	To    any
}

type CmdHelpBodyData struct {
	CommandsLink  any
	DeveloperLink any
}

type CmdRestInfoData struct {
	User any
	Date any
}

type CmdRestInfoReasonData struct {
	User   any
	Date   any
	Reason any
}

type CmdRestNoRestData struct {
	User any
}

type CmdRestSetData struct {
	User any
	Date any
}

type CmdRestSetReasonData struct {
	User   any
	Date   any
	Reason any
}

type CmdRestsHistoryItemData struct {
	Index    any
	From     any
	To       any
	Duration any
}

type CmdRestsHistoryItemReasonData struct {
	Index    any
	From     any
	To       any
	Duration any
	Reason   any
}

type CmdRestsHistoryTotalData struct {
	Count any
}

type CmdRestsHistoryEmptyData struct {
	User any
}

type CmdRestsHistoryTitleData struct {
	User any
}

type CmdStatsTitleData struct {
	From any
	To   any
}

type CmdStatsUserFailedData struct {
	List     any
	User     any
	Messages any
	Required any
}

type CmdStatsNormTitleData struct {
	Name     any
	Required any
}

type CmdStatsTotalMessagesData struct {
	Total any
}

type CmdStatsUserPassedData struct {
	List     any
	User     any
	Messages any
}

type CmdDeleteNormDeletedData struct {
	Name any
}

type CmdDeleteNormErrNothingToDeleteData struct {
	Name any
}

type CmdListNormsItemData struct {
	Name  any
	Value any
}

type CmdAssignNormAssignedData struct {
	Name any
}

type CmdEndRestEndedData struct {
	User any
}

type CmdEndRestNotInRestData struct {
	User any
}

type CmdModerationSetRoleAdminSetData struct {
	User any
}

type CmdModerationSetRoleSetData struct {
	User any
}

type CmdAddNormErrInvalidValueData struct {
	Value any
	Min   any
	Max   any
}

type CmdAddNormAddedData struct {
	Name  any
	Value any
}

type CmdShowNormNotFoundData struct {
	Name    any
	Code    any
	CodeEnd any
}

type CmdShowNormBodyData struct {
	Name  any
	Value any
}

type CmdProfileTotalMessagesData struct {
	Total any
}

type CmdProfileTitleData struct {
	User any
}

type CmdProfileMemberSinceData struct {
	Date any
	Days any
}

type CmdProfileActivityData struct {
	Day          any
	Week         any
	Month        any
	DayRolling   any
	WeekRolling  any
	MonthRolling any
	Total        any
}

type CmdProfileRestUntilData struct {
	Date any
}

type CmdProfileNormPassedData struct {
	Name     any
	Required any
}

type CmdProfileNormFailedData struct {
	Name     any
	Current  any
	Required any
}

type CmdProfileMemberPeriodData struct {
	From any
	To   any
	Days any
}

type CmdUnassignNormUnassignedData struct {
	Name any
}

type SystemNoPermissionData struct {
	Status any
}

type SystemUsernameChangedMaleData struct {
	User        any
	OldUsername any
	NewUsername any
}

type SystemUsernameChangedFemaleData struct {
	User        any
	OldUsername any
	NewUsername any
}

type SystemUsernameChangedUnknownData struct {
	User        any
	OldUsername any
	NewUsername any
}

type UserJoinedMaleData struct {
	User any
}

type UserJoinedFemaleData struct {
	User any
}

type UserJoinedUnknownData struct {
	User any
}

type UserReturnedUnknownData struct {
	User any
}

type UserReturnedMaleData struct {
	User any
}

type UserReturnedFemaleData struct {
	User any
}

type UserLeftMaleData struct {
	User any
}

type UserLeftFemaleData struct {
	User any
}

type UserLeftUnknownData struct {
	User any
}
